[FE] issue94: 스터디 개설 페이지 구현
woowacourse-teams/2022-moamoa pull request #117
Opened 2022-07-25 04:28 UTC by airman5573

## 요약
스터디 개설 페이지를 구현했습니다.

## 세부사항
- 이미지 업로드 기능 구현 못했음
- UI 개선이 필요함

close #94

2022-07-25 12:13 UTC, nan-noo requested changes

2022-07-25 12:13 UTC, nan-noo commented on frontend/src/pages/create-study-page/components/period/Peroid.tsx
> +            <input type="date" id="end-date" min={today} max="2030-07-20" {...register('end-date')}></input>
max값도 바꿔야 동적으로 바뀌는 게 좋을 것 같아요!

2022-07-25 12:13 UTC, nan-noo commented on frontend/src/pages/create-study-page/hooks/usePostNewStudy.ts
> +  return useMutation('post-new-study', postNewStudy);
useMutation은 key가 필수가 아닌데 쓴 이유가 있나요?

2022-07-25 12:13 UTC, nan-noo commented on frontend/src/utils/getToday.ts
> +  return koKRDate.replaceAll(' ', '').replaceAll(/\./g, '-').slice(0, -1);
2022.07.20 형식으로 나왔으면 좋겠어요!

2022-07-25 13:10 UTC, airman5573 commented on frontend/src/api/axiosInstance.ts
> +);
accessToken이 있는 경우에만 Authorization header를 넣는게 적절하다고 생각했습니다.

2022-07-25 13:14 UTC, airman5573 commented on frontend/src/api/postNewStudy.ts
> +  const response = await axiosInstance.post<any, any, StudyDetailPostData>(`/api/studies`, data);
보내주신 링크에는 
`post<T = never, R = AxiosResponse<T>>(url: string, data?: T, co` 이렇게 나와있는데  
axios 코드에는
`post<T = any, R = AxiosResponse<T>, D = any>(url: string, data?: D, config?: AxiosRequestConfig<D>): Promise<R>;` 이렇게 나와있네요. 에러가 안나는걸 보면 axios코드에 나와있는게 맞는듯 싶습니다!

2022-07-25 13:28 UTC, airman5573 commented on frontend/src/components/button/Button.tsx
> +  isLoading?: boolean;
아 같은 boolean임에도 is를 안붙인게 저도 좀 마음에 걸리긴 하는데,  
isLoading은 외부 상태를 바탕으로 모양을 결정하기 위해 넣은 속성이라면, fluid나 outline은 상태가 아닌 모양을 위한 속성이라서  
상태에 어울리는 `is`는 outline에 붙이기에는 조금 부자연스럽지 않나 생각이 듭니다.

2022-07-25 13:29 UTC, airman5573 commented on frontend/src/components/positive-number-input/PositiveNumberInput.tsx
> +  id?: string;
네, `<input id="my-input" />` 이런 식으로 쓸수도 있어서 string이 적절하다고 생각합니다.

2022-07-25 13:35 UTC, airman5573 commented on frontend/src/components/positive-number-input/PositiveNumberInput.tsx
> +  onChange: (val: number) => void;
이미 사용자(개발자)는 `PositiveNumberInput`를 쓰고 있기 때문에 구태여 `handlePositiveNumberInput`를 붙여줄 필요는 없다고 생각합니다.  

그리고 `onChange: (val: number) => void;` 이거는 "change가 일어날때 뭘할지 넣어주세요" 이런 의미이고  
`handleChange`는 "change가 일어날때 내가 뭘 하겠다" 이런 의미가 있다고 생각합니다. 그래서 보통 `onClick = {handleClick}` 이렇게 넣어 준다고 생각합니다.

2022-07-25 13:37 UTC, airman5573 commented on frontend/src/components/positive-number-input/PositiveNumberInput.tsx
> +    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
handling할 change가 number input밖에 없어서 굳이 안써줘도 될것 같습니다!

2022-07-25 13:38 UTC, airman5573 commented on frontend/src/components/positive-number-input/PositiveNumberInput.tsx
> +        value={value === 0 ? '' : value}
01이 입력되는 일을 막기 위해서 한건데,,,0만 넣어보고 싶은 경우가 있어서 사용자 경험이 썩 좋다고 보기는 어렵군요.  
개선해보겠습니다 :D

2022-07-25 13:39 UTC, airman5573 commented on frontend/src/components/positive-number-input/PositiveNumberInput.tsx
> +PositiveNumberInput.displayName = 'PositiveNumberInput';
원래는 babel의 preset안에서 displayName을 자동으로 넣어주는데, forwardRef는 그게 안되는것 같습니다. 그래서 이렇게 직접 설정해준겁니다.  

displayName은 개발자 도구에 보이는 컴포넌트의 이름을 의미합니다.

2022-07-26 01:32 UTC, nan-noo commented on frontend/src/components/positive-number-input/PositiveNumberInput.tsx
> +  id?: string;
클래스, 아이디 할 때 아이디였군요! 데이터 아이디인 줄 알았어요

2022-07-26 01:40 UTC, nan-noo commented on frontend/src/hooks/useForm.tsx
> +  _ref: HTMLInputElement;
저는 ref는 명시를 안 하면 current 속성이 있는지 없는지 헷갈리더라구요! 그래서 항상 ref라고 뒤에 붙이는 편이에요.
_fields -> elementFieldsRef나 inputFieldsRef, inputsRef, ... 
_ref -> elementRef, inputRef, ...  : 애초에 얘는 타입이 HTMLInputElement이니까 이거 따라 이름 붙이면 될 거 같아요

2022-07-26 01:43 UTC, nan-noo commented on frontend/src/api/postNewStudy.ts
> +  const response = await axiosInstance.post<any, any, StudyDetailPostData>(`/api/studies`, data);
그러면 response 타입도 넣어주면 좋을 것 같아요 any말고!

2022-07-26 05:48 UTC, airman5573 commented on frontend/src/utils/getToday.ts
> +  return koKRDate.replaceAll(' ', '').replaceAll(/\./g, '-').slice(0, -1);
수정 했습니다 :D [b9bc0dc](https://github.com/woowacourse-teams/2022-moamoa/pull/117/commits/b9bc0dc89eccac302e618fa853d2b90124dcfc42)

2022-07-26 05:56 UTC, airman5573 commented on frontend/src/pages/create-study-page/hooks/usePostNewStudy.ts
> +  return useMutation('post-new-study', postNewStudy);
필수가 아니었군요!  

[공식문서](https://tanstack.com/query/v4/docs/reference/useMutation?from=reactQueryV3&original=https://react-query-v3.tanstack.com/reference/useMutation)를 보면 
```A mutation key can be set to inherit defaults set with queryClient.setMutationDefaults or to identify the mutation in the devtools.```
이렇게 나와있는데, devtools를 쓸때는 의미가 있는것 같습니다.  
그런데 지금은 빼도 될것 같아요 :D  [57c2f5d](https://github.com/woowacourse-teams/2022-moamoa/pull/117/commits/57c2f5dae5912b233e183a2ff441d2fcaefe1ce2)

2022-07-26 06:21 UTC, airman5573 commented on frontend/src/pages/create-study-page/components/category/Category.tsx
> +    const areaBE = areas.find(({ name }) => name.toLowerCase() === 'be');
수정했습니다 :D [95a3337](https://github.com/woowacourse-teams/2022-moamoa/pull/117/commits/95a3337fb269dbb8dc900c349f086bd911df0825)

2022-07-26 06:24 UTC, airman5573 commented on frontend/src/pages/create-study-page/components/category/Category.tsx
> +    if (isLoading) return <div>loading...</div>;
수정했습니다 :D [f1e50d5](https://github.com/woowacourse-teams/2022-moamoa/pull/117/commits/f1e50d5bfef0904b1c4eaa6b28076b7bd60eabbb)

2022-07-26 06:28 UTC, airman5573 commented on frontend/src/hooks/useForm.tsx
> +    return null;
early return은 좋은것 같아요 :D  
근데 try-catch는 사용자에게 throw new Error()를 강제해야 해서 조금 (개발자 입장에서) 쓰기가 불편하지 않을까 싶어요!  
우선 코드를 정리해봤는데, 한번 확인 부탁드립니다 :D  
[aa1c8a8](https://github.com/woowacourse-teams/2022-moamoa/pull/117/commits/aa1c8a8b1a07584b1695d2b949c4b6945af87806)

2022-07-26 08:25 UTC, airman5573 commented on frontend/src/hooks/useForm.tsx
> +      console.log('errorMessage : ', errorMessage);
으악!

2022-07-26 08:29 UTC, airman5573 commented on frontend/src/hooks/useForm.tsx
> +  _ref: HTMLInputElement;
수정 했습니다 :D [88c41f0](https://github.com/woowacourse-teams/2022-moamoa/pull/117/commits/88c41f0a666b9a04fdaa4e01e888d2ffb45ae5ba)

2022-07-26 09:22 UTC, airman5573 commented on frontend/src/components/positive-number-input/PositiveNumberInput.tsx
> +        type="text"
양의정수만 받고 싶은데, number로 하면 -를 handleChange에서 못받습니다!  
테스트 : [https://codesandbox.io/s/polished-fast-v6m2w7?file=/src/_app.js](https://codesandbox.io/s/polished-fast-v6m2w7?file=/src/_app.js)

2022-07-26 10:30 UTC, airman5573 commented on frontend/src/components/positive-number-input/PositiveNumberInput.tsx
> +    };
[이렇게](https://codesandbox.io/s/infallible-surf-yg0kgn?file=/src/_app.js)도 가능한데,,,중간에 스트링을 입력하면 커서가 오른쪽 끝으로 이동합니다!

2022-07-26 10:36 UTC, airman5573 commented on frontend/src/components/button/Button.style.ts
> +const outlineButtonStyleFn: OutlineButtonStyleFn = ({ theme, isLoading }) => css`
수정했습니다 :D  [e2b33f6](https://github.com/woowacourse-teams/2022-moamoa/pull/117/commits/e2b33f664ead9c2736ccdc63ff8726b46bdaa3fe)

2022-07-26 11:00 UTC, airman5573 commented on frontend/src/hooks/useForm.tsx
> +  !_fields.current && (_fields.current = new Map<string, Field>());
수정했습니다 :D   [88c41f0](https://github.com/woowacourse-teams/2022-moamoa/pull/117/commits/88c41f0a666b9a04fdaa4e01e888d2ffb45ae5ba)

2022-07-26 11:01 UTC, airman5573 commented on frontend/src/components/positive-number-input/PositiveNumberInput.tsx
> +      const { target } = e;
수정했습니다 :D [51f3933](https://github.com/woowacourse-teams/2022-moamoa/pull/117/commits/51f3933b3a1737560207013050017548861f37f9)

2022-07-26 11:02 UTC, airman5573 commented on frontend/src/components/positive-number-input/PositiveNumberInput.tsx
> +        className={className}
수정헀습니다 :D  [cb83092](https://github.com/woowacourse-teams/2022-moamoa/pull/117/commits/cb83092310d709bf81f8239c28ae60e167b5422d)

2022-07-26 11:04 UTC, airman5573 commented on frontend/src/api/postNewStudy.ts
> +  const response = await axiosInstance.post<any, any, StudyDetailPostData>(`/api/studies`, data);
수정했습니다 :D   [5ba601d](https://github.com/woowacourse-teams/2022-moamoa/pull/117/commits/5ba601d0f8935f1a51722d8f2dd350813bb3f261)

2022-07-26 11:04 UTC, airman5573 commented on frontend/.storybook/main.js
>        '@layout': resolve(__dirname, '../src/layout'),
수정헀습니다 :D  [6a5e4d1](https://github.com/woowacourse-teams/2022-moamoa/pull/117/commits/6a5e4d1ef308dc141163c97df02bdfb92a12b92e)

2022-07-26 11:19 UTC, nan-noo commented on frontend/src/components/positive-number-input/PositiveNumberInput.tsx
>      const newValueNum = Number(newValueStr);
얘를 onChange에 바로 넣어줘도 될 것 같아요

2022-07-26 11:32 UTC, nan-noo approved these changes

2022-07-26 11:32 UTC, merged