[BE] issue129: 원하는 갯수만큼 작성된 후기 조회
woowacourse-teams/2022-moamoa pull request #136
Opened 2022-07-26 09:32 UTC by wilgur513

resolve: #129

2022-07-27 23:55 UTC, tco0427 reviewed
구현 고생하셨습니다👍
궁금한 사항과 몇가지 제안사항 코멘트로 남겨보았습니다!
`CategoryIdRequest`와 `Converter`에 대해서는 잘 모르겠어서 설명을 들어보고 싶습니다!

2022-07-27 23:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/review/controller/ReviewController.java
> +            @RequestParam(name = "size", required = false, defaultValue = "") SizeRequest sizeRequest
`SizeRequest` 라는 DTO로 감싸주었군요..!!
기존의 `@RequestParam(required = false) Integer size` 와는 어떤 차이가 있는지 궁금합니다!!

2022-07-27 23:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/review/controller/converter/SizeRequestConverter.java
> +    }
음..빈 값을 포함한 요청일 때마다 Converter 가 추가된다면 관리가 힘들지 않을까하는 생각이 들어요..ㅠ.ㅠ🥲

2022-07-27 23:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/review/service/ReviewService.java
> +            return new ReviewsResponse(allReviews);
단순 Integer가 아닌 DTO로 관리하니 `isMoreThan` 과 같은 메소드 호라용이 가능하군요..!!

2022-07-27 23:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/review/controller/ReviewControllerTest.java
> +    private static final MemberData VERUS = new MemberData(4L, "verus", "https://image", "github.com");
자주 쓰이는 것 같아요!! Fixture로 빼도 될 것 같습니다!!

2022-07-27 23:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/review/controller/ReviewControllerTest.java
> +    }
메소드명과 parameter 를 보고 기능을 알 수 있을 것 같네요! (코드를 보지 않아도)
해당 메소드를 맨 아래로 내려도 괜찮을 것 같아요!

2022-07-28 01:29 UTC, jaejae-yoo requested changes
베루스 구현하느라 고생하셨습니다 코멘트 확인 부탁드려요 ~

2022-07-28 01:29 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/review/query/ReviewDao.java
> +        String sql = "SELECT r.id, r.content, r.created_date, r.last_modified_date, "
r로 축약하지 않고 review로 선언해도 길이가 길 것 같지 않아서 더 명확하게 표현하는 것은 어떨까요 ?!

2022-07-28 01:29 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/moamoa/review/controller/BadRequestReviewControllerTest.java
> +    private ReviewService reviewService;
요청 값 예외 확인을 위한 테스트 클래스라서, 선언해도 쓰이지 않을 빈일 것 같은데 제거해도 되지 않을까요 ?

2022-07-28 01:59 UTC, sc0116 approved these changes
코드 짜느라 고생했어요 베루시우스! 몇가지 코멘트 남겼슴당

2022-07-28 01:59 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/review/controller/converter/SizeRequestConverter.java
> +    }
아래에도 CategoryIdConverter가 있던데 비슷한 처리를 할 때마다 Converter를 만드는 방법 이외에 더 좋은 방법은 없을까요?? 아니면 혹시 Converter가 꼭 필요한 이유가 있을까요?

2022-07-28 01:59 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/review/query/ReviewDao.java
> +        String sql = "SELECT r.id, r.content, r.created_date, r.last_modified_date, "
저는 이 부분은 그렇게 나쁘다고 생각하지 않습니다! sql에서 review r, member m 자체가 테이블의 별칭을 지어주는건데 여기에 굳이 또 review를 하는 것은 의미가 없다고 생각해요!

2022-07-28 01:59 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/review/service/request/SizeRequest.java
> +            throw new IllegalStateException("SizeRequest에 value가 null 입니다.");
BadRequestException을 상속하는 예외 클래스를 만들어도 좋을 것 같아요

2022-07-28 08:54 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/review/service/request/SizeRequest.java
> +            throw new IllegalStateException("SizeRequest에 value가 null 입니다.");
500 응답을 던지도록 ControllerAdvice 수정

2022-07-28 08:54 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/review/service/response/ReviewResponse.java
>      private String content;
LocalDate 로 변경

2022-07-29 04:49 UTC, tco0427 approved these changes

2022-07-29 05:49 UTC, jaejae-yoo approved these changes

2022-07-29 06:07 UTC, merged