[BE] issue119: 내가 참여한 스터디 목록 조회
woowacourse-teams/2022-moamoa pull request #138
Opened 2022-07-26 12:06 UTC by jaejae-yoo

## 요약
내가 참여한 스터디 목록을 조회한다.

## 세부사항
- 내가 참여한 스터디 조회 인수 테스트 작성

close

2022-07-27 23:15 UTC, tco0427 requested changes
상태가 2가지로 변경되면서 변경점이 많은 것 같네요..!!
하나하나 수정해주시느라 고생하셨습니다!!👍

2022-07-27 23:15 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/AuthenticationInterceptor.java
> +                request.getMethod().equals("GET") && request.getServletPath().equals("/api/my/studies")) {
이제 study 생성 이외에도 `내 스터디 조회` 시에도 토큰이 필요하게 되어 위와 같은 변경이 발생했군요!!
흠..🤔

```java
    @Override
    public boolean preHandle(final HttpServletRequest request, final HttpServletResponse response, final Object handler) {
        if (isPreflight(request)) {
            return true;
        }

        final String token = AuthenticationExtractor.extract(request);

        if (token != null) {
            validateToken(token);
            
            request.setAttribute("payload", tokenProvider.getPayload(token));
        }

        return true;
    }

    private void validateToken(String token) {
        if (!tokenProvider.validateToken(token)) {
            throw new UnauthorizedException("유효하지 않은 토큰입니다.");
        }
    }
```

이와 같이 `토큰이 있는 경우` 즉 토큰이 포함된 요청인 경우에 토큰의 유효성을 검사하는 방향으로 수정하면 어떨까요??
기존의 코드는 새로운 `토큰을 동반한 요청`의 경우 계속해서 case가 추가되어 코드가 변경되어야할 것 같아요 ㅠ.ㅠ

2022-07-27 23:15 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/member/query/MemberDao.java
>      }
오!! `NamedParameterJdbcTemplate` 으로 변경 굿굿!👍

2022-07-27 23:15 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/member/query/MemberDao.java
> +        List<String> temp = studyIds.stream().map(Object::toString).collect(Collectors.toList());;
이 부분 한줄씩 띄워도 될 것 같아요!!😃

2022-07-27 23:15 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/controller/MyStudyController.java
> +    @GetMapping("/api/my/studies")
이건 front 와도 이야기해보아야 하는 사항인데 "/api/studies/me" 와 같은 방향은 어떨까요??
(study 라고 하는 자원들 중 me (나의것))
사용자에게 보여지는(브라우저 상단의) URL 은 `moamoa.space/myPage` 등과 같은 방향이 맞지만, 자원을 표기하는 REST API의 URI 에서 `my` 라는 부사(?)가 어색하게 느껴지네요..ㅠ.ㅠ

이전에 장바구니 때에 참고하였던 사이트 공유합니다!😃
[참고 사이트](https://www.a-mean-blog.com/ko/blog/Node-JS-API/_/JWT-JSON-Web-Token-%EB%A1%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8-REST-API-%EB%A7%8C%EB%93%A4%EA%B8%B0)

2022-07-27 23:15 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Details.java
> +        return Objects.hash(title, excerpt, thumbnail, recruitStatus, studyStatus, description);
equals & hash code 까지 꼼꼼하게! 굿!👍

2022-07-27 23:15 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/study/GettingMyStudiesAcceptanceTest.java
> +                .body("studies[0].tags[2].name", is("React"));
내가 참여한 스터디들 중에 첫번째 것만 확인한다 라고 이해해도 될까요??

태그 쪽은
```java
                .body("studies[0].tags.id", contains(2, 4, 5))
                .body("studies[0].tags.name", contains("4기", "FE", "React"));
```

와 같이 간단하게 나타내는게 더 가독성 있을 것 같아요!

2022-07-27 23:15 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/controller/MyStudyControllerTest.java
> +}
EOF!!

2022-07-27 23:15 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/query/MyStudyDaoTest.java
> +}
EOF!!

2022-07-27 23:15 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/service/MyStudyServiceTest.java
> +}
EOF!!

2022-07-28 02:44 UTC, wilgur513 requested changes

2022-07-28 02:44 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/member/query/MemberDao.java
> +        List<String> temp = studyIds.stream().map(Object::toString).collect(Collectors.toList());;
세미콜론이 2개있어요!

2022-07-28 02:44 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Details.java
> +    private String studyStatus;
저희가 String으로 status 관리해왔는데 이참에 Enum으로 바꿔도 좋을 것 같아요

2022-07-28 02:44 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/MyStudyService.java
> +        }
이 부분은 데이터를 조회하기 전에 githubId에 해당하는 사용자가 있는지 확인하는데, Repository를 사용하는게 좋아보입니다.
githubId에 알맞은 사용자가 있는지 확인하는 경우는 비즈니스 로직인거 같습니다. 그래서 단순 데이터 조회가 아닌 경우에는 Repository를 사용하는게 좋아 보입니다.

2022-07-28 02:44 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/MyStudyService.java
> +                .collect(Collectors.toList());
studyId 개수에 따라서 N번 쿼리가 날라가는 N+1 문제가 발생한거 같아요.
StudyId별로 태그를 한번에 가져올 수 있도록 쿼리를 수정해야 할 것 같아요.

2022-07-28 02:44 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/study/controller/MyStudyControllerTest.java
> +        jdbcTemplate.update("INSERT INTO study(id, title, excerpt, thumbnail, recruit_status, study_status, description, current_member_count, created_at, owner_id, start_date, enrollment_end_date, e
몇가지는 쿼리문이 아니라 이미 만들어진 코드를 활용해 데이터를 생성할 수 있을 것 같아요.

2022-07-28 04:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/member/query/MemberDao.java
> +        List<String> temp = studyIds.stream().map(Object::toString).collect(Collectors.toList());;
여름이라 더워서 땀을 많이 흘린 것 같아요!😁

2022-07-29 05:46 UTC, tco0427 requested changes

2022-07-29 05:46 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/MyStudyService.java
> +            }
Request Change 보내는김에 혹시 이부분 `AddMyStudyResponse` 대충 이런식으로라도 분리해보는거 어떨까요??
반영 안하셔도 되요~

2022-07-29 06:03 UTC, wilgur513 approved these changes

2022-07-29 06:06 UTC, tco0427 approved these changes
고생하셨습니다!! Approve 할게염!

2022-07-29 06:16 UTC, merged