[BE] issue120: 스터디 리뷰 작성
woowacourse-teams/2022-moamoa pull request #140
Opened 2022-07-27 04:27 UTC by sc0116

## 요약

스터디 리뷰 작성 기능

## 세부사항

- 내가 참여한 스터디에 대해서만 후기를 작성할 수 있다.
- 내가 참여하지 않은 스터디에 후기를 작성 시 에러를 응답한다.

close #120

2022-07-27 23:36 UTC, tco0427 reviewed
구현 굿굿!!
빠트린 `final` 키워드와 같이 꼼꼼하게 체크해주신 것 같아 좋았습니다!😃
몇가지 궁금한 점들 포함하여 코멘트 남겼어요!

2022-07-27 23:36 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/AuthenticationInterceptor.java
>              validateToken(token);
여기도 `스터디 생성` 뿐 아니라 `리뷰 작성`에 대해서도 토큰이 필요해지면서 변경이 필요해졌군요..!!
그린론 코드에서는 `내 스터디 조회` 시에도 토큰일 필요하게 되어 변경이 발생하더라구요!

흠..🤔

```java
    @Override
    public boolean preHandle(final HttpServletRequest request, final HttpServletResponse response, final Object handler) {
        if (isPreflight(request)) {
            return true;
        }

        final String token = AuthenticationExtractor.extract(request);

        if (token != null) {
            validateToken(token);
            
            request.setAttribute("payload", tokenProvider.getPayload(token));
        }

        return true;
    }

    private void validateToken(String token) {
        if (!tokenProvider.validateToken(token)) {
            throw new UnauthorizedException("유효하지 않은 토큰입니다.");
        }
    }
```

이와 같이 `토큰이 있는 경우` 즉 토큰이 포함된 요청인 경우에 토큰의 유효성을 검사하는 방향으로 수정하면 어떨까요??
기존의 코드는 새로운 `토큰을 동반한 요청`의 경우 계속해서 case가 추가되어 코드가 변경되어야할 것 같아요 ㅠ.ㅠ

2022-07-27 23:36 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/common/advice/CommonControllerAdvice.java
> +    public ResponseEntity<Void> handleUnauthorized(final Exception e) {
혹시 이와같이 변경한 이유가 무엇일까요??

현재 잡는 예외가 하나라서 `@ExceptionHandler(UnauthorizedException.class)`와 같이 해도 좋을 것 같아요!

2022-07-27 23:36 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/common/advice/CommonControllerAdvice.java
> +    })
여기도!!

2022-07-27 23:36 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/member/query/MemberDao.java
> +        final String sql = "SELECT github_id, username, image_url, profile_url "
굿굿!!👍

2022-07-27 23:36 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/member/query/MemberDao.java
> +                + ")";
서브쿼리를 사용하셨군요..!! inner 쿼리에 `*` 대신 id 정도만 조회해봐도 동일한 결과가 나올 것 같아요!

2022-07-27 23:36 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/member/service/exception/InvalidMemberException.java
> +        super("회원을 찾을 수 없습니다.");
저도 Service 쪽 코드보다 Exception 에서 예외 메시지를 관리하는게 좋다고 생각합니다!

2022-07-27 23:36 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/review/domain/Review.java
> +    @Column(nullable = false, updatable = false)
`updatable false` 굿!!

2022-07-27 23:36 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/review/domain/Review.java
> +    }
음..🤔 생성자 체이닝이 아닌 정적 팩토리 메소드로 하신 이유가 있을까요??

2022-07-27 23:36 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Study.java
> -        validatePeriod(period);
혹시 기존의 코드에서 변경한 이유가 있을까요?? 짱구의 생각이 궁금합니다!

2022-07-27 23:36 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/exception/StudyNotFoundException.java
> +public class StudyNotFoundException extends NotFoundException {
아하..! 이렇게 상속의 용도로 NotFoundException을 만드신 거군요..!!
음..🤔 좋은 것 같은데요...??

2022-07-27 23:36 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/review/domain/ReviewTest.java
> +    void writeable() {
굿!!

2022-07-28 01:30 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/exception/StudyNotFoundException.java
> +public class StudyNotFoundException extends NotFoundException {
넵! NotFound 뿐만 아니라 BadRequest나 Unauthorized 관련 예외 클래스를 각각 만들면 controller advice에 계속 추가해줘야 하는 번거로움 때문에 한번 더 묶어봤습니당

2022-07-28 01:31 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/common/advice/CommonControllerAdvice.java
> +    public ResponseEntity<Void> handleUnauthorized(final Exception e) {
기존에는 여러 개를 받고 있어서 일단은 { }로 감쌌는데 병합하면서 수정하겠슴당

2022-07-28 01:38 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Study.java
> -        validatePeriod(period);
검증 로직이 위에 있어야 한다는 생각에서 변경하게 되었습니다! 검증 메소드에서 사용하는 now()와 실제 createAt에 넣어줄 now()를 동일하게 하기 위해 검증 전 선언했습니당

2022-07-28 01:39 UTC, jaejae-yoo requested changes
짱구 구현하느라 고생하셨어요! 코멘트 확인 부탁드려요 ~

2022-07-28 01:39 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/review/domain/Review.java
> +//    @Embedded
주석 제거해주시면 좋을 것 같아요 ~

2022-07-28 01:39 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/review/domain/exception/InvalidReviewException.java
> +    private static final String message = "스터디 시작 전 후기를 작성할 수 없습니다.";
상수 컨벤션 대문자면 좋을 것 같아요 !

2022-07-28 01:39 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/moamoa/review/webmvc/BadRequestReviewWebMvcTest.java
> +    @DisplayName("필수 데이터인 후기 내용이 없는 경우 400을 반환한다.")
위의 테스트와 차이가 있는지 궁금해요!

2022-07-28 01:47 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/review/domain/Review.java
> +//    @Embedded
아 여기 병합 후 바꿀 예정이라 남겨두었어요

2022-07-28 01:47 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/review/domain/exception/InvalidReviewException.java
> +    private static final String message = "스터디 시작 전 후기를 작성할 수 없습니다.";
요거 바로 수정할게욤

2022-07-28 01:48 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/moamoa/review/webmvc/BadRequestReviewWebMvcTest.java
> +    @DisplayName("필수 데이터인 후기 내용이 없는 경우 400을 반환한다.")
아마 ""와 null인데 DisplayName이 중복되었군요

2022-07-28 02:32 UTC, wilgur513 requested changes

2022-07-28 02:32 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/review/domain/Review.java
>      private Member member;
연관 매핑을 사용한 이유가 있나요??
아래 주석처럼 Embedded로 memberId를 가진 Reviewer로 써도 될꺼 같아요

2022-07-28 02:32 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/review/domain/Review.java
> +    }
이미 아래에 생성자가 있어서 정적 팩토리 메서드를 만들 이유가 없어 보입니다.

2022-07-28 02:32 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/review/domain/Review.java
> +    }
Review에 두지 말고 Service 계층에 두는건 어떨까요?

2022-07-28 02:32 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/review/service/ReviewService.java
> +    }
checkParticipate는 어떤걸 체크하는지에 대한 의미를 전혀 전달하지 못하는것 같아요...

2022-07-28 02:32 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/review/service/ReviewService.java
> +    private final MemberDao memberDao;
ReviewService에 Repository와 Dao 두가지를 사용하고 있는데 사용하는 용도가 서로 달라 분리시키는게 좋아 보입니다.
Repository는 명령을 위해 DB에서 데이터를 조회해 객체로 매핑하는 용도이고, Dao는 조회를 위해 DB에서 데이터를 조회해 DTO로 변환해 전달하는 용도입니다. 이 부분을 별도의 Service 클래스를 두어 분리시켜두는게 좋을 것 같습니다.

2022-07-28 02:32 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/review/service/ReviewService.java
> +    }
이 부분은 데이터를 외부로 전달하기 위한 조회가 아닌 명령을 위해서 DB를 조회하기 때문에, Repository에서 확인하는게 좋아보입니다.

2022-07-28 02:46 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/AuthenticationInterceptor.java
>              validateToken(token);
이것도 정말 좋은데 이렇게 되면 토큰이 필요없는 전체 목록 조회같은 기능에 유효하지 않은 토큰이 포함된다면 예외가 나지 않을까요? 원래같으면 토큰이 필요없는 비회원도 목록을 볼 수 있을텐데..!

2022-07-28 02:47 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/review/domain/Review.java
>      private Member member;
어 이거 병합하고 수정하자고 합의된거 아니었나욤..?

2022-07-28 02:59 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/review/service/ReviewService.java
> +    }
조금 더 명확하게 수정했습니다

2022-07-28 08:32 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/review/service/ReviewService.java
> +        final Review review = writeReviewRequest.toReview(associatedStudy, member);
new로 할지 toReview로 할지 고민중

2022-07-28 08:32 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/review/service/ReviewService.java
> +        if (!study.isParticipant(participant)) {
isParticipated 로 수정하는게 좋을 것 같음

2022-07-28 08:32 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/acceptance/AcceptanceTest.java
> +    protected void setUp() {
AcceptanceTest의 setUp()을 setRestAssuredPort() 로 바꿔주는 게 좋을듯
(BeforeEach의 순서를 정할 수 있는지 알아보기)

2022-07-28 08:32 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/acceptance/review/ReviewAcceptanceTest.java
> +                new GithubProfileResponse(2L, "jjanga", "https://image", "github.com"));
jjanga버리기

2022-07-28 08:32 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/moamoa/review/webmvc/BadRequestReviewWebMvcTest.java
> +    @DisplayName("필수 데이터인 후기 내용이 비어있는 경우 400을 반환한다.")
설명을 공백과 null로 구분하는게 좋을듯

2022-07-29 00:56 UTC, tco0427 approved these changes
추가적인 피드백 반영까지 고생하셨습니다!!
Approve 해도 될 것 같습니다!👍

2022-07-29 02:47 UTC, jaejae-yoo approved these changes

2022-07-29 02:47 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/member/service/MemberService.java
> +                .orElseThrow(MemberNotFoundException::new);
명확해서 좋아요 👍

2022-07-29 02:47 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/ParticipantsTest.java
> +}
EOF만 확인 부탁드려요 ~

2022-07-29 06:07 UTC, wilgur513 approved these changes

2022-07-29 06:55 UTC, merged