[BE] issue164: 스터디 가득차면 CLOSE 및 날짜 리팩토링
woowacourse-teams/2022-moamoa pull request #165
Opened 2022-07-29 07:45 UTC by tco0427

## 요약

스터디 가득차면 CLOSE 및 날짜 리팩토링

## 세부사항

- 스터디 인원이 가득차면 CLOSE
- createdDate 제외하고 스터디 날짜만 (시간 없이) 나오도록 수정

close #164

2022-08-01 05:22 UTC, sc0116 reviewed
생성일자와 수정일자를 Auditing 했네요! 고생많았어요 몇가지 코멘트 달았습니다!

2022-08-01 05:22 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/acceptance/study/GettingMyStudiesAcceptanceTest.java
> +    void mentgetMyStudies() {
ment를 추가한 이유가 있을까요

2022-08-01 05:22 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/acceptance/study/GettingStudyDetailsAcceptanceTest.java
> +    public void mentgetStudyDetails() {
여기도 ment가 붙어있네요!

2022-08-01 05:22 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/acceptance/study/SearchingStudiesAcceptanceTest.java
> +    public void mentgetStudiesByDefaultPagingInfo() {
여기도ㅠ

2022-08-01 05:22 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/moamoa/study/controller/MyStudyControllerTest.java
> +    void mentgetMyStudies() {
😥

2022-08-01 05:22 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/moamoa/study/controller/StudyControllerTest.java
> +    void checkStudyStatusIfcreatedDateeSameStartDate() {
오타가 있네요!

2022-08-01 05:22 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/moamoa/study/query/StudyDetailsDaoTest.java
> +    void mentgetNotHasMaxMemberCountStudyDetails() {
😂

2022-08-01 05:22 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/moamoa/tag/query/TagDaoTest.java
> +    void mentfindAllByNameContainingIgnoreCase() {
ㅜ

2022-08-01 05:22 UTC, sc0116 commented on backend/src/test/resources/schema.sql
> +    excerpt VARCHAR(50) NOT NULL,
굿굿

2022-08-01 05:22 UTC, sc0116 commented on backend/src/test/resources/schema.sql
> +    end_date DATE,
바꿔주셨네요!

2022-08-01 05:22 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Participants.java
> +    private void closeRecruitStatus() {
이름만 보면 무조건 닫아야 할 것 같은데, 클로즈가 가능한지 확인하는 메소드를 만들어서 활용하는 대신 이렇게 한 이유가 있을까요??

2022-08-01 05:22 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Participants.java
> +    private void closeRecruitStatus() {
밑에 isCloseStatus()로 확인한 후 닫는게 어떨까요!

2022-08-01 05:47 UTC, tco0427 reviewed
짱구 피드백 반영해보았습니다!!
꼼꼼히 봐주셔서 감사합니다!!👍

2022-08-01 05:47 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Participants.java
> +    private void closeRecruitStatus() {
아! `isCloseStatus()` 는 "이미" 닫혀있는지를 확인하는 로직이구, 해당 로직은 인원이 가득차면 닫아주는 로직입니다..!!
메소드 명이 불문명해서 해석이 깔끔하지 못했던 것 같습니다!!
`closeRecruitStatusWhenMax` 는 너무 긴 것 같기도 한데..🤔 고민해보도록 하겠습니다!

2022-08-01 05:47 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/study/GettingMyStudiesAcceptanceTest.java
> +    void mentgetMyStudies() {
replaceAll 로 수정하면서 잘못 수정된 것 같네요..😅
수정하도록 하겠습니다!!

2022-08-01 05:47 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/study/GettingStudyDetailsAcceptanceTest.java
> +    public void mentgetStudyDetails() {
수정하겠습니다!! 찾아주셔서 감사해요~_~

2022-08-01 05:47 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/study/SearchingStudiesAcceptanceTest.java
> +    public void mentgetStudiesByDefaultPagingInfo() {
ㅠ.ㅠ 수정하겠습니다!!

2022-08-01 05:47 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/controller/MyStudyControllerTest.java
> +    void mentgetMyStudies() {
🥲

2022-08-01 05:47 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/controller/StudyControllerTest.java
> +    void checkStudyStatusIfcreatedDateeSameStartDate() {
헐랭..엄청 꼼꼼이 봐주셨군요!!
수정하겠습니다!! 감사합니다~_~

2022-08-01 05:47 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/query/StudyDetailsDaoTest.java
> +    void mentgetNotHasMaxMemberCountStudyDetails() {
감사합니다!

2022-08-01 05:47 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/tag/query/TagDaoTest.java
> +    void mentfindAllByNameContainingIgnoreCase() {
일을 두 배로 만들어버렸네요..ㅠ.ㅠ

2022-08-01 06:54 UTC, jaejae-yoo requested changes

2022-08-01 06:54 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/MoamoaApplication.java
> +@EnableJpaAuditing
Application에 선언하지 않고, Config로 분리하는 게 좋을 것 같아요!

2022-08-01 06:54 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/acceptance/study/GettingStudiesSummaryAcceptanceTest.java
> +                .body("studies.recruitmentStatus", contains("RECRUITMENT_START", "RECRUITMENT_START", "RECRUITMENT_START", "RECRUITMENT_START", "RECRUITMENT_START"));
리팩터링 👍

2022-08-01 07:16 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/MoamoaApplication.java
> +@EnableJpaAuditing
어..여기 분리하면 어떤 이점이 있는지 린론의 생각이 궁금해요!! (제가 잘 몰라서..ㅠ.ㅠ)

2022-08-01 07:29 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/MoamoaApplication.java
> +@EnableJpaAuditing
@WebMvcTest를 사용해서 테스트를 하면 JPA와 관련된 빈을 등록하지 않기 때문에,
Application에 @EnableJpaAuditing를 붙이면 슬라이스 테스트 코드에서 문제가 생길 수 있어요!

2022-08-01 07:30 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/MoamoaApplication.java
> +@EnableJpaAuditing
@WebMvcTest를 사용해서 테스트를 하면 JPA와 관련된 빈을 등록하지 않기 때문에,
Application에 @EnableJpaAuditing를 붙이면 슬라이스 테스트 코드에서 문제가 생길 수 있어요! 

https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.testing.spring-boot-applications.user-configuration-and-slicing

2022-08-01 07:33 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/MoamoaApplication.java
> +@EnableJpaAuditing
아하..!! 그래서 제가 [JpaMetamodelMappingContext.class](https://1-7171771.tistory.com/136) 를 `@WebMvcTest` 를 쓰는 곳에 추가해주어야 했군요..!! 수정해보도록 하겠습니다~_~

2022-08-01 07:43 UTC, wilgur513 approved these changes

2022-08-01 09:07 UTC, jaejae-yoo approved these changes

2022-08-02 00:55 UTC, sc0116 approved these changes

2022-08-02 05:35 UTC, merged