[BE] issue162: 스터디 모집 기간 종료 시 자동 모집 종료 설정
woowacourse-teams/2022-moamoa pull request #167
Opened 2022-07-29 14:41 UTC by wilgur513

## 요약

## 세부사항

resolve #162

2022-08-01 06:55 UTC, tco0427 requested changes
베루스 주말동안 고생하셨습니다!!
코드에서 이해를 못한 부분이 있어 따로 설명을 한 번 들어봐야 할 것 같아요ㅜ.ㅜ

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/common/config/SchedulerConfig.java
> +    }
`AllArgs` 써도 되겠네요!

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/common/config/SchedulerConfig.java
> +    }
`AllArgs` 써도 무방하겠네요!1

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/review/domain/Review.java
> +    private Reviewer reviewer;
변경 굿!!

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/review/domain/Review.java
> +    }
직접 Getter를 정의해주신 이유가 궁금합니다!

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/review/domain/Reviewer.java
> +    }
Lombok으로 빼면 더 간결해지겠네요!!

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/review/domain/exception/WritingReviewBadRequestException.java
> +        super("스터디에 후기를 작성할 수 없습니다.");
좀 더 보편적인 예외 메시지로 바꿔주셨군요!!

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/review/service/ReviewService.java
> +    private Long writeReview(final Study study, final Member member, final String content) {
엄청 간단한 로직이라 분리하기 보다는 `writeReview` 에 포함시키는게 로직을 이해하기 좋을 것 같습니다!

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/StudyService.java
> +    }
`RequiredArgs` 대신 직접 정의해주신 이유가 궁금합니다!

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/common/config/SchedulerConfig.java
> +    }
Scheduled 된 Task를 등록하는 걸로 이해하면 될까요??

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/batch/AutoCloseEnrollmentTask.java
> +        super(runnable(studyService), new CronTrigger("@daily", ZoneId.of("Asia/Seoul")));
"Asia/Seoul" 기준으로 `@daily` (하루 단위로) 돌아간다 라고 이해하면 될까요??

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/RecruitStatus.java
> +    OPEN, CLOSE
여기는 제꺼 병합하면서 수정하면 될 것 같습니다!

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Participants.java
> +        return participants.contains(new Participant(memberId)) || ownerId.equals(memberId);
훨신 나은 네이밍이네요!👍

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Participants.java
> +        }
이전 회의에서 처럼 예외를 각 `Embedded` 에서 처리하도록 수정한 걸로 이해하면 될까요??

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/RecruitPlanner.java
> +public class RecruitPlanner {
음..🤔
`참여 가능 조건들` 이 모여있는 Embeddable 객체인 것 같아요..!!
그런데 `Planner` 계획서(?) 라는 말이 조금 어색하게 느껴지네요..조금 더 좋은 네이밍을 같이 고민해봐요!

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/StudyPlanner.java
> +public class StudyPlanner {
아하 `StudyPlanner` 라는 네이밍을 보니 `RecruitPlanner` 라는 네이밍이 조금 납득이 되네요..!!
`스터디 계획서` 와 `모집 계획서`

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/DateTimeSystem.java
> +    }
빈번한 호출때문에 빈으로 등록해주신걸까요??
now 가 static 메소드라 `DateTimeSystem` 이라는 별도의 객체를 만든 이유가 궁금해요!

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/batch/AutoCloseEnrollmentTask.java
> +            }
`autoCloseStudies` 에 `@Transactional` 이 붙어있는데 여기서도 별도로 해주어야 정상처리가 되는 걸까요?? (잘 몰라서...)

2022-08-01 06:55 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/StudyService.java
> +    public void autoCloseStudies() {
여기에 `@Scheduled(cron = "0 0 00 ** ?")` 이렇게 붙여주는 것과는 어떤차이가 있는지 궁금합니다!

2022-08-01 06:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/batch/AutoCloseEnrollmentTaskTest.java
> +class AutoCloseEnrollmentTaskTest {
여기는 설명을 따로 들어야 될 것 같네요..ㅠㅠ
이해가 어렵습니다..ㅠㅠ

2022-08-01 06:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/webmvc/UnauthorizedMyStudyControllerTest.java
> -
저번에 이야기 한 것 처럼 given 절이 필요가 없어서 지운거군요!👍

2022-08-01 07:10 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/common/config/SchedulerConfig.java
> +            taskRegistrar.addTriggerTask(task);
TriggerTask를 상속한 클래스들을 등록해주는 것인가요 ??

2022-08-01 07:44 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/review/domain/Review.java
> +    }
롬복은 어디서 쓰는지 알수가 없어요...
직접 getter가 있으면 intellij에서 어디서 사용되는지 추적해줘서 쉽게 리팩토링 할 수 있어요.

2022-08-01 07:45 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/StudyService.java
> +    }
intellij에서 리팩터링 편의를 위해서 추가했습니다.

2022-08-01 07:45 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/common/config/SchedulerConfig.java
> +    }
맞아요!

2022-08-01 07:46 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/study/batch/AutoCloseEnrollmentTask.java
> +        super(runnable(studyService), new CronTrigger("@daily", ZoneId.of("Asia/Seoul")));
맞습니다.

2022-08-01 07:46 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Participants.java
> +        }
맞아요

2022-08-01 07:48 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/DateTimeSystem.java
> +    }
테스트 초반에 픽스처 생성 시 현재 시간이 아니라 과거에 열린 스터디를 만들 필요가 있더라구요.
그래서 현재 시간을 반환하는 협력 객체를 만들어 주입하면 픽스처 생성 시 과거에 열린 스터디를 만들 수 있었습니다.

2022-08-01 07:49 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/study/batch/AutoCloseEnrollmentTask.java
> +            }
저도 기억이 가물가물해서 그냥 붙여뒀습니다.

2022-08-01 07:50 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/StudyService.java
> +    public void autoCloseStudies() {
한번 확인해볼께요

2022-08-01 07:50 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/common/config/SchedulerConfig.java
> +            taskRegistrar.addTriggerTask(task);
맞습니다

2022-08-01 07:53 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/review/domain/Reviewer.java
> +    }
intellij에서 리팩터링 편의성을 위해서 남겨두는게 더 좋을 것 같아요

2022-08-01 08:39 UTC, jaejae-yoo approved these changes

2022-08-01 08:39 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/moamoa/study/batch/AutoCloseEnrollmentTaskTest.java
> +        assertThat(javaStudy.isCloseEnrollment()).isEqualTo(true);
👍 테스트 너무 좋은 방법이네요

2022-08-02 00:56 UTC, sc0116 approved these changes

2022-08-02 09:13 UTC, merged