[BE] issue168: 사용자 인증 요청 핸들링
woowacourse-teams/2022-moamoa pull request #176
Opened 2022-07-30 12:12 UTC by jaejae-yoo

## 요약
사용자 인증이 필요한 요청들을 핸들링한다.

## 세부사항

close #168

2022-07-31 03:08 UTC, tco0427 approved these changes
아직은 PATH가 추가될 때 마다 이렇게 추가하는식으로하는 방법밖에는 없겠네요..!!
이전보다는 훨씬 깔끔한 느낌입니다! 고생하셨습니다👍

2022-07-31 07:53 UTC, tco0427 requested changes

2022-07-31 07:53 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/AuthenticationInterceptor.java
> +                .build();;
땀 두 개!!

2022-08-01 06:06 UTC, sc0116 reviewed
이전에 인터셉터에서 if로 확인할 때보다 더 깔끔해졌네요 몇가지 코멘트 남겼습니다!

2022-08-01 06:06 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/matcher/AuthenticationRequest.java
> +                && (path.equals(request.getServletPath()) || pattern.matcher(request.getServletPath()).matches());
`pattern.matcher(request.getServletPath()).matches()`로도 충분히 url 확인할 수 있다고 생각하는데 그럼에도 `path.equals(request.getServletPath()`를 추가하신 이유가 있을까요?

2022-08-01 06:24 UTC, tco0427 requested changes
구현 하시느라 고생하셨습니다!!👍
몇가지 사소한 부분 코멘트 달아보았어요~_~

2022-08-01 06:24 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/AuthenticationInterceptor.java
> +@AllArgsConstructor
어 여기서 기존의 `@RequiredArgsConstructor` 로도 의존성 주입이 될 것 같은데, `AllArgs` 로 변경한 이유가 있을까요??
개인적인 거긴 한데, 저는 Required를 통해서 final 필드들이 의존성 주입을 받고 있구나 생각을 해서 Required가 좀 더 명시적인 느낌인 것 같아요!! 린론의 생각을 공유해주세요~_~

2022-08-01 06:24 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/AuthenticationInterceptor.java
> +        if (authenticationRequestMatcher.isRequiredAuth(request)) {
분리하니까 기존보다 훨씬 깔끔하네요!👍

2022-08-01 06:24 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/matcher/AuthenticationRequest.java
> +    }
`AllArgs` 어때요??ㅇㅅㅇ

2022-08-01 06:24 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/matcher/AuthenticationRequest.java
> +                && (path.equals(request.getServletPath()) || pattern.matcher(request.getServletPath()).matches());
오..굿굿..!!

2022-08-01 06:24 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/matcher/AuthenticationRequestMatcher.java
> +                        .map(path -> new AuthenticationRequest(method, path)))
여기만 들여쓰여있어요!!

2022-08-01 06:24 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/matcher/AuthenticationRequestMatcherBuilder.java
> +
여기 공백이 두 칸이에요!!

2022-08-01 06:24 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/auth/controller/matcher/AuthenticationRequestMatcherTest.java
> +            "POST,/api/studies", "POST,/api/studies/1/reviews", "GET,/api/my/studies"
여기 콤마 space 한 칸 띄워주면 좋을 것 같아요!!

2022-08-01 07:26 UTC, wilgur513 approved these changes

2022-08-01 07:26 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/auth/config/AuthRequestMatchConfig.java
> +                .setUpAuthenticationPath(HttpMethod.GET, "/api/my/studies")
setUp보다는 add가 좀 더 의미가 좋을 것 같아요

2022-08-01 07:42 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/auth/config/AuthConfig.java
> +
https://naver.github.io/hackday-conventions-java/#import-grouping

import가 많아지면서, 어떤걸 임포트하는지 한 눈에 파악하기가 어려운 것 같아서 이번 구현에서 그룹을 한번 지어보았어요!

2022-08-01 07:46 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/AuthenticationInterceptor.java
> +@AllArgsConstructor
리팩터링 과정에서 고민이 있어서 @RequiredArgsConstructor를 없앴다가 다시 생성하였는데, 모든 필드를 받는 생성자 생성을 원해서 해당 애노테이션으로 했습니다! 
물론 현재 클래스에서는 모두 final이라 둘이 같겠네요!

2022-08-01 08:04 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/matcher/AuthenticationRequest.java
> +                && (path.equals(request.getServletPath()) || pattern.matcher(request.getServletPath()).matches());
equals 제거했습니다! 👍

2022-08-01 08:16 UTC, tco0427 approved these changes
잘 반영해주셨습니다! Approve 할게요~_~

2022-08-02 00:56 UTC, sc0116 approved these changes

2022-08-02 02:00 UTC, merged