[BE] issue163: 스터디 목록 조회 시 태그 추가
woowacourse-teams/2022-moamoa pull request #177
Opened 2022-07-30 16:03 UTC by sc0116

## 요약

스터디 목록 조회 시 태그 추가

## 세부사항

- 스터디 목록을 조회할 때 해당 스터디의 태그도 함께 조회할 수 있도록 변경한다.

close #163

2022-08-01 05:30 UTC, tco0427 requested changes
짱구 주말에도 열심히 구현해주셨네요!! 고생하셨습니다~_~
몇가지 코멘트 달아보았습니다!

2022-08-01 05:30 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/query/StudySummaryDao.java
> +                + "WHERE s.id IN (:ids)";
이거 그 때 `t` 대신 `tag` 처럼 풀네임으로 가기로 정해서 기존 sql은 변경하지 않더라도 추가되는 부분은 풀네임으로 해주시면 다음 사람이 보게 될 때 편할 것 같습니다!!

2022-08-01 05:30 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/query/StudySummaryDao.java
> +            result.get(studyId).add(tagSummaryData);
여기 분리해주면 조금 더 읽기 편할 것 같습니다!!

2022-08-01 05:30 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/query/StudySummaryDao.java
> +    };
이렇게 긴 경우, 기존에서 처럼 별도의 메소드로 표현하는게 어떨까요??
더 읽기 편할 것 같습니다!!

2022-08-01 05:30 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/study/GettingStudiesSummaryAcceptanceTest.java
> +    private Long linuxStudyId;
Long 굿!

2022-08-01 05:30 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/study/GettingStudiesSummaryAcceptanceTest.java
> +        javaStudyId = createStudy(token, javaRequest);
형변환 필요가 없네요!! 👍👍

2022-08-01 05:30 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/study/GettingStudiesSummaryAcceptanceTest.java
> +        reactTag = new TagSummaryData(5L, "React");
네이밍 좋타..😁

2022-08-01 05:30 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/study/GettingStudiesSummaryAcceptanceTest.java
> +                .extract().as(StudiesResponse.class);
`.as()` 배워갑니다~😃

2022-08-01 05:30 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/query/StudySummaryDaoTest.java
> +    public static Stream<Arguments> provideStudyTags() {
private 접근제어자도 괜찮을 것 같습니다!!

2022-08-01 06:07 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/acceptance/study/GettingStudiesSummaryAcceptanceTest.java
> +        javaStudyId = createStudy(token, javaRequest);
네 그렇더라구요!

2022-08-01 06:08 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/study/query/StudySummaryDao.java
> +                + "WHERE s.id IN (:ids)";
아 그러네요 별칭 사용하지 않고 풀네임으로 수정하겠습니다!

2022-08-01 06:18 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/moamoa/study/query/StudySummaryDaoTest.java
> +    public static Stream<Arguments> provideStudyTags() {
여기서만 쓰니 private으로 바꿔놓겠습니다!

2022-08-01 06:26 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/study/query/StudySummaryDao.java
> +            result.get(studyId).add(tagSummaryData);
`result.get(studyId)`가 `List<TagSummaryData>`를 반환하는 부분이 명확하지 않다는 의미인가요?? 
변수로 뽑아서 조금 더 읽기 편하도록 수정했습니다~!

2022-08-01 06:49 UTC, jaejae-yoo requested changes

2022-08-01 06:49 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/moamoa/study/query/StudySummaryDaoTest.java
> +    private static Stream<Arguments> provideStudyTags() {
👍

2022-08-01 06:49 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/study/query/StudySummaryDao.java
> +        for (int idx = 0; idx < rs.getRow(); idx++) {
`while(rs.next())`로 리팩터링하셔도 좋을 것 같아요!

2022-08-01 06:54 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/study/query/StudySummaryDao.java
> +        for (int idx = 0; idx < rs.getRow(); idx++) {
그렇게 하면 더 가독성도 좋아지고 깔끔해지네요! 😊

2022-08-01 07:40 UTC, wilgur513 requested changes

2022-08-01 07:40 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/study/query/StudySummaryDao.java
> +                .collect(Collectors.toList());
아마 toString으로 변환하지 않아도 됩니다.

2022-08-01 07:40 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/study/query/StudySummaryDao.java
> +    public Map<Long, List<TagSummaryData>> findStudyWithTags(final List<Long> studyIds) {
TagSummaryData 리스트를 반환하는데 StudySummaryData를 담지 않기 때문에 findStudyWithTags는 어울리지 않는 메서드 이름 같아요.

2022-08-01 07:40 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/acceptance/study/GettingStudiesSummaryAcceptanceTest.java
> +                () -> assertThat(studyTags.get(2)).contains(fourTag, beTag)
contains보다 containsExactly나 containsExactlyInAnyOrder와 같은 걸로 좀 더 정확히 확인할 필요가 있어 보여요

2022-08-01 07:40 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/acceptance/study/GettingStudiesSummaryAcceptanceTest.java
> +                        List.of(javaTag, fourTag, beTag), List.of(fourTag, feTag, reactTag))
특정 스터디에 정확히 해당 태그가 있는지를 확인할 필요가 있어 보여요
javaStudy에 붙은게 아니라 reactStudy에 붙어 있어도 통과할 껄로 보입니다.

2022-08-01 07:40 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/study/query/StudySummaryDaoTest.java
> +                "INSERT INTO study(id, title, excerpt, thumbnail, recruit_status, study_status, description, current_member_count, created_at, owner_id, start_date, enrollment_end_date, end_date) VAL
sql이 아니라 repository같은걸로 데이터를 저장하는게 이제는 더 좋아 보입니다.

2022-08-01 07:44 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/study/query/StudySummaryDao.java
> +    public Map<Long, List<TagSummaryData>> findStudyWithTags(final List<Long> studyIds) {
좀더 의미있는 이름으로 수정함과 동시에 TagDao로 이동했습니다!

2022-08-01 09:09 UTC, jaejae-yoo approved these changes

2022-08-02 00:16 UTC, tco0427 approved these changes

2022-08-02 02:02 UTC, wilgur513 approved these changes

2022-08-02 05:09 UTC, merged