[BE] issue119: 내가 참여한 스터디 목록 조회 리팩터링
woowacourse-teams/2022-moamoa pull request #180
Opened 2022-08-01 06:24 UTC by jaejae-yoo

## 요약
내가 참여한 스터디 목록 기능을 리팩터링 및 누락된 요구사항을 추가한다.

## 세부사항
- 내가 참여한 스터디 목록에 자신이 개설한 스터디도 추가한다.
- 내가 참여한 스터디 목록 조회 로직을 리팩터링한다. 

close #119

2022-08-01 07:56 UTC, tco0427 approved these changes
오류 잡아주시느라 고생하셨습니다!
Approve 해도 될 것 같아요~_~

2022-08-01 07:56 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/query/MyStudyDao.java
> +    private static final ResultSetExtractor<Map<Long, StudyOwnerWithTagsData>> OWNER_WITH_TAG_ROW_MAPPER = rs -> {
기존의 RowMapper 를 쓰면 첫번째 row 가 `while (rs.next)` 시 누락되어 `ResultSetExtractor` 로 변경해주셨군요..!!
굿굿👍

2022-08-01 07:56 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/query/MyStudyDao.java
> +        String sql = "SELECT DISTINCT study.id, study.title, study.study_status, study.current_member_count, "
`DISTINCT` 처리 좋네요!

2022-08-01 07:56 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/query/MyStudyDao.java
> +    public Map<Long, StudyOwnerWithTagsData> findStudyOwnerWithTags(List<Long> studyIds) {
이렇게 묶어준 게 훨씬 가독성 있는 것 같습니다!!

2022-08-01 08:04 UTC, wilgur513 requested changes

2022-08-01 08:04 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/study/query/data/StudyOwnerWithTagsData.java
> +public class StudyOwnerWithTagsData {
With보다 And가 더 좋아 보여요

2022-08-02 06:53 UTC, wilgur513 approved these changes

2022-08-02 11:16 UTC, merged