[FE] issue137: 리뷰 작성 페이지 생성
woowacourse-teams/2022-moamoa pull request #184
Opened 2022-08-01 13:35 UTC by airman5573

## 요약
- 리뷰 작성 페이지를 생성했습니다
- StudyRoom에 리뷰 작성 페이지(TabPanel)을 붙였습니다
- 리뷰 작성 / 수정 / 삭제 기능을 구현했습니다. 다만, Backend API가 아직 없는 관계로 정상 작동하지는 않습니다.

close #137

2022-08-02 06:29 UTC, nan-noo requested changes

2022-08-02 06:29 UTC, nan-noo commented on frontend/src/custom-types/index.ts
> +export type CategoryId = number;
👍

2022-08-02 06:29 UTC, nan-noo commented on frontend/src/mocks/handlers.ts
> -  ...tokenHandlers,
이거 지우면 로그인 모킹서버가 안 돼요!

2022-08-02 06:29 UTC, nan-noo commented on frontend/src/mocks/tokenHandlers.ts
> -];
복구해주세요!!

2022-08-02 06:29 UTC, nan-noo commented on frontend/src/custom-types/index.ts
> +export type DateYMD = `${YYYY}-${MM}-${DD}`;
👀 👍

2022-08-02 06:29 UTC, nan-noo commented on frontend/src/mocks/reviewHandler.ts
> +          totalResults: reviewJSON.reviews.length,
이거 totalResults -> totalCount로 바꿔주세요!

2022-08-03 05:57 UTC, airman5573 commented on frontend/src/pages/study-room-page/StudyRoomPage.tsx
> +    { id: 'review', name: '후기', content: <ReviewTabPanel studyId={parseInt(studyId, 10)} /> },
수정했습니다 :D

2022-08-03 06:01 UTC, airman5573 commented on frontend/src/pages/study-room-page/components/review-tab-panel/components/reivew-form/ReviewForm.style.tsx
> +          background-color: transparent;
스타일 린트를 적용하겠습니다!

2022-08-03 06:02 UTC, airman5573 commented on frontend/src/pages/study-room-page/components/review-tab-panel/components/reivew-form/ReviewForm.tsx
> +import useLetterCount from '@components/letter-counter/useLetterCount';
다음 스프린트때 진행하겠습니다 :D

2022-08-03 06:03 UTC, airman5573 commented on frontend/src/pages/study-room-page/components/review-tab-panel/ReviewTabPanel.tsx
> +  const renderReviewList = () => {
회의결과 : 인정하기로 했습니다

2022-08-03 06:04 UTC, airman5573 commented on frontend/src/pages/study-room-page/components/review-tab-panel/components/reivew-form/ReviewForm.tsx
> +  };
다음 스프린트때 하겠습니다 :D

2022-08-03 06:04 UTC, airman5573 commented on frontend/src/pages/study-room-page/components/review-tab-panel/components/review-comment/ReviewComment.style.tsx
> +    row-gap: 8px;
스타일 린트를 적용하겠습니다 :D

2022-08-03 06:04 UTC, airman5573 commented on frontend/src/pages/study-room-page/components/review-tab-panel/components/review-comment/ReviewComment.tsx
> +              </S.DropDownMenu>
네, 알겠습니다. 다음 스프린트때 적용하겠습니다 :D

2022-08-03 06:05 UTC, airman5573 commented on frontend/src/pages/study-room-page/components/review-tab-panel/components/review-comment/useReviewComment.ts
> +  }, [isOpen, handleDropDownClick]);
회의 필요

2022-08-03 06:08 UTC, airman5573 commented on frontend/src/mocks/handlers.ts
> -  ...tokenHandlers,
복구했습니다!

2022-08-03 06:08 UTC, airman5573 commented on frontend/src/mocks/tokenHandlers.ts
> -];
네!

2022-08-03 06:11 UTC, nan-noo approved these changes

2022-08-03 06:11 UTC, merged