[BE] issue196: 토큰을 이용한 현재 사용자 조회
woowacourse-teams/2022-moamoa pull request #200
Opened 2022-08-03 09:26 UTC by wilgur513

## 요약
토큰을 이용한 현재 사용자 조회

## 세부사항

close #196

2022-08-03 23:22 UTC, tco0427 requested changes
베루스! 구현 고생하셨습니다~_~
몇가지 사소한 코멘트와 궁금한 점 남겼습니다!

2022-08-03 23:22 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/member/query/MemberDao.java
> +        return Optional.empty();
음..List를 받아와서 사이즈를 비교하고 0번째 인덱스를 반환한다는 표현에서는
조회결과가 없으면 Opional.empty() 이고 있으면 Opional로 감싼 값을 반환한다 라는 의미가 불명확한것 같아요..🥲

```java
        try {
            final MemberData data = jdbcTemplate.queryForObject(sql, Map.of("id", githubId), ROW_MAPPER);
            return Optional.of(data);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
```

해당 부분을 위와 같은 코드로 변경해보는 것은 어떨까요?? ㅇㅅㅇ

2022-08-03 23:22 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/member/service/MemberService.java
> +        memberRepository.save(member);
람다에서 위와같이 변경한 이유는 가독성 측면에서 일까요?? 어떤이유에서인지 궁금합니다!!

2022-08-03 23:22 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/docs/AuthDocumentationTest.java
> +package com.woowacourse.docs;
패키지 분리 좋네요!

2022-08-03 23:22 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/member/controller/MemberControllerTest.java
> +    void findNotFoundGithubIdMember() {
`@DisplayName` 으로 GithubId로 찾지 못했을 때에 대한 상황을 명시해주면 좋을 것 같아요!!

2022-08-03 23:22 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/member/webmvc/MemberWebMvcTest.java
> +    void notFound() throws Exception {
엇..여기도 조회가 안되었을 경우에는 `@DisplayName` 이 누락되어있네요..
혹시 의도해주신걸까요..??🤔

2022-08-04 00:38 UTC, sc0116 reviewed
베루스!!! 고생하셨슴당😛 궁금한점 몇가지 남겨봤어요!

2022-08-04 00:38 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/member/query/MemberDao.java
> +        final List<MemberData> data = jdbcTemplate.query(sql, Map.of("id", githubId), ROW_MAPPER);
앗 혹시 queryForObject 대신에 query 쓴 이유가 있을까요??
query는 리스트로 나오는데 githubId로 찾는 멤버는 한명만 나오니까 queryForObject로 받는게 더 편하지 않나요?

2022-08-04 00:38 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/member/service/MemberService.java
> +        if (foundMember.isPresent()) {
저도 기존 코드가 너무 익숙해져서 그런지 변경한 이유가 궁금하네요!

2022-08-04 00:38 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/docs/AuthDocumentationTest.java
> +package com.woowacourse.docs;
헉 저도 이렇게 할까 했는데 굳굳!!!

2022-08-04 05:26 UTC, jaejae-yoo approved these changes

2022-08-04 05:26 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/acceptance/member/MemberAcceptanceTest.java
> +                .header(HttpHeaders.AUTHORIZATION, token)
RESR Docs에도 추가하면 좋을 것 같아요 ~

2022-08-04 05:26 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/moamoa/auth/controller/matcher/AuthenticationRequestMatcherTest.java
> +        given(httpServletRequest.getRequestURI())
`getRequestURI()`로 변경한 이유가 궁금해요!

2022-08-04 05:26 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/docs/DocumentationTest.java
> +@ContextConfiguration(classes = {MoamoaApplication.class})
해당 설정이 왜 추가됐는지 궁금해요!

2022-08-04 05:26 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/auth/config/AuthRequestMatchConfig.java
> +                .addUpAuthenticationPath(HttpMethod.GET, "/api/my/studies", "/api/members/me")
👍

2022-08-04 07:36 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/member/service/MemberService.java
> +        memberRepository.save(member);
가독성이 저게 더 좋아 보여서요 ㅎㅎ

2022-08-04 13:51 UTC, merged