[BE] issue223: 테스트 코드 최적화
woowacourse-teams/2022-moamoa pull request #224
Opened 2022-08-06 15:31 UTC by jaejae-yoo

## 요약
- 테스트 환경 통일
- 테스트 코드 시간 단축

close #223

2022-08-08 07:55 UTC, tco0427 approved these changes
테스트 코드 최적화👍
생각하지도 못하고 있었는데, 감사합니다!!

궁금한 점 몇가지 코멘트 남겼습니다~_~

2022-08-08 07:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/AcceptanceTest.java
> +        jdbcTemplate.update("SET REFERENTIAL_INTEGRITY TRUE");
오호! 여기가 최적화의 핵심인 것 같은데요!!
DELETE 와 TRUNCATE 동작에 어떤 차이가 있는지 궁금합니다!!

2022-08-08 07:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/WebMVCTest.java
> +public abstract class WebMVCTest {
WebMVCTest 로 의존성을 한 곳으로 모아주고 이를 가져다가 쓰는 것으로 이해했는데 맞을까요?

2022-08-08 07:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/auth/controller/AuthControllerTest.java
> +public class AuthControllerTest extends WebMVCTest {
상속만 받으면 끝이라서 코드가 훨씬 깔금해지겠군요!

2022-08-08 07:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/auth/controller/AuthenticationInterceptorTest.java
> +        given(authenticationRequestMatcher.isRequiredAuth(httpServletRequest)).willReturn(true);
Auth(인증) 이 필요한 요청인지를 확인해서 조금 더 정확한 테스트를 하기 위해 추가한 것으로 이해하면 될까요??

2022-08-08 08:45 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/acceptance/AcceptanceTest.java
> +        jdbcTemplate.update("SET REFERENTIAL_INTEGRITY TRUE");
저도 궁금합니다 DELETE와 TRUNCATE의 차이점을요! 만약 그린론이 답변을 해준다면 더할나위 없이 행복할 것 같네요

2022-08-08 08:56 UTC, wilgur513 requested changes

2022-08-08 08:56 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/WebMVCTest.java
> +    protected AuthenticationRequestMatcher authenticationRequestMatcher;
이거 목킹한 이유가 있나요??

2022-08-08 08:56 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/auth/controller/matcher/AuthenticationRequestMatcherTest.java
> +
아래서 목킹한 기능을 테스트하는게 이상합니다...
부모 클래스에서 authentiactionRequestMatcher를 @MockBean으로 만들지 말고 필요한 자식 클래스에서만 목킹하는게 좋을 것 같아요.
지금과 같은 테스트 코드에서는 AuthRequestMatchConfig에서 제공하는 AuthenticationRequestMatcher를 사용해야 할 것 같아요.

2022-08-09 01:36 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/moamoa/auth/controller/matcher/AuthenticationRequestMatcherTest.java
> +
말씀하신 것처럼 테스트하는 대상을 MockBean으로 처리하는 게 어색하네요.
AuthentiactionRequestMatcher는 실제 객체를 사용하고, HttpServletRequest를 모킹해서 주입했습니다!

2022-08-09 01:39 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/moamoa/WebMVCTest.java
> +public abstract class WebMVCTest {
네, 테스트에서 `스프링 컨테이너를 재사용`하기 위함입니다!

2022-08-09 01:43 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/moamoa/auth/controller/AuthenticationInterceptorTest.java
> +        given(authenticationRequestMatcher.isRequiredAuth(httpServletRequest)).willReturn(true);
네, 그런데 AuthenticationRequestMatcher의 목빈을 제거하면서 해당 로직도 제거했습니다!
인증 요청 부분은 AuthenticationRequestMatcherTest에서 처리하고 있습니다.

2022-08-09 01:48 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/acceptance/AcceptanceTest.java
> +        jdbcTemplate.update("SET REFERENTIAL_INTEGRITY TRUE");
`DELETE`는 트랜잭션 로그를 남기기 때문에 롤백할 수 있고, `TRUNCATE`는 로그를 남기지 않아 롤백할 수 없습니다.
현재 테스트에서는 롤백할 상황이 없기 때문에 로그를 남기지 않아 더 빠른 TRUNCATE로 변경했습니다!

2022-08-09 05:06 UTC, wilgur513 approved these changes

2022-08-09 05:14 UTC, merged