[BE] issue229: Refresh Token 적용하기
woowacourse-teams/2022-moamoa pull request #236
Opened 2022-08-09 15:17 UTC by tco0427

## 요약

Refresh Token을 적용한다.

### 적용이유

현재 Access Token 만을 사용하는데, JWT의 Stateless한 방식의 단점을 개선하기 위해서 Refresh Token을 도입한다.
(Access Token의 노출시간을 줄이고, Refresh Token을 이용하여 사용자가 매번 로그인하는 불편함을 해소한다.)

[JWT에서 Refresh Token은 왜 필요한가?](https://velog.io/@park2348190/JWT%EC%97%90%EC%84%9C-Refresh-Token%EC%9D%80-%EC%99%9C-%ED%95%84%EC%9A%94%ED%95%9C%EA%B0%80)

## 세부사항

- Refresh Token 이용한 동작과정
  - accessToken이 만료되었다는 응답이 왔을 때 refreshToken과 함께 accessToken을 발급 요청한다
  - 새로운 accessToken을 발급받으면 accessToken을 클라이언트에 저장하고, 기존에 요청했던 리소스를 다시 fetch
  - refreshToken도 만료되었다는 응답이 오면 저장되어 있는 accessToken을 제거하고 로그아웃

- [x] Token 발급 시 Refresh Token을 함께 Client에 전달한다.
- [x] "/api/auth/refresh" 요청이 오면 Refresh Token을 검사하고 Access Token을 재발급한다.
- [ ] Refresh Token은 헤더에 포함해서 Client 측으로 전달한다.
- [ ] Refresh Token을 이용해 Access Token을 재발급할 때 쿠키의 내용을 통해서 확인한다.
- [ ] Refresh Token은 서버측 DB에 저장한다.

close #229

2022-08-11 02:28 UTC, sc0116 reviewed
디우 리프레시토큰 코드보면서 학습했어요! 몇 가지 코멘트 달아놨습니다

2022-08-11 02:28 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/AuthController.java
> +        return ResponseCookie.from(REFRESH_TOKEN, null)
로그아웃할 때 쿠키에 있는 리프레시 토큰에 null을 넣는군요!

2022-08-11 02:28 UTC, sc0116 commented on backend/src/main/resources/application.yml
> +    url: jdbc:h2:mem:~/moamoa;MODE=MYSQL
앗 main yml에 이렇게 바꿔놓으면 ec2에서 못받아오지 않나요?

2022-08-11 04:10 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/domain/Token.java
> +        this.refreshToken = refreshToken;
오오..!! 좋네요!

2022-08-11 04:10 UTC, tco0427 commented on backend/src/main/resources/application.yml
> +    url: jdbc:h2:mem:~/moamoa;MODE=MYSQL
앗..!! 수정해놓겠습니다!!

2022-08-11 07:59 UTC, sc0116 approved these changes

2022-08-11 23:32 UTC, jaejae-yoo requested changes
디우 구현하느라 고생하셨습니다! 👍
궁금한 점과 리뷰 확인 부탁드려요 ~

2022-08-11 23:32 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/auth/infrastructure/JwtTokenProvider.java
> +    public long getValidityInMilliseconds() {
`@Override` 선언이 있어야 할 것 같아요 ~

2022-08-11 23:32 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/auth/service/AuthService.java
> +        final Optional<Token> token = tokenRepository.findByGithubId(githubId);
```
final Token token = tokenRepository.findByGithubId(githubId)
                .orElseThrow(TokenNotFoundException::new);
```
로 바꾸는 것은 어떨까요 ?? 
예외를 던지지 않으면 잘못된 githubId여도 밑에서 토큰을 생성할 것 같아서요!

```
final TokenResponseWithRefresh tokenResponse = tokenProvider.createToken(githubProfileResponse.getGithubId());
```

2022-08-11 23:32 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/auth/service/AuthService.java
> +    public void logout(final Long githubId) {
`@Transactional`을 붙여야 할 것 같아요!

2022-08-11 23:32 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/common/advice/CommonControllerAdvice.java
> +        return ResponseEntity.status(INTERNAL_SERVER_ERROR).body(new ErrorResponse(e.getMessage(), 4001));
`4001` 상태 코드가 리프레시 토큰 만료 에러이군요!

2022-08-11 23:32 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/acceptance/test/auth/AuthAcceptanceTest.java
> +        final String token = getBearerTokenBySignInOrUp(new GithubProfileResponse(4L, "verus", "https://image", "github.com"));
반환값 이번 구현에서 `TokenResponse`로 변경되지 않았나요 ?

2022-08-11 23:32 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/moamoa/auth/service/AuthServiceTest.java
> +@SpringBootTest
테스트 비용때문에 사용했던 `@RepositoryTest`를 사용하지 않은 이유가 궁금해요!

2022-08-11 23:32 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/moamoa/auth/service/AuthServiceTest.java
> +        Mockito.when(oAuthClient.getProfile("accessToken"))
```
Mockito.when(oAuthClient.getAccessToken("authorization-code")).thenReturn("access-token");
Mockito.when(oAuthClient.getAccessToken("authorizationCode")).thenReturn("accessToken");
Mockito.when(oAuthClient.getProfile("access-token"))
                .thenReturn(new GithubProfileResponse(1L, "dwoo", "imageUrl", "profileUrl"));
Mockito.when(oAuthClient.getProfile("accessToken"))
                .thenReturn(new GithubProfileResponse(1L, "dwoo", "imageUrl", "profileUrl"));
```

두 번씩 선언한 이유가 궁금해요!

2022-08-11 23:32 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/AuthController.java
> +    public ResponseEntity<TokenResponse> refreshToken(@AuthenticationPrincipal Long githubId, @CookieValue String refreshToken) {
`@CookieValue` String refreshToken가 null이면 어떻게 처리되는지 궁금합니다! 
해당 부분이 `WebMvcTest`에 있으면 좋을 것 같아요!

2022-08-12 01:05 UTC, tco0427 reviewed
안녕하세요 린론!!
질문 주신 내용에 대해서 코멘트 달고, 피드백 반영해보았습니다~_~
꼼꼼하게 봐주셔서 감사합니다!!

2022-08-12 01:05 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/auth/service/AuthServiceTest.java
> +        Mockito.when(oAuthClient.getProfile("accessToken"))
처음 테스트 작성시에 서로 다른 accessToken과 그에 대한 응답이 필요했다고 생각했던 것 같애요!!
근데 테스트 과정에서 불필요해졌는데 제거하지 못했던 것 같습니다!!

2022-08-12 04:47 UTC, wilgur513 approved these changes

2022-08-12 04:48 UTC, jaejae-yoo approved these changes

2022-08-12 04:49 UTC, merged