[BE] issue227: 스터디원을 위한 링크공유 CRUD
woowacourse-teams/2022-moamoa pull request #237
Opened 2022-08-10 01:38 UTC by sc0116

## 요약

링크공유 CRUD를 한다.

## 세부사항

- C함
- R안함
- U함
- D함

close #227

2022-08-11 08:47 UTC, tco0427 requested changes
API 4개를 한 번에 구현해주시느라 고생많으셨습니다!!
몇가지 코멘트나 간단한 제안사항 남겨보았습니다~_~

2022-08-11 08:47 UTC, tco0427 commented on backend/src/docs/asciidoc/index.adoc
> +
Docs 추가 좋습니다!

2022-08-11 08:47 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/config/AuthRequestMatchConfig.java
> +                        "/api/studies/\\d+/reference-room/links/\\d+")
아마 스터디 커뮤니티쪽도 추가되게 되면 굉장히 많아지겠네요..
슬슬...개선방안을 고민해봐야할 듯 ㅠ.ㅠ

2022-08-11 08:47 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/common/entity/BaseEntity.java
> +    private LocalDate createdDate;
`LocalDateTime` 으로 수정 부탁드립니다!!
밑에 `lastModifiedDate` 도!!

2022-08-11 08:47 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/controller/SearchingReferenceRoomController.java
> +    }
조회랑 명령 분리해준거 좋네요!!👍
defalut size는 5로 프론트와 이야기를 한 건지 궁금합니다!!

2022-08-11 08:47 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/domain/Link.java
> +        validateAuthor(updatedLink.author);
필드로 바로 접근보다 getter 쓰는게 어떨까요??ㅇㅅㅇ
Link 클래스내의 로직이라 접근이 가능한 것 같은데 parameter로 넘어온 객체는 현재 로직이 실행되는 객체랑은 달라서!

2022-08-11 08:47 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/domain/Link.java
> +    }
5개 모두 Getter가 필요하다면 `@Getter` 어노테이션도 괜찮을 것 같아요!! (꼭 반영하지 않으셔도 됩니다~_~)

2022-08-11 08:47 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/domain/repository/LinkRepository.java
> +}
사용하는 메소드만 👍👍

2022-08-11 08:47 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/query/LinkDao.java
> +                + " member.github_id, member.username, member.image_url, member.profile_url "
어 여기 공백 두 칸이네요!!

2022-08-11 08:47 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/query/LinkDao.java
> +    }
굿굿!! 편리함을 느꼈다니 기쁘네요~_~😁

2022-08-11 08:47 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/service/ReferenceRoomService.java
> +        }
꼼꼼한 검증 굿!

2022-08-11 08:47 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/service/ReferenceRoomService.java
> +                .orElseThrow(StudyNotFoundException::new);
orElseThrow() 포함해서 중복이 많네요..ㅠ.ㅠ
혹시 별도의 메소드로 빼서 사용하는 것 어떨까요??

```java
private Member findByGithubId(final Long githubId) {
    return memberRepository.findByGithubId(githubId).orElseThrow(MemberNotFoundException::new);
}
```

개인적인 의견이니 꼭 반영하지 않으셔도 됩니다!!
```

2022-08-11 08:47 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/service/request/CreatingLinkRequest.java
> +    @Size(max = 500, message = "링크 URL은 500자를 초과할 수 없습니다.")
Validation 사용 굿굿!!

2022-08-11 08:47 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Participants.java
> +    public boolean isParticipation(final Long memberId) {
public 으로 열어준 이유가 궁금합니다!!

2022-08-11 08:47 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Participants.java
> +    public boolean isParticipation(final Long memberId) {
밑에 Study에서 필요해졌군요..!!

2022-08-11 08:47 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/AcceptanceTest.java
> +        jdbcTemplate.update("TRUNCATE TABLE link");
👍

2022-08-11 08:47 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/steps/StudyRelatedSteps.java
> +            return -1;
이전 코드 리뷰 때 놓쳤던 것 같은데.. `-1` 반환이 아니라 `Long` 타입 써서 null을 반환해도 괜찮을 수 있겠네요..!!
짱구가 한 번 고민해보고 리팩토링 해봐도 좋을 것 같습니다!!

2022-08-11 08:47 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/test/review/ReviewsAcceptanceTest.java
> +
에러 떠서 수정해주셨군요!!

2022-08-11 08:47 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/referenceroom/controller/ReferenceRoomControllerTest.java
> +public class ReferenceRoomControllerTest {
스터디 엄청 꼼꼼하게 써주셨네요!!👍👍
`혹시 작성할 수 있다 or 없다` 는 도메인에서 검증 가능할 것 같아서 이런 부분들은 도메인 테스트로 내리면 적은 비용으로 원하는 피드백을 받을 수 있을 것 같아요!!

2022-08-11 08:47 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/referenceroom/controller/ReferenceRoomControllerTest.java
> +    }
예를 들어 이부분은 `LinkTest`의 `링크 공유를 수정한다.`에서 검증해주고 있는 것 같아요!!

2022-08-11 08:47 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/referenceroom/webmvc/ReferenceRoomWebMvcTest.java
> +    @DisplayName("링크 공유 설명이 50글자 이상인 경우 400을 반환한다.")
길이까지 크~~
저라면 놓쳤을 테스트였을 것 같네요..🥲

2022-08-12 00:42 UTC, jaejae-yoo requested changes
짱구 구현하느라 고생하셨어요 ~ 
리뷰 확인부탁드려요!

2022-08-12 00:42 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/query/LinkDao.java
> +                + "ORDER BY link.created_date DESC";
`link.id`로 정렬하는 부분도 추가하면 좋을 것 같아요 
시간이 아예 같은 경우 순서가 뒤죽박죽이 되더라고요! 🥲

2022-08-12 00:42 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/service/request/CreatingLinkRequest.java
> +    @Size(max = 25, message = "설명은 50자를 초과할 수 없습니다.")
max는 25자인데, 메시지에는 50자로 되어있어요!

2022-08-12 00:42 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/service/request/EditingLinkRequest.java
> +    @Size(max = 25, message = "설명은 50자를 초과할 수 없습니다.")
여기도 사이즈 확인부탁드려요 ~

2022-08-12 00:42 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/acceptance/test/referenceroom/ReferenceRoomAcceptanceTest.java
> +                        )))
`requestFields`로 링크 url, description도 있으면 좋을 것 같아요 ~

2022-08-12 00:42 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/acceptance/test/referenceroom/ReferenceRoomAcceptanceTest.java
> +                .param("page", 1)
이 부분 확인해 봐야 할 것 같아요.. 
`page가 0,1,2로 바꿔도 사이즈가 모두 5`로 나오고 있어요!

2022-08-12 00:42 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/domain/Link.java
> +        validateBelongToStudy(associatedStudy);
꼼꼼한 검증 👍

2022-08-12 01:28 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/auth/config/AuthRequestMatchConfig.java
> +                        "/api/studies/\\d+/reference-room/links/\\d+")
맞아요 더 많아질텐데 개선해봐야겠어요

2022-08-12 01:31 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/controller/SearchingReferenceRoomController.java
> +    }
디폴트가 9로 바꼈네요 ㅎㅎ

2022-08-12 01:33 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/domain/Link.java
> +    }
`getAuthor()`가 현재는 필요하지 않고, 롬복쓰면 간결해지지만 어디에 쓰는지 모르겠더라구여..!

2022-08-12 01:35 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/query/LinkDao.java
> +                + " member.github_id, member.username, member.image_url, member.profile_url "
헉 그러네요 한 칸으로 줄였습니다

2022-08-12 01:39 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/service/ReferenceRoomService.java
> +                .orElseThrow(StudyNotFoundException::new);
이 부분에 대해서 고민을 해봤는데, 위 코드를 ReferenceRoomService의 메서드로 뽑으면 ReferenceRoomService 내부에선 중복이 사라지지만, 현재 `memberRepository.findByGithubId()`를 거의 모든 Service에서 사용하고 있기 때문에 ReviewService에서도 뽑은 메서드가 있고 ReferenceRoomService에서도 뽑은 메서드가 존재해서 결국은 중복될 것 같더라구요 그래서 그냥 member와 관련있는 MemberService에 메서드로 뽑아두고 MemberService를 불러와서 사용하는게 어떨까 싶은데요 디우는 어떻게 생각하나요

2022-08-12 01:41 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/service/request/CreatingLinkRequest.java
> +    @Size(max = 25, message = "설명은 50자를 초과할 수 없습니다.")
앗 실수했는데 감사합니다~

2022-08-12 01:43 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/query/LinkDao.java
> +                + "ORDER BY link.created_date DESC";
넵 id로 정렬하는 부분 추가하겠습니다!

2022-08-12 01:59 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/service/ReferenceRoomService.java
> +                .orElseThrow(StudyNotFoundException::new);
음..일단 저라면 저는 서비스 -> 서비스 의존할 때 비즈니스 로직이 포함되었을 때 의존을 해야한다고 생각을 하는데, 이 경우에는 그런 case는 아니라서 ReferenceRoomService 내에서 뽑아서 쓸 것 같긴합니다..!!

제 의견을 반영하셔도 되고, 짱구가 원하는 방향으로 리팩토링해주면 될 것 같아요!!

2022-08-12 04:29 UTC, tco0427 approved these changes

2022-08-12 04:29 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/controller/SearchingReferenceRoomController.java
> +            @PageableDefault(size = 9) final Pageable pageable
굿!!

2022-08-12 04:29 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/query/LinkDao.java
> +                + "member.github_id, member.username, member.image_url, member.profile_url "
👍

2022-08-12 04:29 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/service/request/CreatingLinkRequest.java
> +    @Size(max = 25, message = "설명은 25자를 초과할 수 없습니다.")
꼼꼼한 반영 좋습니다~_~

2022-08-12 04:29 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/steps/StudyRelatedSteps.java
> +            return null;
굿굿굿~

2022-08-12 05:03 UTC, jaejae-yoo approved these changes

2022-08-12 05:48 UTC, wilgur513 approved these changes

2022-08-12 05:48 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/service/ReferenceRoomService.java
> +        }
study.isWritable은 리뷰를 쓸 수 있는지 확인할 때 사용하는 메서드인데,
리뷰 작성은 스터디 시작전에 작성할 수 없다는 조건이 있어요.
링크 모음 게시글 작성은 스터디 상태와 상관없기 때문에 다른 메서드를 써야할 것 같아요.
그리고 isWritable보다 isReviewWritable과 같이 리뷰를 작성할 수 있는 지 확인하는 메서드라는 이름을 유지해야 할 것 같아요

2022-08-12 05:48 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/referenceroom/service/ReferenceRoomService.java
> +        link.update(updatedLink);
작성자만 링크를 업데이트할 수 있다는 로직이 들어나지 않아서 이상해요

2022-08-12 06:57 UTC, merged