[BE] issue241: 테스트 코드 리팩토링
woowacourse-teams/2022-moamoa pull request #242
Opened 2022-08-11 01:20 UTC by tco0427

## 요약
테스트코드 JdbcTemplate 제거

## 세부 설명
테스트코드의 JdbcTemplate 을 제거하면서 Fixture 보완

close #241

2022-08-11 05:44 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/fixtures/ReviewFixtures.java
> +    }
굿!!

2022-08-16 01:48 UTC, jaejae-yoo approved these changes

2022-08-16 01:48 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/common/entity/BaseEntity.java
> +    private LocalDate createdDate;
LocalDateTime으로 정했던 거로 기억해요!

2022-08-16 01:48 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/study/service/StudyService.java
> +    private static RecruitPlanner getRecruitPlanner(final CreatingStudyRequest request, final Participants participants) {
static으로 선언하신 이유가 궁금해요 ~

2022-08-16 01:48 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/study/service/StudyService.java
> +        if (request.getMaxMemberCount() != null && participants.getSize() == temporaryRecruitPlanner.getMax()) {
```
private static RecruitPlanner getRecruitPlanner(final CreatingStudyRequest request, final Participants participants) {
        final RecruitPlanner recruitPlanner = request.mapToRecruitPlan();
        if (recruitPlanner.isMemberMax(request.getMaxMemberCount(), participants.getSize())) {
            return new RecruitPlanner(recruitPlanner.getMax(), RECRUITMENT_END, recruitPlanner.getEnrollmentEndDate());
        }
        return recruitPlanner;
}
```
RecruitPlanner 객체에서 검증하는 게 더 좋을 것 같아서 제안해 드려 봅니다 ~

2022-08-16 01:48 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/fixtures/MemberFixtures.java
> +    public static Member 짱구() {
👍

2022-08-16 01:49 UTC, sc0116 approved these changes

2022-08-16 01:52 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/StudyService.java
> +    private static RecruitPlanner getRecruitPlanner(final CreatingStudyRequest request, final Participants participants) {
메소드 분리하면서 static으로 분리된 것 같네요..!!ㅠ.ㅠ Non-static 으로 수정하도록 하겠습니다!

2022-08-16 01:52 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/common/entity/BaseEntity.java
> +    private LocalDate createdDate;
이거 그 때 확정이 안났던 것 같습니다..!! `LocalDateTime` 으로 수정할게요~_~

2022-08-16 02:01 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/StudyService.java
> +        if (request.getMaxMemberCount() != null && participants.getSize() == temporaryRecruitPlanner.getMax()) {
좋은 생각입니다..!!

2022-08-16 03:05 UTC, wilgur513 requested changes

2022-08-16 03:05 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/StudyService.java
> +    }
```java
if (maxMemberCount != null && maxMemberCount == 1) {
    return new RecruitPlanner(maxMemberCount, RecruitStatus.RECRUITMENT_END, enrollmentEndDate);
}
```
이런 식으로 CreatingStudyRequest.mapToRecruitPlan 메서드안에 넣는게 좋아보여요

2022-08-16 03:05 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/fixtures/StudyFixtures.java
> +
```java
public static CreatingStudyRequestBuilder 자바_스터디_신청서(...) {
    ...
}
```
위와 같이 Builder도 픽스처에 넣는게 좋을 것 같아요

2022-08-16 03:10 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/StudyService.java
> +    }
`RecruitPlanner` 도메인의 로직도 제거할 수 있고, Service 쪽 private 메소드도 제거 가능해지네요!

2022-08-16 06:44 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/fixtures/StudyFixtures.java
> +
중복이 많아 말씀하신대로 픽스쳐로 빼도 좋을 것 같네요..!! 수정하겠습니다!

2022-08-16 07:31 UTC, wilgur513 approved these changes

2022-08-16 07:31 UTC, merged