[BE] issue245: 스터디 가입날짜 및 스터디 개수
woowacourse-teams/2022-moamoa pull request #246
Opened 2022-08-12 00:34 UTC by tco0427

## 요약

스터디 가입날짜 및 스터디 개수

## 세부 설명

스터디 가입날짜 및 스터디 개수를 함께 표시한다.

![스크린샷 2022-08-11 오후 8 03 40](https://user-images.githubusercontent.com/57028386/184119764-8d1e4f33-d1d2-4ac0-a733-7d0bd896c324.png)

close #245

2022-08-16 02:11 UTC, sc0116 reviewed
디우 고생하셨습니다. 몇 가지 코멘트 남겨뒀어요!

2022-08-16 02:11 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/member/query/MemberDao.java
>      }
저는 개인적으로 잘 읽히는 것 같아요 저번 회의때 스터디 참여개수를 구하는 부분에 대해 논의했던거 같은데 다른 방법으로 하더라도 이 구조보다 덜 복잡하진 않을 것 같다는 생각이 드네요. (이름때문에 그러는거면 이부분만 그냥 필드명처럼 메서드를 바꿔보는것도... )

2022-08-16 02:11 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Participant.java
> +    private LocalDate participationDate;
참여일자 추가 굿

2022-08-16 02:11 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Study.java
> +@NoArgsConstructor(access = PROTECTED)
순서를 바꾸셨는데 이건 정말 궁금해서 여쭤보는거에요! 혹시 바꾼 이유가 있나요? 중요한 순서라기엔 오름차순이나 내림차순 둘다 Getter가 처음이나 마지막이어야 할 것 같은데 궁금합니다!

2022-08-16 02:11 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/moamoa/study/controller/MyStudyControllerTest.java
어후 노가다 고생하셨네용

2022-08-16 02:11 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/moamoa/study/controller/SearchingStudyControllerTest.java
> +                );
이 부분은 순서가 중요한 부분은 아니라서 containsExactly가 아닌 InAnyOrder를 하신거군요!

2022-08-16 02:11 UTC, sc0116 commented on backend/src/test/resources/schema.sql
> +    participation_date DATE not null,
굿굿

2022-08-16 02:49 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Study.java
> +@NoArgsConstructor(access = PROTECTED)
어.. 이건 아마 구현하는 중에 변경된 것 같습니다..!!

2022-08-16 02:50 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/controller/SearchingStudyControllerTest.java
> +                );
넵..!! 순서까지 고려하려면 너무 initDataBase 에서 순서까지 고려해줘야하고 다른 테스트들에도 영향이 있어서요..!!

2022-08-16 15:39 UTC, jaejae-yoo requested changes

2022-08-16 15:39 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/member/query/MemberDao.java
> +    private String countParticipationStudy() {
이 경우가 countOwnerStudy()일까요? sql문을 보니 헷갈려서 질문드려요~

2022-08-16 23:27 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/response/StudyDetailResponse.java
> +                               final List<MemberFullData> participants,
<img width="664" alt="스크린샷 2022-08-17 08 27 10" src="https://user-images.githubusercontent.com/57028386/185002301-9b488a8f-0ff9-4ac6-9c2c-2b91b0332912.png">

기존의 MemberData 를 제거하면 변경점이 많아져서 (118 곳에서 사용중) 디테일 조회에서만 사용하는 MemberFullData 를 추가하는 방향으로 작업하였습니다..!!

2022-08-16 23:30 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/member/query/MemberDao.java
> +    private String countParticipationStudy() {
이런...가독성 올리기 위해서 메소드 분리하는 과정에서 Paricipant 카운트돠 Owner 카운트가 뒤바뀐 것 같습니다!
린론이 생각한게 맞습니다! (`countParticipantionStudy` 와 `countOwnerStudy` 가 바뀌었네요!)

2022-08-17 06:13 UTC, wilgur513 requested changes

2022-08-17 06:13 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/member/query/data/MemberFullData.java
> +public class MemberFullData {
MemberFullData보다는 다른 이름이 좋아 보입니다. 예를 들어 ParticipantData라든가

2022-08-17 06:33 UTC, jaejae-yoo approved these changes

2022-08-17 07:51 UTC, sc0116 approved these changes

2022-08-17 10:33 UTC, wilgur513 approved these changes

2022-08-17 10:33 UTC, merged