[FE] issue256: atomic css 방식을 css props에 적용하는 유틸 함수 생성
woowacourse-teams/2022-moamoa pull request #259
Opened 2022-08-12 12:55 UTC by airman5573

## 요약
[issue 256](https://github.com/woowacourse-teams/2022-moamoa/issues/256)

close #256

2022-08-12 15:38 UTC, nan-noo requested changes

2022-08-12 15:38 UTC, nan-noo commented on frontend/src/App.tsx
> +import tw from '@utils/tw';
utils/index.ts 파일에 추가해서 import하는 건 어떨까요?

2022-08-12 15:38 UTC, nan-noo commented on frontend/src/App.tsx
> +      <Header css={tw`fixed top-0 left-0 right-0 z-2`} />
👍

2022-08-12 15:38 UTC, nan-noo commented on frontend/src/utils/tw.ts
> +const arr0_to_300 = [...Array(301).keys()];
`Array.from({length: 101}, (_, i) => i);`을 쓰는 것과 어떤 차이가 있나요?

2022-08-13 05:09 UTC, airman5573 commented on frontend/src/App.tsx
> +import tw from '@utils/tw';
intellisense 가 `@utils/tw` 키워드를 인식하도록 설정되어 있어서 이게 필요합니다

2022-08-13 05:20 UTC, airman5573 commented on frontend/src/utils/tw.ts
> +const arr0_to_300 = [...Array(301).keys()];
결과는 같은데 속도 차이가 있네요!

```javascript
let now = performance.now();

for (let i = 0; i < 10000; i += 1) {
  const _ = Array.from({ length: 101 + i }, (_, i) => i);
}

console.log("Array.from", performance.now() - now);

now = performance.now();

for (let i = 0; i < 10000; i += 1) {
  const _ = [...Array(101 + i).keys()];
}

console.log("[...keys]", performance.now() - now);
```

```
Array.from 1569.2020409107208
[...keys] 870.6262919902802 // 2배 빠름!
```

Array.from은 callback 함수를 계속 실행하니까, call stack에 쌓여서 시간이 더 오래 걸리는게 아닐까 생각이 듭니다 :D

2022-08-13 05:34 UTC, nan-noo commented on frontend/src/App.tsx
> +import tw from '@utils/tw';
@utils/tw가 해당 파일에 있어야지만 자동완성 인식이 되는 건가요??

2022-08-13 05:35 UTC, nan-noo approved these changes

2022-08-13 05:35 UTC, merged

2022-08-13 05:43 UTC, airman5573 commented on frontend/src/App.tsx
> +import tw from '@utils/tw';
네 맞습니다