[BE] issue306: PathMatcherInterceptor 생성 및 AuthenticationInterceptor 개선
woowacourse-teams/2022-moamoa pull request #307
Opened 2022-08-29 09:06 UTC by jaejae-yoo

## 요약

## 세부사항

close #306

2022-09-14 05:41 UTC, wilgur513 approved these changes
굿굿!

2022-09-15 05:01 UTC, tco0427 approved these changes
수고하셨습니다!

2022-09-15 05:12 UTC, sc0116 requested changes
그린론 테스트까지 잘 해주셨네요!! 고생했습니당!

2022-09-15 05:12 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/auth/config/AuthConfig.java
> +                .includePathPattern("/api/study/\\d+", HttpMethod.PUT)
앗 여기 studies 아닌가요??

2022-09-15 05:23 UTC, sc0116 approved these changes

2022-09-15 05:24 UTC, merged