[BE] issue320: 기존 인증에서 githubId 가 아닌 memberId 사용하도록 리팩터링
woowacourse-teams/2022-moamoa pull request #327
Opened 2022-09-13 04:57 UTC by tco0427

## 요약

기존 인증과정에서 사용하던 githubId 를 memberId 를 사용할 수 있도록 수정한다.

## 세부사항

- `AuthenticationPrincipal` 어노테이션을 제거하고, `AuthenticatedMember` 를 사용하도록 한다.
- `AuthenticationArgumentResolver` 를 제거하고, `AuthenticatedMemberResolver` 를 사용하도록 한다.

close #320

2022-09-14 04:13 UTC, sc0116 approved these changes
githubId -> memberId 바꾼거 확인했습니다!

2022-09-14 04:13 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/acceptance/steps/AfterLoginSteps.java
> +    }
정보 가져오는 메서드 굿굿

2022-09-14 05:33 UTC, wilgur513 requested changes

2022-09-14 05:33 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/AuthenticatedRefreshArgumentResolver.java
> +    private final MemberRepository memberRepository;
memberRepository 사용 안하지 않나요??

2022-09-14 05:33 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/auth/service/AuthService.java
>          memberService.saveOrUpdate(githubProfileResponse.toMember());
saveOrUpdate 메서드에서 Member를 반환하면 안되나요?
아니면, 현재 반환하는 MemberResponse의 id를 사용하면 안되나요?

2022-09-14 05:33 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/acceptance/test/member/MemberAcceptanceTest.java
> +        assertThat(memberResponse.getId()).isEqualTo(memberResponse.getId());
memberResponse.getId()을 isEqualTo에 넣는건 이상한 것 같아요. 그냥 isNotNull과 같은 형태로 검증하면 안될까요?

2022-09-14 05:33 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/fixtures/StudyFixtures.java
> +    public static final Member 자바_스터디장 = new Member(짱구_깃허브_아이디, 짱구_유저네임, 짱구_이미지, 짱구_프로필);
스터디장이 왜 Member로 사용하는지 이해가 안됩니다...
지금 비교문에 스터디장을 사용하는데 Member가 아닌 MemberResponse나 MemberData로 둬야할 것 같고,
비교되는 코드에서도 githubId가 아닌 memberId를 사용하는 거 같은데... 한번 확인해주세요

2022-09-14 05:33 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/member/controller/MemberControllerTest.java
> +        assertThat(response.getBody().getId()).isEqualTo(memberResponse.getId());
여기도 isNotNull과 같은 검증문으로 변경하는게 좋아보입니다.

2022-09-14 05:36 UTC, jaejae-yoo requested changes

2022-09-14 05:36 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/auth/service/AuthService.java
> +                .orElseThrow();
적절한 예외를 던져줘야 할 것 같아요!

2022-09-14 05:36 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/member/service/MemberService.java
> +    public MemberResponse saveOrUpdate(final Member member) {
프로덕션 코드에서 외부에 해당 데이터가 필요한 경우가 없는 데 response를 반환한 이유가 궁금해요!

2022-09-14 05:36 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/study/service/StudyService.java
> -    private Study findStudyBy(final Long studyId) {
쓰이지 않던 메서드를 제거해주신 걸까요 ??

2022-09-14 05:36 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/acceptance/test/auth/AuthAcceptanceTest.java
> +        final Member member = memberRepository.findByGithubId(4L).orElseThrow();
테스트 코드이니 `memberRepository.findByGithubId(4L).get();`이 나을 것 같아요! 
다른 테스트 코드에서도 orElseThrow(); 쓰는 부분 확인 부탁드려요 ~

2022-09-14 07:05 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/AuthenticatedRefreshArgumentResolver.java
> +    private final MemberRepository memberRepository;
맞습니다!

2022-09-14 07:06 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/service/AuthService.java
>          memberService.saveOrUpdate(githubProfileResponse.toMember());
MemberResponse 사용하도록 수정하였습니다!

2022-09-14 07:08 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/test/member/MemberAcceptanceTest.java
> +        assertThat(memberResponse.getId()).isEqualTo(memberResponse.getId());
`isNotNull()` 로 id 존재여부만 확인하도록 수정하였습니다!

2022-09-14 07:09 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/member/controller/MemberControllerTest.java
> +        assertThat(response.getBody().getId()).isEqualTo(memberResponse.getId());
수정하였습니다..!!

2022-09-14 07:10 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/service/AuthService.java
> +                .orElseThrow();
saveOrUpdate() 에서 반환되는 값을 사용하면서 조회 로직 제거되었습니다!!

2022-09-14 07:11 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/member/service/MemberService.java
> +    public MemberResponse saveOrUpdate(final Member member) {
이거 사용하려다가 반영을 못했네요,,리팩터링 중간 부산물이 남아있었던 것 같습니다!

2022-09-14 07:14 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/StudyService.java
> -    private Study findStudyBy(final Long studyId) {
넵!! 중복되서 사용되는 곳이 없어서 `final Member owner = memberRepository.findById(memberId)
                .orElseThrow(MemberNotFoundException::new);` 를 사용하고 있습니다!

2022-09-14 07:17 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/test/auth/AuthAcceptanceTest.java
> +        final Member member = memberRepository.findByGithubId(4L).orElseThrow();
테스트 코드가 어디서 깨지는지 확인하기 편할 것 같아 orElseThrow() 를 사용하도록 하였습니다!
어떤 예외가 던져지는지 추가하여 수정하도록 하겠습니다!!

2022-09-14 22:43 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/test/auth/AuthAcceptanceTest.java
> +        final Member member = memberRepository.findByGithubId(4L).orElseThrow();
[우아한테크코스 레벨2 지하철 노선도 미션 정리](https://velog.io/@tco0427/%EC%9A%B0%EC%95%84%ED%95%9C%ED%85%8C%ED%81%AC%EC%BD%94%EC%8A%A4-%EB%A0%88%EB%B2%A82-%EC%A7%80%ED%95%98%EC%B2%A0-%EB%85%B8%EC%84%A0%EB%8F%84-%EB%AF%B8%EC%85%98-%EC%A0%95%EB%A6%AC) 를 참고하여 get() 으로 수정하였습니다!

2022-09-14 23:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/fixtures/StudyFixtures.java
> +    public static final Member 자바_스터디장 = new Member(짱구_깃허브_아이디, 짱구_유저네임, 짱구_이미지, 짱구_프로필);
스터디장 FIxture 제거해주었습니다!

2022-09-15 05:22 UTC, wilgur513 approved these changes

2022-09-15 07:18 UTC, jaejae-yoo approved these changes

2022-09-15 07:45 UTC, merged