[BE] Token 개선
woowacourse-teams/2022-moamoa pull request #328
Opened 2022-09-13 05:27 UTC by tco0427

## 요약

AccessToken 및 RefreshToken 개선

## 세부사항

- 현재 AccessToken 과 RefreshToken 의 키가 동일한데, 이 둘을 구분한다.
- AccessToken 을 쿠키로 발급한다.

close #280

2022-09-17 17:46 UTC, jaejae-yoo requested changes
디우 고생하셨습니다 👍
리뷰 확인 부탁드려요 ~

2022-09-17 17:46 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/auth/config/AuthenticationExtractor.java
> +            if (splitAccessToken.length < 2) {
이 로직에 대해서 추가로 설명해주실 수 있나요??

2022-09-17 17:46 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/auth/infrastructure/JwtTokenProvider.java
> +                .setSubject(Long.toString(payload))
기존의 memberId에서 payload로 파라미터 명을 바꾸신 이유가 궁금해요!
값에 변화가 있었던 걸까요??

2022-09-17 17:46 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/AuthController.java
> +        final ResponseCookie accessCookie = putInCookie(ACCESS_TOKEN, response.getAccessToken());
기존에는 REFRESH_TOKEN만 cookie에 담아서 보냈었는데, ACCESS_TOKEN도 cookie에 담아서 보내게 바뀌었군요!
해당 방식으로 바뀌게 된 이유가 궁금합니다ㅎㅎ. 어떤 이점이 있나요??

2022-09-17 17:46 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/auth/infrastructure/JwtTokenProvider.java
> +            @Value("${security.jwt.token.refresh-secret-key}") final String refreshSecretKey,
ACCESS와 REFRESH의 secret 키를 분리하게 된 이유가 궁금해요! :D

2022-09-17 17:46 UTC, jaejae-yoo commented on .github/workflows/backend.yml
> +      refresh-expire-length: ${{ secrets.REFRESH_EXPIRE_LENGTH }}
👍

2022-09-17 17:46 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/auth/config/AuthenticationExtractor.java
> +            final String accessToken = Arrays.stream(value.split(" "))
`BEARER_TYPE`을 안쓰게 바꾸셨군요! 이유가 궁금해요!
인증 타입을 제거했을 때의 문제점은 없을까요??

2022-09-18 04:31 UTC, tco0427 reviewed
안녕하세요, 그린론!!
코멘트 확인하고 답변드렸습니다!!
답변하면서 저도 다시 한 번 생각정리를 할 수 있어서 좋은 리뷰가 되었던 것 같습니다!!

질문 주셨던 `accessToken 만료되어도 쿠키 자체는 유지`에 대해서 답변 드리자면, 현재 저희가 refresh 요청시에 access 와 refresh 토큰 모두를 받고, 검사하여 새로운 액세스 토큰을 발급해주고 있습니다. 이와 같이 해준 이유는 참고할 만한 글을 첨부해드릴게요!!
[디우의 Refresh Token](https://velog.io/@tco0427/Refresh-Token)
[Is a Refresh Token really necessary when using JWT token authentication?](https://stackoverflow.com/questions/32060478/is-a-refresh-token-really-necessary-when-using-jwt-token-authentication)

따라서 현재 만료된 JWT 자체는 필요하므로 (만료되어있는 AccessToken) 토큰 자체는 만료되었지만, 쿠키의 유효시간은 보다 길게 설정하여 해당 쿠키의 값(AccessToken)이 요청으로 넘어올 수 있도록 설정해준 것입니다!!

2022-09-18 04:31 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/config/AuthenticationExtractor.java
> +            final String accessToken = Arrays.stream(value.split(" "))
넵! 우선 저희가 Authorization 헤더가 아닌 쿠키에 값을 담는 방식으로 변경함에 따라서 key & value 쌍이기 때문에, 어떤 타입인지와 무관해지고 쿠키 입장에서는 단순히 하나의 value 로 보게 되기 때문에 문제가 없다고 판단하였고,
추가적으로 기존에 저희가 토큰 추출 과정에서 `Bearer` 문자열이 앞단에 포함되어있는지로 서버에서 판단하고 있었는데, 현재는 그 부분이 사라진 것이고, 타입이 일치하지 않는 경우 JWT 토큰 형식(header, payload, signature) 이 일치하지 않을 것이기 때문에 저희 서버쪽에서 해주던 검증과정은 동일하다고 판단하였습니다!!

추가적으로 `BEARER_TYPE` 상수를 사용하지 않으므로 제거해주도록 하겠습니다..!!

2022-09-18 04:31 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/config/AuthenticationExtractor.java
> +            if (splitAccessToken.length < 2) {
쿠키는 key&value 이고, 여러 쿠키를 가지고 요청을 보낼 수 있기 때문에 `accessToken` 키를 가지는 쿠키를 가져오고 나서 `=` 를 기준으로 split 해줍니다.
만약 length가 2보다 적다면 value가 적절히 없는 경우이게 될 것입니다.
그리고 33 번째줄 이후부터는 기존에 로직과 동일합니다..!!
(기존 Authorization 헤더 에서 추출하던 것을 쿠키에서 추출하도록 변경이 있다보니 로직이 변경되었다고 이해하시면 좋을 것 같습니다!)

2022-09-18 04:31 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/config/AuthenticationExtractor.java
> +            if (splitAccessToken[0].equals("accessToken")) {
오호! `splitAccessToken[0]` 을 `COOKIE_KEY` 와 같은 상수로 변경하면 훨씬 가독성있을 것 같네요!
기존 extract 코드에서 로직 변경에만 급하다보니 기존 코드를 개선해야겠다는 생각을 못했던 것 같습니다...!!
이 외에도 상수 처리하면 가독성이 좋아질 만한 부분을 extract 메소드에서 적용해보도록 하겠습니다!

2022-09-18 04:31 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/config/AuthenticationExtractor.java
> +                request.setAttribute(ACCESS_TOKEN_TYPE, splitAccessToken[1]);
넵! 이 부분은 기존 코드와 논리적으로 동일합니다!!

2022-09-18 04:31 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/controller/AuthController.java
> +        final ResponseCookie accessCookie = putInCookie(ACCESS_TOKEN, response.getAccessToken());
우선 프런트 팀원과 상의한 내용 공유드립니다..!!
[모아모아 로그인 및 로그아웃 등 인증&인가 과정 정리](https://github.com/woowacourse-teams/2022-moamoa/discussions/357) 

저희가 현재 [모아모아](https://moamoa.space) 의 경우에는 refresh가 제대로 동작하지 않고 있습니다. (사용자는 창을 닫으면 다시 로그인을 하여야합니다.) 그리고 그 이유는 액세스 토큰을 session storage 에 저장하고 있기 때문입니다.
즉 저희가 refresh token 을 도입한 이유(사용자의 빈번한 로그인을 제거하여 사용자에게 편의성을 제공한다.) 와는 맞지 않는 방식입니다.

따라서 총 3가지 방법이 존재합니다. JS 변수 저장, local storage, cookie.
JS 변수에 저장하는 경우, 사용자가 새로고침을 하면 계속해서 refresh 요청을 보내야 하기 때문에 이는 저희가 의도한 refresh token 도입 이유(사용자의 빈번한 로그인을 제거한다.) 와는 목적 자체가 맞지 않게 됩니다. (토큰이 사라지므로 재요청한다가 되므로, 또한 액세스 토큰의 유효시간이 30분이지만 새로고침하면 사라지므로 그 의미가 퇴색됨)
따라서 해당 케이스는 제외하였습니다.
다음으로는 local storage 와 cookie 입니다. 두 경우, 거의 유사합니다. 하지만 보안적인 취약점에서 차이가 있습니다. local storage 는 xss 공격에 취약하고, cookie 는 CSRF 공격에 취약합니다. 결론적으로는 xss는 발생 빈도가 높지만(공격하기가 보다 쉽지만) 보다 치명적이지는 않습니다. 하지만 CSRF의 경우에는 발생 빈도가 더 적지만, 보다 치명적일 수 있습니다.
하지만 결국, CSRF 공격의 경우에도 개인에 대해서, 즉 DB입장에서는 사용자 한명에 데이터에 대해서만(ex. A 사용자가 CSRF 공격을 당한다면 A 가 만든 스터디 삭제와 같은 식) 공격이 가능하며, 발생하려면 모든 조건이 맞아 떨어져야하기 때문에 쿠키를 선택하였습니다.
이 외에도 쿠키를 사용하면 local storage와는 또 다른 이점을 얻을 수 있는데, 프런트 측에서 더 이상 인증 및 인가 과정에 대해서 고민할 필요가 없게 되고, 서버측에서만 관리하면 된다는 것입니다. (어떻게 보면 보안적인 측면보다 해당 측면이 저와 프런트 크루가 선택한 가장 큰 이유인 것 같습니다.ㅎㅎ) 생각해보면 프런트는 뷰와 관련된 측면을 관리하고, 비즈니스 로직이나 인증 및 인가 과정 등에 대한 책임을 서버쪽에서만 고려하면 되는데 현재 구조에서는 어쨋든 토큰을 저장하고, 인증이 필요한 요청에는 토큰을 실으는 등 프런트측에서 고려할 사항이 있기 때문에 쿠키에 담는 현재 방식이 보다 적절한 책임 분리라고 판단한였습니다!

물론 3 case 모두 새로고침시 refresh 요청을 보내야하는 상황입니다.(프런트입장에서는 현재 로그인 상태인지 비로그인 상태인지 판단할 수 없으므로 이를 확인하기 위해) 하지만 refresh API 의 목적이 `새로운 액세스 토큰을 발급한다` 와는 거리가 있는 API 의 활용이므로, 로그인 상태를 위한 새로운 API 를 만들어 개선하였습니다. (현재 코드에 반영 X...간단한 API 이므로 현재 코드에서 큰 변화는 없을 듯 합니다!)

혹시 추가적인 질문이 있으신경우 추가 질문해주세요~_~

2022-09-18 04:31 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/infrastructure/JwtTokenProvider.java
> +            @Value("${security.jwt.token.refresh-secret-key}") final String refreshSecretKey,
이전에 제가 잘못 사용하고 있었습니다.ㅜ.ㅜ 서로 다른 두 토큰에 대해서 같은 키를 사용하는 것은 잘못되었으므로, 둘에 대해서 키를 분리해주었습니다.

2022-09-18 04:31 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/infrastructure/JwtTokenProvider.java
> +                .setSubject(Long.toString(payload))
이번에 githubId 에서 MemberId 로 변경하면서 느꼈습니다. 현재 createAccessToken() 메소드에서는 payload 가 넘어오므로 이를 담아서 새로운 토큰을 만들어준다는 사실만을 알면되지 무엇이 구체적으로 넘어오는지는 해당 메소드의 관심사가 아니므로 변경해주었습니다!!

2022-09-18 04:31 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/auth/config/AuthenticationExtractor.java
> +                    .findAny().orElseThrow();
넵! 해당 부분 확인하고 예외 추가하도록 하겠습니다!

2022-09-27 07:36 UTC, closed without merging