[BE] issue322: 스터디 모집 상태 변경 버그
woowacourse-teams/2022-moamoa pull request #331
Opened 2022-09-13 06:52 UTC by jaejae-yoo

## 요약 및 세부사항
- 모집 완료 상태에서 내용을 수정하면 모집중으로 바뀌는 오류 수정
    - 스터디 상세 내역을 업데이트할 때, recruit 상태를 판단해야 하는 로직에서 study 현재 인원 수를 고려하고 있지 않았습니다.

- 모집 인원 중 한명이 탈퇴한 경우에도 계속 모집 완료인 오류 수정
    - 스터디원 탈퇴시 모집 상태 변경 조건을 확인하여, 상태를 변경하는 로직이 존재하지 않았습니다.
        - 모집 마감 날짜가 지나지 않은 경우에만 모집중으로 바뀌도록 수정했습니다.

- [ ] 리팩터링 중

close #322

2022-09-13 07:17 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/study/service/StudyParticipantService.java
> +    private final DateTimeSystem dateTimeSystem;
스터디원 탈퇴시 `모집 마감 날짜가 지나지 않았다면` `모집중`으로 바꾸어야 하기 때문에, 날짜 데이터가 필요해서 필드로 선언했습니다!

2022-09-13 07:23 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/RecruitPlanner.java
> +    boolean hasEnrollmentEndDate() {
이 부분은 선언 순서에 맞게 변경했습니다.

2022-09-14 05:55 UTC, wilgur513 requested changes

2022-09-14 05:55 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/request/StudyRequest.java
>              return new RecruitPlanner(maxMemberCount, RECRUITMENT_END, enrollmentEndDate);
StudyRequest의 mapToXXX 메서드들이 수정에 대한 비즈니스 로직을 담고 있는 것 같습니다.
이 부분을 도메인인 Study 쪽을 최대한 옮기는 건 어떨까요?
이것 때문에 도메인 테스트가 아닌, Service나 Controller 테스트로 수정이 올바로 일어나는지를 검증하는 것 같네요.
Study 도메인 테스트를 늘리면서 관련 로직을 Study쪽으로 옮겨보아요.

2022-09-15 00:46 UTC, tco0427 approved these changes
역시 `mapToRecruitPlan()` 의 조건이 생성시만 고려하고 있었네요!
스터디 탈퇴시에 현재시간과의 비교만을 통해서 모집 상태를 변경하는 로직이 인상깊었습니다!

2022-09-15 00:46 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/request/StudyRequest.java
> -        if (maxMemberCount != null && maxMemberCount == 1) {
기존에는 처음 생성시에 대해서만 모집 상태를 고려하고 있었네요!

2022-09-15 01:22 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Study.java
> +        }
스터디 탈퇴 시 날짜를 비교해서 모집중으로 바꿔놓는군요!

2022-09-15 01:27 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/request/StudyRequest.java
> +        if (maxMemberCount != null && maxMemberCount <= currentMemberCount) {
근데 이런 조건은 dto가 아니라 도메인에서 하는건 어떨까요? 현재 회원수를 비교하는게 dto에서 하는게 맞는지 의문이어서요..!

2022-09-15 02:42 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/study/service/request/StudyRequest.java
>              return new RecruitPlanner(maxMemberCount, RECRUITMENT_END, enrollmentEndDate);
https://github.com/woowacourse-teams/2022-moamoa/pull/331/commits/a5f51ab218fb08f5276e18d8c1371c8123519875 

로직 변경 확인 부탁드려요 ~

2022-09-15 02:42 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/study/service/request/StudyRequest.java
> +        if (maxMemberCount != null && maxMemberCount <= currentMemberCount) {
https://github.com/woowacourse-teams/2022-moamoa/pull/331/commits/a5f51ab218fb08f5276e18d8c1371c8123519875 

로직 변경 확인 부탁드려요 ~

2022-09-18 01:00 UTC, jaejae-yoo commented
PR 내용 및 예외 검증 확인 부탁드려요!
사진은 칠판에 적었던 내용 요약 부분에서 잘못된 부분이 있어서 우선 전체 관계도 부분만 첨부해 놓았어요!
테스트 확인 및 로직 검증 부탁드립니다 ~

2022-09-28 10:29 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/RecruitPlannerTest.java
> +public class RecruitPlannerTest {
RecuuitPlanner의 상태에 따라 스터디 생성 여부를 결정하니... RecruitPlannerTest 보다는 CreatingStudyTest로 해야할 것 같아요.

2022-09-28 10:31 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/RecruitPlannerTest.java
> +                .hasMessageContaining("잘못된 기간 설정입니다.");
메시지 검증은 제거해도 된다고 생각합니다.

2022-09-28 10:34 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/RecruitPlannerTest.java
> +    @DisplayName("RECRUIT Planner| 스터디 상태 생성 | 모집 마감일 < 생성일 예외")
DisplayName의 테스트 설명이 이해가 잘안됩니다... 다른 글귀가 좋을 것 같아요.
예를 들어, "스터디의 모집 마감일은 생성일보다 이전일 수 없다" 같이 도메인 규칙을 명확히 이해되는 설명이 좋을 듯 합니다.

2022-09-28 10:35 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/RecruitPlannerTest.java
> +    @DisplayName("RECRUIT Planner| 스터디 상태 생성 | 모집 인원 1명 End")
이 부분의 설명도 "생성한 스터디의 현재 인원(1명)이 모집인원과 같은 경우 모집은 종료된다"와 같은 설명이 적절한 듯 합니다.

2022-09-28 10:37 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/RecruitPlannerTest.java
> +        RecruitPlanner recruitPlanner = new RecruitPlanner(1, RECRUITMENT_START, enrollmentEndDate);
전반적으로 RecruitPlanner의 객체 생성 과정을 손봐야겠네요...
Study 내부에서 RecruitPlanner의 상태를 결정할 수 있으니... 객체 생성 시 현재 RecruitPlanner의 상태를 설정하는 것은 옳지 못한 것 같습니다.

2022-09-28 10:39 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/RecruitPlannerTest.java
> +    @DisplayName("RECRUIT Planner| 스터디 상태 생성 | 예외와 END 이외의 경우 START")
정상적인 스터디 생성 과정이니 설명을 조금 더 상황이 드러나게 작성해보아요

2022-09-28 10:40 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/RecruitPlannerTest.java
> +    @DisplayName("Recruit Planner| 스터디 상태 수정| 모집 마감 날짜 수정일이 생성일 이전으로 수정 OR 수정 인원이 현재 인원 보다 적은 경우 예외")
예외가 발생하는 케이스가 2가지인데 개별 테스트로 작성하는 것이 좋을 것 같습니다.

2022-09-28 10:51 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/RecruitPlannerTest.java
> +    @DisplayName("Recruit Planner| 스터디 상태 수정| 수정일이 모집 마감 날짜 이전 AND 수정 인원이 현재 인원과 같은 경우 END")
`수정일이 모집 마감 날짜 이전인 경우` 또는 `수정 인원이 현재와 같은 경우`가 END이므로 잘못 작성된 거 같습니다.

2022-09-28 10:55 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/RecruitPlannerTest.java
> +    @DisplayName("Recruit Planner| 스터디 상태 수정| 수정일이 모집 마감 날짜 이전 AND 수정 인원이 현재 인원과 같은 경우 START")
나머지 케이스가 Start인데 6가지(모집 마감 날짜 == null, 모집 마감 날짜 == 생성일 <= 수정일, 모집 인원 == null, 모집 인원 > 현재 인원)인데, ParameterizedTest로 작성해야할 것 같습니다.

2022-09-28 11:00 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/StudyPlannerTest.java
> +    @DisplayName("STUDY Planner| 스터디 생성 | 예외와 IN PROGRESS 이외의 경우 PREPARE")
"스터디 시작 일자  <= 스터디 종료 일자" 조건에 맞게 설명을 쓰면 좋을 것 같습니다.

2022-09-28 11:05 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/StudyPlannerTest.java
> +    void updateStudyPlannerIsInProgress() {
여기로 ParameterizedTest로 작성하면 좋을 것 같습니다.

2022-09-28 11:09 UTC, wilgur513 requested changes
테스트 코드에만 우선적으로 피드백 남겼습니다.
테스트 코드부터 가독성 있게 다시 정리한 다음에 프로덕션 코드를 고쳐야할 것 같습니다. 자세한 얘기는 만나서 하시죠

2022-10-05 05:36 UTC, tco0427 approved these changes
복잡한 내용이었는데 수고하셨습니다 린론!

2022-10-05 05:36 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/CreatingStudyTest.java
> +    void recruitMemberSizeIsNull() {
👍

2022-10-05 05:36 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/CreatingStudyTest.java
> +    void nowDateIsBeforeStartDate() {
👍

2022-10-05 05:36 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/UpdatingStudyTest.java
> +    void updateRecruitPlannerMemberSizeIsNull() {
👍

2022-10-05 05:36 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/UpdatingStudyTest.java
> +    void updateRecruitPlannerIs() {
👍

2022-10-05 05:36 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/UpdatingStudyTest.java
> +    void updateStudyPlannerExceptionIfStudyStartBeforeStudyCreate() {
👍

2022-10-05 05:36 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/UpdatingStudyTest.java
> +    void updateStudyPlannerIsInProgress() {
👍

2022-10-05 05:36 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/Study.java
> +        studyPlanner = makStudyPlanner(createdAt, startDate, endDate);
오타인 것 같습니다..!

2022-10-05 05:39 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/StudyService.java
> +//        final StudyPlanner studyPlanner = request.mapToStudyPlanner(LocalDate.now());
주석 제거해주셔도 될 것 같습니다!!

2022-10-05 13:01 UTC, merged