[BE] issue344: 리뷰 리팩토링
woowacourse-teams/2022-moamoa pull request #348
Opened 2022-09-14 09:11 UTC by sc0116

## 요약

## 세부사항

리뷰 관련 파일 스터디룸 패키지 내부로 이동 및 리팩토링

close

2022-09-17 18:13 UTC, jaejae-yoo requested changes
짱구 고생하셨습니다! 👍
`ReviewControllerTest`와 `SearchingReviewControllerTest` 테스트가 깨지는 데 확인부탁드려요 ~

2022-09-17 18:13 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/domain/StudyRoom.java
> +        if (!isPermittedAccessor(accessor)) {
👍

2022-09-17 18:13 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/controller/ReviewController.java
> +        reviewService.updateReview(memberId, studyId, reviewId, editingReviewRequest);
오오 이전에 확인 못 했던 부분이네요. 👍

2022-09-20 04:23 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/service/ReviewService.java
> +        final Accessor accessor = new Accessor(member.getId(), studyId);
넵! Accessor 클래스에 현재 사용하는 로직과 같은 로직이 있어서 바꿨습니당

2022-09-20 04:25 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/service/ReviewService.java
> +                .orElseThrow(StudyNotFoundException::new);
넵 맞습니다

2022-09-20 04:25 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/domain/StudyRoomTest.java
> +}
헉 이건 얼른 수정하겠습니다

2022-09-28 11:12 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/domain/StudyRoom.java
> +            throw new NotParticipatedMemberException();
아마 StudyRoom에 UneditableArticleException이 있을 건데 이거와 합치는게 좋을 듯 합니다. 당연히 이름도 Article을 빼서 적절한 이름으로 변경해야겠죠 ㅎㅎ

2022-09-28 11:34 UTC, wilgur513 requested changes

2022-09-28 11:34 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/domain/review/Review.java
> +        deleted = true;
Article처럼 Accessor를 도입해보는 것도 좋을 것 같습니다.

2022-09-28 11:34 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/service/ReviewService.java
> +                .orElseThrow(MemberNotFoundException::new);
StudyRoom에서 작성 가능한 사용자를 체크하는데 member가 DB에 존재하는지 확인할 필요가 없을 것 같습니다.

2022-09-28 11:34 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/service/ReviewService.java
> +    public Long writeReview(final Long memberId, final Long studyId, final WriteReviewRequest writeReviewRequest) {
WriteReviewRequest와 EditingReviewRequest가 동일하기 때문에 하나로 합치는게 일단은 좋을 것 같습니다.

2022-09-28 11:34 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/service/ReviewService.java
> +        review.updateContent(new AssociatedStudy(studyId), new Reviewer(memberId), editingReviewRequest.getContent());
Article과 비슷한 구조로 만들 수 있을 것 같습니다. Review가 Accessor를 사용해 수정하게 되면, StudyRoom, Member를 DB에 조회할 필요가 없을 것 같습니다.

2022-09-28 11:34 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/domain/StudyRoomTest.java
> +    @DisplayName("스터디에 참여하지 않은 사용자는 리뷰를 작성할 수 없다.")
작성자 ID는 맞으나 스터디 ID가 다른 케이스도 다뤄야할 것 같습니다.

2022-09-29 05:42 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/service/ReviewService.java
> +    public Long writeReview(final Long memberId, final Long studyId, final WriteReviewRequest writeReviewRequest) {
😊

2022-09-29 05:42 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/service/ReviewService.java
> +                .orElseThrow(MemberNotFoundException::new);
StudyRoom에서는 스터디에 참여한 회원인가를 확인하고, 저 부분은 해당 id의 멤버가 존재하냐를 확인하는거라 다르긴 하지만 지금 생각해보면 굳이 회원이 존재하는지 확인안해도 될 것 같네요! 저 로직을 타려면 굳이굳이 힘들게 포스트맨으로 보내야만 탈 것 같네용...

2022-09-29 05:42 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/domain/review/Review.java
> +        deleted = true;
기존 메서드 유지하면서 Accessor 사용한 메서드 추가하고 테스트 통과한거 확인한 뒤 지우는 절차를 밟았는데 재밌네요!

2022-09-29 05:42 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/domain/StudyRoom.java
> +            throw new NotParticipatedMemberException();
앗 합치는건 좋은데 리뷰 작성시 예외 발생하는 경우에 "수정할 수 없는 아티클 예외"를 사용하는게 맞나용?

2022-09-29 05:42 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/domain/StudyRoomTest.java
> +    @DisplayName("스터디에 참여하지 않은 사용자는 리뷰를 작성할 수 없다.")
작성에 있어서는 두 가지가 같은 의미 아닌가요?? 만약 수정, 삭제에서 작성자는 맞지만 스터디가 다른 경우를 말씀하시는거면 ReviewTest에 작성되어있습니다!(삭제만 있고 수정은 없어서 추가했습니다)

2022-09-29 05:46 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/service/ReviewService.java
> +        review.updateContent(new AssociatedStudy(studyId), new Reviewer(memberId), editingReviewRequest.getContent());
Accessor를 사용하도록 수정했는데요! 그래도 해당 스터디나 회원이 있는지 여부는 확인해야 하는거 아닌가요??

2022-09-29 13:04 UTC, jaejae-yoo approved these changes

2022-10-05 11:45 UTC, tco0427 approved these changes
충돌 해결하느라 고생하셨습니다..!!

2022-10-05 12:37 UTC, wilgur513 approved these changes

2022-10-05 12:37 UTC, merged