[BE] issue 329: 링크 모음 패지키 이동 리팩토링
woowacourse-teams/2022-moamoa pull request #350
Opened 2022-09-14 13:19 UTC by wilgur513

## 요약
reference room 패키지 study room으로 이동

## 세부사항

close

2022-09-17 17:11 UTC, jaejae-yoo requested changes
베루스 안녕하세요! 코드 반영해 주신 내용 확인했어요! 
이전보다 중복이 많이 줄었들었네요 👍. 고생하셨습니다.

그런데 전반적으로 코드의 변화도 많고, 제네릭이 많이 쓰이고 있어서 코드를 이해하는 데 어려운 것 같아요.. 
우선 리뷰 남겼는데, 답변 남겨주신 내용 바탕으로 조금 더 이해한 후에 다시 리뷰하겠습니다!

추가적으로 부탁드릴 부분이 있는데요.
혹시 이번 리팩터링으로 변경된 구조에 대해 PR 내용에 조금 더 설명을 부탁드려도 될까요? 구조에 대한 그림이나 설명이 있으면 조금 더 이해하는 데 수월할 것 같습니다!

또 개인적으로 Article과 Content가 서로를 참조하고 있는 구조인데, 서로 타입 간의 관계가 있다 보니 조금 복잡하게 느껴지는 것 같아요! 
둘을 합칠 수 있으면 복잡도가 조금 내려갈 것 같은데, 어떻게 생각하시는지 궁금하네요!

2022-09-17 17:11 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/service/AbstractArticleService.java
> +public abstract class AbstractArticleService<A extends Article<C>, C extends Content<A>> {
community, notice, link 글들을 한 번에 처리할 수 있는 서비스를 만드셨군요! 👍
개인적으로 셋을 합침으로써 중복은 정말 많이 줄었들었지만, 제네릭이 많이 쓰이다 보니 코드가 조금 복잡하게 느껴지는 것 같아요..
고민이 되는 부분이네요... ㅠ

2022-09-20 05:55 UTC, tco0427 requested changes
안녕하세요 베루스! 많은양 리팩터링하시느라 고생하셨습니다!!

Generic을 활용하여 중복되는 CUD 로직을 공통화한 부분과 권한 체크하는 부분을 인터페이스로 풀어내는 부분도 인상깊었습니다!!

몇가지 코멘트 남겼습니다~_~ 확인 부탁드려요!!

2022-09-20 05:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/steps/StudyRelatedSteps.java
> +                    .body(objectMapper.writeValueAsString(new CommunityArticleRequest(title, content)))
`NoticeArticleRequest` 이 되어야 할 것 같아요!

2022-09-20 05:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/domain/article/CommunityContentTest.java
> +                Arguments.of(new Accessor(2L, 1L)) // 일반 참가자
주석 처리 굿!

2022-09-20 05:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/domain/article/LinkArticleTest.java
> +    @CsvSource({"2,1", "1,2"})
여기도 동일하게 `memberId가 잘못된 경우` 와 `studyId가 잘못된 경우` 인 거라고 이해했는데 맞을까요?? ㅇㅅㅇ
여기도 주석을 추가해주시면 읽기 더 편할 것 같습니다!

2022-09-20 05:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/service/CommunityArticleServiceTest.java
> +public class CommunityArticleServiceTest {
public 제거해주셔도 될 것 같아요!

2022-09-20 05:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/service/CommunityArticleServiceTest.java
> +    private CommunityArticleService sut;
이렇게 사용하는 필드가 많아질 때 특히 `sut` 라는 네이밍의 의미가 확 와닿는거 같아요!👍

2022-09-20 05:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/service/CommunityArticleServiceTest.java
> +    @DisplayName("존재하지 않는 링크 공유글을 삭제할 수 없다.")
엇..!! 게시글이라는 말이 더 적절한 것 같아요..!!
혹시 밑에 DisplayName 도 수정해주실 수 있을까요??ㅇㅅㅇ

2022-09-20 05:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/service/LinkArticleServiceTest.java
> +    @DisplayName("게시글을 작성한다.")
어 여기는 sut가 `LinkArticleService` 인데 게시글이라고 DisplayName 이 명시되어 있네요...ㅠ.ㅠ

2022-09-20 05:55 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/service/NoticeArticleServiceTest.java
> +public class NoticeArticleServiceTest {
이쪽도 한 번 DisplayName 봐주시면 좋을 것 같습니다!😃

2022-09-29 14:22 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/domain/article/CommunityContent.java
> +        return new CommunityArticle(studyRoom, accessor.getMemberId(), this);
이건 만나서 얘기하시죠...
이거 말고는 방법이 없네요 ㅠㅠ

2022-09-29 14:23 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/domain/article/Article.java
> +public abstract class Article<T extends Content<? extends Article<T>>> extends BaseEntity {
금욜날 얘기해요~

2022-09-29 14:23 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/service/AbstractArticleService.java
> +        final A article = content.createArticle(studyRoom, new Accessor(memberId, studyId));
둘을 합치기가 전 힘들었습니다...
만나서 얘기하시죠

2022-09-29 14:23 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/service/AbstractArticleService.java
> +public abstract class AbstractArticleService<A extends Article<C>, C extends Content<A>> {
저도 고민입니다.... ㅠㅠㅠ
만나서 얘기하시죠

2022-09-29 14:23 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/controller/CommunityArticleController.java
> +    @DeleteMapping("{article-id}")
반영했습니다

2022-09-29 14:23 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/domain/article/Article.java
> +    public Article(final Long id, final StudyRoom studyRoom, final Long authorId) {
반영했습니다.

2022-09-29 14:28 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/domain/article/Content.java
> +public interface Content<A extends Article<? extends Content<A>>> {
일단은 패키지 분리는 하지 않았습니다. 그 이유가 구체 Article의 생성자를 디폴트로 두고 싶어서입니다. 현재 구체 Article은 Content에서 생성하고 있기 때문에 Article 생성자를 통한 생성을 막기 위해서는 Content와 같은 패키지에 있어야 합니다.
예를 들어 content 패키지를 분리하면 NoticeContent는 NoticeArticle을 생성하기 위해 public 생성자를 사용해야합니다. 이는 NoticeArticle의 생성을 2개의 입구로 할 수 있게 되는 건데... 개인적으로 하나의 통로로만 객체를 생성할 수 있게 막는게 좋을 것 같습니다.

2022-09-29 14:28 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/acceptance/steps/StudyRelatedSteps.java
> +                    .body(objectMapper.writeValueAsString(new CommunityArticleRequest(title, content)))
수정했습니다

2022-09-29 14:28 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/domain/article/LinkArticleTest.java
> +    @CsvSource({"2,1", "1,2"})
주석 말고 좀 더 가독성 있게 코드를 수정해봤습니다. 확인해주세요~

2022-09-29 14:28 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/service/CommunityArticleServiceTest.java
> +public class CommunityArticleServiceTest {
제거했습니다.

2022-09-29 14:29 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/service/CommunityArticleServiceTest.java
> +    @DisplayName("존재하지 않는 링크 공유글을 삭제할 수 없다.")
수정했습니다.

2022-09-29 14:29 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/service/LinkArticleServiceTest.java
> +    @DisplayName("게시글을 작성한다.")
수정했습니다.

2022-09-29 14:29 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/service/NoticeArticleServiceTest.java
> +public class NoticeArticleServiceTest {
수정했습니다.

2022-09-30 00:46 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/domain/article/LinkArticleTest.java
> +    @CsvSource({"2,1", "1,2"})
상수로 처리해주셨군요!👍

2022-09-30 00:50 UTC, tco0427 approved these changes
리뷰 반영해주신 부분 확인하였습니다!!
다만, 피드백 반영 부분 확인하면서 코드를 다시 보니 생성부분에서 특히 article이 content에 의존하고 있다는 느낌을 받았는데요, 당연히 현재 content 내용에 의해서 article의 종류(?)가 달라지기 때문에 의존하는게 맞을 수 있다는 생각도 들면서 정말 여기에 의존하는게 맞을까? 하는 생각도 들었어요...ㅠ.ㅠ
한 번 다시 고민해볼 포인트라고 생각되어 코멘트로 남겨봅니다!

고생하셨습니다!!

2022-10-04 22:30 UTC, tco0427 approved these changes
루스루스베! 빠르게 회의 내용 반영해서 구현해주셨군요..!!
고생하셨습니다!!👍👍

수정해야할 부분은 보이지 않았고, 궁금한 점이나 의견 몇가지 제시해보았습니다! Approve 할게요!

그런데 제가 잘 기억나지 않아서 그러는데..
당시 회의에서 나왔던 내용이 크게 `Generic 을 제거하고 type 을 통해서 공지사항과 게시글을 구분한다.` 이외에도 추가적으로 나왔던 내용이 있었을까요?? (테스트에서 private 메소드 이런 부분 제외하고 구현 상에서..기록 해놓지 않으니...기억이 가물가물..ㅠ.ㅠ)

2022-10-04 22:30 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/controller/ArticleController.java
> +        final Article article = articleService.createArticle(id, studyId, request.createContent(), type);
`reqeust.createContent()` 를 통해서 Content 도메인을 만들어 넘기고 있군요..!!

service로 reqeust만 넘기고 Response를 받는 것은 어떨까요??
풀어쓰면 다음과 같은 것 같아서..

```java
final Content content = request.createContent();
final Article article = articleService.createArticle(id, studyId, content, type);
```
추가적으로 Article을 반환하는 것이 아닌 DTO 를 반환하는것은 어떤가요??

2022-10-04 22:30 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/service/LinkArticleService.java
> +    public LinkArticle createArticle(final Long memberId, final Long studyId, final LinkContent content) {
어 혹시 create 시에는 도메인을 반환하도록 하는 특별한 이유가 있을까요?? 궁금합니다..!!

2022-10-04 22:30 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/domain/link/LinkArticle.java
> +@Where(clause = "deleted = false")
JPA 로 조회시에 항상 where 절에 delete = false 가 추가된다고 이해하면 될까요??

2022-10-04 22:30 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/domain/article/Article.java
> +    @ManyToOne(fetch = FetchType.EAGER)
StudyRoom에 대해서 EAGER 로 해주신 이유를 공유해주시면 좋을 것 같습니다!

`articleRepository.findById()` 시에 article, study, study_member테이블에 대해서 각각 쿼리를 날리는 것이 아닌 한 번에 가져오기 위함이라고 이해하면 될까요??

2022-10-04 22:30 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/query/ArticleDao.java
> +                + "article.created_date as article_created_date, article.last_modified_date as article_last_modified_date, "
쿼리를 변경하면서 {} 를 제거해주셨군요..!! 쿼리 가독성이 훨씬 좋아진 것 같아요!👍

2022-10-04 22:30 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/acceptance/AcceptanceTest.java
> +        jdbcTemplate.update("TRUNCATE TABLE article");
꼼꼼하게 수정해주셨네요!👍

2022-10-04 22:30 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/domain/exception/ArticleNotFoundException.java
> +        super(String.format("%d의 식별자를 가진 %s 게시글이 존재하지 않습니다.", articleId, articleType.getSimpleName()));
어떤 클래스에 대해서 발생한 예외인지 로그로 확인하기 편리할 것 같네요!👍

2022-10-04 22:30 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/service/LinkArticleService.java
> +        article.delete(accessor);
처음 Accessor를 활용할 때는 몰랐는데, 이렇게 보니 Accessor 의 활용도가 굉장히 높네요!
Member가 굳이 필요가 없군요!

2022-10-04 22:30 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/domain/article/ArticleType.java
> +        }
권한 부여(?), 체크(?) 를 여기서 해주고 있군요..!!

2022-10-04 22:30 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/domain/article/ArticleTest.java
> +class ArticleTest {
NoticeArticleTest 처럼 CommunityArticleTest 로 네이밍하는건 어떨까요??

2022-10-04 22:30 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/service/ArticleServiceTest.java
> +    @EnumSource(ArticleType.class)
오..이렇게 Enum 상수를 parameterized 로 테스트할 수 있군요! 하나 배워갑니다~_~

2022-10-04 22:30 UTC, tco0427 commented on backend/src/test/resources/schema.sql
> +    author_id          BIGINT     NOT NULL,
👍

2022-10-04 22:30 UTC, tco0427 commented on backend/src/test/resources/schema.sql
> +    deleted            boolean      NOT NULL,
👍👍

2022-10-04 22:30 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/controller/ArticleController.java
> +@RequestMapping("api/studies/{study-id}/{type}/articles")
API가 길어지면서 articles 는 제거해도 괜찮지 않을까 의견 제시해봅니다!!
`api/studies/1/community/4`, `api/studies/1/notice/5`

2022-10-04 22:30 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/controller/LinkArticleController.java
> +public class LinkArticleController {
Review의 경우에도 `/api/studies/4/links/5` 와 같이 reference-room 을 생략해도 자원을 명시하는데 문제가 없어 보여 어떤지 의견 제시해봅니다!

2022-10-05 01:27 UTC, jaejae-yoo approved these changes

2022-10-05 01:27 UTC, jaejae-yoo commented on backend/src/test/java/com/woowacourse/moamoa/studyroom/domain/link/LinkArticleTest.java
> +        sut.delete(new Accessor(1L, 1L));
`new Accessor(OWNER_ID, STUDY_ID);`
`new Accessor(owner.getId(), studyRoom.getId());`
`new Accessor(1L, 1L);`

통일하면 좋을 것 같아요.
여러 곳에서 같은 값이 쓰이면 필드로 빼는 게 관리하기 더 좋을 것 같아요.

2022-10-06 02:05 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/service/LinkArticleService.java
> +    public LinkArticle createArticle(final Long memberId, final Long studyId, final LinkContent content) {
다음작업 때 ID로 변경하겠습니다~

2022-10-06 05:48 UTC, merged