[FE] issue 326: 태그 다중 선택 기능
woowacourse-teams/2022-moamoa pull request #358
Opened 2022-09-17 08:26 UTC by airman5573

## 요약
스터디를 생성할때 태그를 여러개 선택할 수 있습니다

close #326

2022-09-18 14:47 UTC, nan-noo requested changes
여러 태그 선택하기 UI 깔끔하네요! 코멘트 남겼습니다!

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +    });
```suggestion
    const unSelectedOptions = options.filter(({ value }) => !selectedOptions.includes(value));
```

이렇게 바꾸는 건 어떨까요?

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +      });
```suggestion
      setSelectedOptions(prev => prev.filter(({ value }) => option.value !== value));
```

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +    const handleAllClearButton = (event: React.MouseEvent<HTMLButtonElement>) => {
```suggestion
    const handleAllClearButtonClick = (event: React.MouseEvent<HTMLButtonElement>) => {
```

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +        !isMenuClicked && setIsOpenMenu(false);
개행을 하면 좋을것 같아요!

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +        !isMenuClicked && setIsOpenMenu(false);
DropDownBox 컴포넌트를 사용하는 건 어떨까요?

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +                </S.SelectMenuItem>
이것도 컴포넌트 분리하면 좋을 것 같아요!

+ unSelectedOptions를 렌더링하는데 styled 컴포넌트 이름이 select menu item이라서 어색한 것 같아요!
+ ListItem 컴포넌트를 만드는 건 어떨까요?

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/pages/create-study-page/components/subject/Subject.tsx
> +      }
```suggestion
      const etcTag = subjects.find(tag => tag.name === 'Etc') ?? '%ERROR%';
```

콘솔 등등으로 조금 더 약하게 에러를 표시하는 건 어떨까요?

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/pages/create-study-page/components/subject/Subject.tsx
> +      }
throw를 하면 app이 멈춰버리니까..!

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/pages/create-study-page/components/subject/Subject.tsx
>      if (data?.tags) {
early return 하는 게 좋을 것 같아요!

위에 isError도 isError || !isSuccess로 바꾸면 early return도 필요 없겠네요

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/pages/create-study-page/components/subject/Subject.tsx
> +      }, [] as MultiTagSelectProps['options']);
```suggestion
      const options = subjects.map(({ id, description }) => ({
         value: id,
         label: description
      }));
```

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/pages/create-study-page/components/subject/Subject.tsx
> +      }, [] as MultiTagSelectProps['options']);
위에 동일한 로직이 있으니 함수로 분리해도 좋을 것 같아요!

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/pages/main-page/components/study-card/StudyCard.tsx
> +            {tags &&
👍 태그가 없는 경우도 존재하는군요!

2022-09-18 14:47 UTC, nan-noo commented on frontend/webpack/webpack.common.js
> +const smp = new SpeedMeasurePlugin();
이 플러그인은 local, dev, prod 상관 없이 모두 필요하나요?

2022-09-18 14:47 UTC, nan-noo commented on frontend/webpack/webpack.common.js
> +const smp = new SpeedMeasurePlugin();
common에 있어서요!

2022-09-18 14:47 UTC, nan-noo commented on frontend/webpack/webpack.prod.js
> +      config: [__filename],
성능이 얼마나 달라졌는지도 PR에 추가해주면 좋을 것 같아요!

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.style.tsx
> +  min-width: 0px;
0px!!

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.style.tsx
> +      background-color: ${theme.colors.red};
red 색은 input 유효성 검사나 오류 발생했을 때 말고는 쓰지 않았으면 좋을 것 같아요!

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.style.tsx
> +
이 파일에서 전체적으로 개행을 추가해주고 순서를 지켜줬으면 합니당!

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +import { UnstyledButton } from '@components/button/unstyled-button/UnstyledButton.style';
.style에서 가져왔네요!

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +    );
serializedSelectedValues가 바뀔 때 inputRef.current.value = serializedSelectedValues로 하고
그냥 input 요소에 ref={inputRef} 를 하는 것과 어떤 차이인가요?

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/pages/create-study-page/hooks/useCreateStudyPage.ts
> +    const subject = values['subject'].split(',');
','를 변수로 빼는 게 휴먼 에러를 줄일 수 있을 것 같아요!

2022-09-18 14:47 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +      </S.Container>
Input, DropDownBox, IconButton, TextButton, Chip, Flex 등등
또는 tw를 활용할 수도 있을 것 같아요!

2022-09-19 00:40 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.style.tsx
> +  min-width: 0px;
Oops..!

2022-09-19 04:23 UTC, airman5573 commented on frontend/src/components/center/Center.style.tsx
> +`;
Flex를 쓰면  
`<Flex alignItems="center" justifyContent="center"></Flex>` 이렇게 될것 같아요!   

자주 쓰일것 같은데, 이런식으로 한번 더 추상화 하는건 어떻게 생각하시나요?  
`const Center = () => <Flex alignItems="center" justifyContent="center"></Flex>;`

2022-09-19 05:29 UTC, airman5573 commented on frontend/src/components/button/unstyled-button/UnstyledButton.tsx
> +export default S.UnstyledButton;
맞네요!  
-- 회의 결과 --
UnstyledButton대신 TextButton을 사용하자!

2022-09-19 05:31 UTC, airman5573 commented on frontend/package.json
> +    "@babel/preset-typescript": "^7.18.6",
테스트 하다가 미처 바꿔놓지 않았네요, 수정하겠습니다 :D

2022-09-19 05:42 UTC, airman5573 commented on frontend/src/components/icons/x-mark-icon/XMarkIcon.tsx
> +  if (size === 'sm') {
font-size를 적용하는건 좋은데, `sm / base / md` 이런식으로 크기를 정해놓는 건 어떨까요?  
```tsx
const fontSizeMap = {
  sm: '14px',
  base: '20px',
};

const XMarkIcon: React.FC<XMarkIconProps> = ({ size = 'base' }) => {
  return (
    <svg
      height="1em"
      width="1em"
      viewBox="0 0 20 20"
      aria-hidden="true"
      focusable="false"
      style={{ fontSize: fontSizeMap[size] }}
    >
      <path d="M14.348 14.849c-0.469 0.469-1.229 0.469-1.697 0l-2.651-3.030-2.651 3.029c-0.469 0.469-1.229 0.469-1.697 0-0.469-0.469-0.469-1.229 0-1.697l2.758-3.15-2.759-3.152c-0.469-0.469-0.469-1.228 0-1.697s1.228-0.469 1.697 0l2.652 3.031 2.651-3.031c0.469-0.469 1.228-0.469 1.697 0s0.469 1.229 0 1.697l-2.758 3.152 2.758 3.15c0.469 0.469 0.469 1.229 0 1.698z"></path>
    </svg>
  );
};
```

2022-09-19 06:54 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +const MultiTagSelect = forwardRef<HTMLInputElement, MultiTagSelectProps>(
안해줘도 된다고 생각합니다.  

forwardRef의 모양은 아래와 같습니다.  
```function forwardRef<T, P = {}>(render: ForwardRefRenderFunction<T, P>): ForwardRefExoticComponent<PropsWithoutRef<P> & RefAttributes<T>>;```  
보시면 `forwardRef`는 `ForwardRefExoticComponent`를 리턴하는 함수입니다.  
그래서 굳이! React.FC로 다시 타입을 정해줄  필요는 없다고 생각합니다 :D

2022-09-19 07:23 UTC, airman5573 commented on frontend/webpack/webpack.prod.js
> +      config: [__filename],
이번에 테스트 설정들이 같이 올라갔는데요,  
성능 최적화는 다른 PR로 다시 올리겠습니다 :D  

[99b6b97](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/99b6b972fd41a369fdfec744705b1d5de7d2f83b)

2022-09-19 07:48 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.style.tsx
> +      background-color: ${theme.colors.red};
수정했습니다 :D  
[0786015](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/078601506c3b2945e7c7637e661ca23e2437af1f)

2022-09-19 07:48 UTC, airman5573 commented on frontend/webpack/webpack.common.js
> +const smp = new SpeedMeasurePlugin();
수정했습니다 :D  
[3a470e8](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/3a470e828efb9256483bdd4ae5962b4c4f74ef58)

2022-09-19 07:49 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +  selectedOptoins?: Array<Option>;
수정했습니다 :D  
[c864fea](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/c864feaf6f93fd104bab33ed05759231dafa606d)

2022-09-19 07:50 UTC, airman5573 commented on frontend/src/components/icons/x-mark-icon/XMarkIcon.tsx
> +  if (size === 'sm') {
좋습니다 :D  

[e587003](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/e587003a7c9941c79d7d1cb2f38569fe357ae59a)

2022-09-19 07:52 UTC, airman5573 commented on frontend/src/components/button/unstyled-button/UnstyledButton.style.tsx
> +  background-color: transparent;
텍스트 버튼과 아이콘 버튼을 override하기에는 각각 색깔이 뚜렷해서, UnstyledButton을 사용하는것이 좋아보입니다 :D

2022-09-19 07:53 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.style.tsx
> +  border-color: rgb(204, 204, 204);
수정했습니다 :D  

[0786015](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/078601506c3b2945e7c7637e661ca23e2437af1f)

2022-09-20 01:06 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +      </S.Container>
-- 회의결과 --

디자인 시스템 재설계.  

----
이번 PR머지되면 약속된 디자인 시스템으로 개선하고  
이 컴포넌트에 적용하겠습니다 :D

2022-09-20 01:07 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +              </S.SelectedOptionListItem>
이것도 새로운 디자인 시스템 적용하면서 같이 개선하겠습니다 :D

2022-09-20 04:43 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +    const innerInputRef = useRef() as React.MutableRefObject<HTMLInputElement>;
수정했습니다 :D  

[d28569f](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/d28569f3a0f9051deff5614745c0812db2e1f271)

2022-09-20 04:47 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +    });
`selectedOptions `가 가지고 있는건 option 객체라서 위의 로직은 작동하지 않습니다! 
다만 return문을 제거할 수 있네요 :D  

[76e5048](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/76e50486b2c73af73bca7e0fe085d21277617119)

2022-09-20 04:50 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +      });
좋습니다 :D  

[76e5048](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/76e50486b2c73af73bca7e0fe085d21277617119)

2022-09-20 04:54 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +    const handleAllClearButton = (event: React.MouseEvent<HTMLButtonElement>) => {
[28b4911](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/28b49110c0451b1d88ba64b88d56a7d04dd8dfe3)

2022-09-20 05:14 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +        !isMenuClicked && setIsOpenMenu(false);
반영했습니다 :D  

[bb0dc67](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/bb0dc67816be9a41d96c12271ee6cdccb3fd83b1)

2022-09-20 05:20 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +                </S.SelectMenuItem>
아직 선택되지 않은 옵션들(unSelectedOptions)을 선택할 메뉴 아이템 컴포넌트(SelectMenuItem)로 그린다는 의미였습니다. 그래서 이것도 괜찮아 보이는데, 어떻게 생각하시나요?

ListItem 컴포넌트를 만드는 건 어떨까요?
=> 공통 컴포넌트로 빼자는 의미인가요?  
만약 맞다면, 아직은 조금 이르지 않나 싶습니다!

2022-09-20 05:20 UTC, airman5573 commented on frontend/src/pages/create-study-page/components/subject/Subject.tsx
> +      }
그런데 저희가 콘솔을 자주 보는건 아니라서, 조금 불안하네요.  
alert는 어떨까요?

2022-09-20 06:04 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.style.tsx
> +
넵 :D  

[f4fd8c6](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/f4fd8c675a84c3c0ca2be8bb557b944a2386213f)

2022-09-20 06:06 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +import { UnstyledButton } from '@components/button/unstyled-button/UnstyledButton.style';
수정했습니다 :D  

[link](https://github.com/woowacourse-teams/2022-moamoa/blob/bceb2544f2b089dc0b3c2352cf09cf9d3481dad8/frontend/src/components/multi-tag-select/MultiTagSelect.tsx#L6)

2022-09-20 06:28 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +    );
inputRef는 현재 함수라서 inputRef.current 이런식으로 접근을 할 수 없습니다.  

그나저나, useImperativeHandle로 구현 가능하긴 한데 조금 더 명시적인 구현을 위해서 useEffect를 사용했습니다.  
[link](https://github.com/woowacourse-teams/2022-moamoa/blob/bceb2544f2b089dc0b3c2352cf09cf9d3481dad8/frontend/src/components/multi-tag-select/MultiTagSelect.tsx#L23)

2022-09-20 06:32 UTC, airman5573 commented on frontend/src/pages/create-study-page/hooks/useCreateStudyPage.ts
> +    const subject = values['subject'].split(',');
수정했습니다 :D  

[e7f4a96](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/e7f4a9603d36dcffaf3ab44036738b97a3526d7d)

2022-09-20 06:43 UTC, airman5573 commented on frontend/src/pages/create-study-page/components/subject/Subject.tsx
> +      }, [] as MultiTagSelectProps['options']);
좋은 생각입니다!  

[link](https://github.com/woowacourse-teams/2022-moamoa/blob/64fad8f8fba7cfa7318d5110022220bd4e7ee5d8/frontend/src/pages/create-study-page/components/subject/Subject.tsx#L17)

2022-09-20 07:05 UTC, airman5573 commented on frontend/src/pages/create-study-page/components/subject/Subject.tsx
>      if (data?.tags) {
수정했습니다 :D  

[ae00d02](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/ae00d02d7b0c927dda9649a13d2d1e49c2312664)

2022-09-20 07:53 UTC, nan-noo requested changes
추가로 궁금한 점 리뷰 남겼습니다!!

2022-09-20 07:53 UTC, nan-noo commented on frontend/src/components/drop-down-box/DropDownBox.tsx
> +      if (event.target === ref.current) return;
```suggestion
      if (event.target === null || event.target === ref.current) return;
```

2022-09-20 07:53 UTC, nan-noo commented on frontend/src/components/drop-down-box/DropDownBox.tsx
> +    const handleClose = (event: MouseEvent) => {
저희 event 객체 파라미터는 e로 했던 거 같아요!

2022-09-20 07:53 UTC, nan-noo commented on frontend/src/components/drop-down-box/DropDownBox.tsx
> +      const isDropDownBoxClicked = path.findIndex(el => el === ref.current) > 0;
```suggestion
      const isDropDownBoxClicked = path.some(el => el === ref.current);
```

그런데 이걸 하면 위에서 `if (event.target === ref.current) return;`가 의미가 있나요??

2022-09-20 07:53 UTC, nan-noo commented on frontend/src/components/drop-down-box/DropDownBox.tsx
> +      const isDropDownBoxClicked = path.findIndex(el => el === ref.current) > 0;
반복문을 덜 돌게 하려고 처리한 건가요?

2022-09-20 07:53 UTC, nan-noo commented on frontend/src/components/drop-down-box/DropDownBox.tsx
>      requestAnimationFrame(() => document.body.addEventListener('click', handleClose));
위에서 드롭박스를 클릭하면 꺼지지 않도록 처리했으니 requestAnimationFrame도 없어도 되지 않을까요??

2022-09-20 07:53 UTC, nan-noo commented on frontend/src/components/drop-down-box/DropDownBox.tsx
> +const DropDownBox: React.FC<DropDownBoxProps> = ({ children, isOpen, onClose, padding, ...positions }) => {
개선 했군요!

2022-09-20 07:53 UTC, nan-noo commented on frontend/src/components/drop-down-box/DropDownBox.tsx
> +  if (!isOpen) return <></>;
그냥 return; 해도 되지 않을까요? 아니면 아래에 같이 
return isOpen && <S.Drop~~ 해도 될 것 같아요

2022-09-20 07:53 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +      ({ value }) => selectedOptions.findIndex(option => option.value === value) === -1,
```suggestion
      ({ value }) => selectedOptions.some(option => option.value === value);
```

some은 어떨까요?

2022-09-20 07:53 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +      if (isFunction<(element: HTMLInputElement) => void>(inputRef)) {
typeof function을 사용하지 않은 이유는 무엇인가요??

2022-09-20 07:53 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +      <UnstyledButton css={tw`text-18`} onClick={handleAllClearButtonClick}>
UnstyledButton에 fontSize를 입력받을 수 있게 제한하는 건 어떨까요?

2022-09-20 07:53 UTC, nan-noo commented on frontend/src/utils/isFunction.ts
> +  return Object.prototype.toString.call(val) === '[object Function]';
문자열에 의존하는 타입 체크가 위험하진 않을까요??

2022-09-20 07:53 UTC, nan-noo commented on frontend/src/utils/isNullOrUndefined.ts
> +export default (value: unknown): value is null | undefined => value == null;
return 값이 value == null 인 것은 어떤 의미인가요?

함수 이름(파일명)만 보면 boolean 값을 return해야 할 것 같아요

2022-09-20 07:53 UTC, nan-noo commented on frontend/src/utils/isNullOrUndefined.ts
> +export default (value: unknown): value is null | undefined => value == null;
default export여도 함수 명을 붙여주는 건 어떨까요?

2022-09-20 07:53 UTC, nan-noo commented on frontend/webpack/webpack.dev.js
> +  devtool: 'source-map',
https://webpack.js.org/configuration/devtool/

여기를 보면 eval-source-map은 개발 빌드에 좋고 rebuild도 source-map보다 빠르다 하는데 바꾼 이유가 무엇인가요??

source-map은 'production builds with high quality SourceMaps.'라 써져 있어요!

2022-09-20 07:53 UTC, nan-noo commented on frontend/src/components/button/unstyled-button/UnstyledButton.tsx
> +  className?: string;
클래스 네임을 받으면 스타일 관련(css props)해서 너무 열어 놓는 것이 아닐까요?

2022-09-20 07:54 UTC, nan-noo commented on frontend/src/components/center/Center.style.tsx
> +`;
자주 쓰이게 되면 분리하는 게 좋을 것 같네요!

2022-09-20 08:20 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +    });
네, 수정했습니다 :D  

[9eb5d6a](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/9eb5d6acc4b0daac1eac5f49afa6d89528ad7560)

2022-09-20 11:40 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +                </S.SelectMenuItem>
좋습니다.  

내용이 길어 우선 commit을 했는데, 한번 확인해주세요 :D  
[1960cdf](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/1960cdfafef6e76e3e10b2a7ff801db8255f048a)

2022-09-20 11:50 UTC, airman5573 commented on frontend/src/pages/create-study-page/components/subject/Subject.tsx
> +      }
좋은 생각이네요 :D  

[e0904de](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/e0904deca602d97a3643acb6b7d20aa8e99ae00c)

2022-09-20 11:52 UTC, airman5573 commented on frontend/webpack/webpack.dev.js
> +  devtool: 'source-map',
아! 저희 `webpack.dev.js`는 개발 서버용입니다.  
eval-source-map은 로컬 개발 서버에서 사용하고 있어요.

2022-09-20 11:56 UTC, airman5573 commented on frontend/src/utils/isNullOrUndefined.ts
> +export default (value: unknown): value is null | undefined => value == null;
return 값이 value == null 인 것은 어떤 의미인가요?
=> value === undefined || value === null 과 같은 의미입니다!

2022-09-20 12:18 UTC, airman5573 commented on frontend/src/utils/isFunction.ts
> +  return Object.prototype.toString.call(val) === '[object Function]';
구형 브라우저에서는 잘 작동 안하는 방식으로 보입니다.  
typeof val === 'function' 이 좋겠네요 :D  

[8d50b9d](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/8d50b9d3b78b65ae6cdd9bc52ac9a9af5d96e73f)

2022-09-20 12:18 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +      <UnstyledButton css={tw`text-18`} onClick={handleAllClearButtonClick}>
음, 제가 tw를 남겨놨었군요.  
UnstyledButton을 상속받으면 문제는 없어 보입니다!  
```tsx
const AllClearButton = styled(UnstyledButton)`
  font-size: 14px;
`;

<S.AllClearButton onClick={handleAllClearButtonClick}>
  <Center>
    <XMarkIcon />
  </Center>
</S.AllClearButton>
```
UnstyledButton은 상속용으로만 사용하고 싶다는 생각이 드네요, 나중에 font-size를 줘야만 할때 다시 고민해 보는건 어떨까요?

2022-09-20 12:20 UTC, airman5573 commented on frontend/src/components/button/unstyled-button/UnstyledButton.tsx
> +  className?: string;
맞습니다.

[ba628bb](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/ba628bbdc3e63249313bafa4da95dcf651b7568e)

2022-09-20 12:22 UTC, airman5573 commented on frontend/src/components/drop-down-box/DropDownBox.tsx
> +      if (event.target === ref.current) return;
[d82014a](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/d82014a955c4df4c9f70aef827a79a573bac3d97)

2022-09-20 12:23 UTC, airman5573 commented on frontend/src/components/drop-down-box/DropDownBox.tsx
> +    const handleClose = (event: MouseEvent) => {
일관성에 더 좋네요 :D  
[03e9bb2](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/03e9bb28ef6d18d3f27dad97d971d8e34cf9cb4e)

2022-09-20 12:25 UTC, airman5573 commented on frontend/src/components/drop-down-box/DropDownBox.style.tsx
> +    overflow-y: scroll;
오, 차이가 있었군요.  
[https://stackoverflow.com/a/6689440/9279003](https://stackoverflow.com/a/6689440/9279003)
```
Auto will only show a scrollbar when any content is clipped.  

Scroll will however always show the scrollbar even if all content fits and you cant scroll it.  
```
[ccacde2](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/ccacde20d62dfb365c9153047c2c818dd5c1f68e)

2022-09-20 12:29 UTC, airman5573 commented on frontend/src/components/drop-down-box/DropDownBox.tsx
> +      const isDropDownBoxClicked = path.findIndex(el => el === ref.current) > 0;
path를 순회한것은, DropDownBox가 클릭된것인지, 그 외의 공간이 클릭된것인지 확인하기 위함입니다 :D  
그래서 DropDownBox외의 다른 공간을 클릭하면 
`!isDropDownBoxClicked && onClose();` 로직에 의해 DropDownBox가 close됩니다.

2022-09-20 12:31 UTC, airman5573 commented on frontend/src/components/drop-down-box/DropDownBox.tsx
> +  if (!isOpen) return <></>;
저희가 React.FC를 리턴 타입으로 지정해 놨기 때문에, false / undefined / null 은 리턴값이 될 수 없습니다 :D

2022-09-20 12:51 UTC, airman5573 commented on frontend/src/components/drop-down-box/DropDownBox.tsx
>      requestAnimationFrame(() => document.body.addEventListener('click', handleClose));
반대로 드롭박스 외의 공간을 클릭하면 꺼지도록 했으니,  
requestAnimationFrame가 없다면 드롭박스를 open할 수 없습니다.  
왜냐면 이벤트 전파가 끝나기 전에 addEventListener가 호출되기 때문입니다.  

1. mount
2. body에 addEventListener
3. Control 클릭 (드롭박스을 열기 위해)
4. 그런데 Control에 달아놓은 onClick은 사실 root엘리먼트에 달려있고, 이는 rendering pipeline의 맨 앞쪽에서 처리가 됩니다.
5. (재조정 과정에서) event가 root까지 버블링되서 처리되는것보다 드롭박스의 useEffect가 먼저 호출되기 때문에
7. re-mount되자마자 바로 close()가 되버립니다.

그래서 이벤트 등록하는 테스크를 한 프레임 늦춘것입니다.  
저도 재조정 과정에 대해 자세히는 모르기 때문에, 이정도 설명만 가능합니다 :D

2022-09-20 13:29 UTC, nan-noo commented on frontend/src/components/drop-down-box/DropDownBox.tsx
> +  if (!isOpen) return <></>;
`(props: P, context?: any): ReactElement<any, any> | null;`
찾아보니 null은 되네요!
 
그러면 Fragment를 사용해서  `<>{isOpen && <S.Drop~~ ></S.Drop~>}</>`하면 되지 않을까요?

2022-09-20 13:45 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +      <UnstyledButton css={tw`text-18`} onClick={handleAllClearButtonClick}>
media-query나 animation 등의 스타일이 아닌데 상속 받는 게 걸리네요. 이런 경우 외에 상속 받아 스타일을 추가하면 기준이 흐트러질 위험이 생기니까요!

2022-09-20 13:48 UTC, nan-noo commented on frontend/webpack/webpack.dev.js
> +  devtool: 'source-map',
아 맞네요!

2022-09-20 13:55 UTC, nan-noo commented on frontend/src/components/drop-down-box/DropDownBox.tsx
> +      const isDropDownBoxClicked = path.findIndex(el => el === ref.current) > 0;
아 0을 포함한 게 아니라 0보다 큰 경우군요. 
드롭박스 내부를 클릭하면 클로즈되지 않고 외부를 클릭했을 때만 클로즈되는 로직인 건 이해했어요!

그런데 아래 로직은
`if (event.target === ref.current) return;` 
=> `const isDropDownBoxClicked = path.some(el => el === ref.current);`이거나  `const isDropDownBoxClicked = path.findIndex(el => el === ref.current) >= 0;`이거에 포함되지 않나요?

2022-09-20 14:03 UTC, nan-noo commented on frontend/src/components/drop-down-box/DropDownBox.tsx
>      requestAnimationFrame(() => document.body.addEventListener('click', handleClose));
정리하자면,  유저 상호작용 이벤트를 리액트가 우선처리하는데 프레임을 늦추지 않으면
드롭박스를 열기 위해 어떤 버튼(드롭박스 외부)을 클릭 -> 드롭박스 오픈 -> useEffect에 의해 이벤트 리스너가 먼저 바디에 등록됨 -> 이 후에 처음 버튼 클릭한 이벤트가 바디까지 전파됨 -> handleClose 로직 실행 -> 버튼은 드롭박스 외부에 있으므로 드롭박스가 닫힘
제가 이해한 게 맞나요??

2022-09-20 14:12 UTC, nan-noo commented on frontend/src/components/drop-down-box/DropDownBox.tsx
> +      const isDropDownBoxClicked = path.findIndex(el => el === ref.current) > 0;
테스트해보니까 아래 코드도 작동 돼요!
```ts
const handleClose = (e) => {
  if (e.target === null) return;

  const path = e.composedPath();
  const isDropDownBoxClicked = path.some(el => el === ref.current);

  !isDropDownBoxClicked && onClose();
};
```

2022-09-20 14:17 UTC, nan-noo reviewed
이전 리뷰에 댓글 추가로 남겼습니다!

2022-09-20 14:17 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.style.tsx
>    right: 0;
DropDownBox에 props로 top, left, right를 줄 수 있어요!

2022-09-20 14:17 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.style.tsx
> +export const SelectButton = styled(UnstyledButton)`
아무래도 단순 스타일을 위한 상속은 마음에 걸리네요

2022-09-20 14:17 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
>        event.stopPropagation(); // 전파를 멈춰야 handleSelectControlClick이 호출되지 않는다
여기도 event가 사용되었네요

2022-09-20 14:23 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
>        event.stopPropagation(); // 전파를 멈춰야 handleSelectControlClick이 호출되지 않는다
수정했습니다 :D  
[9a92068](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/9a92068710cf5030513b5deddffc18e7b7aa29e1)

2022-09-20 15:06 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.style.tsx
> +export const SelectButton = styled(UnstyledButton)`
맞네요, 그러면 이런건 어떨까요?  

```tsx
type UnselectButtonProps = {
  children?: React.ReactNode;
  onClick: React.MouseEventHandler<HTMLButtonElement>;
};

// 지정된 속성값만 받을 수 있으면서
export const UnselectButton = ({ children, onClick: handleClick }: UnselectButtonProps) => {
  const theme = useTheme(); // theme 사용 가능
  const Component = () => (
    <ImportedUnstyledButton onClick={handleClick} fontSize="md"> // fontSize는 지정된 값만 넣음 + 스타일의 응집성이 생김(<UnselectButton fontSize='md'> 이렇게 쓰지 않고, 스타일 관련은 전부 이쪽에 모아놓음) 
      {children}
    </ImportedUnstyledButton>
  );
  return styled(Component)` // props로 표현하기 어려운 추가적인 속성은 styled()로 구현
    animation...
    media-query...

    color: ${theme.colors.primary}; // 예시
  `;
};
```

2022-09-20 15:30 UTC, airman5573 commented on frontend/src/components/drop-down-box/DropDownBox.tsx
> +      const isDropDownBoxClicked = path.findIndex(el => el === ref.current) > 0;
오 맞네요, 태태가 어떤 말을 하려했는지 이해했어요.  
제안해주신 코드로 수정했습니다 :D  

[77b0b46](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/77b0b4601df40a5ac07c54c64a377e539e731c5a)

2022-09-20 23:43 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +      if (isFunction<(element: HTMLInputElement) => void>(inputRef)) {
직접 `typeof inputRef === 'function'`보다는 더 명시적이고 휴먼에러가 적을것이라 생각합니다.  

다만, generic을 넣어줄 필요는 없어 보이네요!  

```ts
useEffect(() => {
      if (!innerInputRef.current) return;
      if (!inputRef) return;
      if (isFunction(inputRef)) {
        inputRef(innerInputRef.current);
        innerInputRef.current.value = serializedSelectedValues;
        return;
      }
      if (isObject(inputRef)) {
        inputRef.current = innerInputRef.current;
        innerInputRef.current.value = serializedSelectedValues;
        return;
      }
      console.error('ref의 타입이 올바르지 않습니다');
    }, [inputRef, serializedSelectedValues]);
```

어떤가요?

2022-09-21 00:27 UTC, airman5573 commented on frontend/src/components/drop-down-box/DropDownBox.tsx
>      requestAnimationFrame(() => document.body.addEventListener('click', handleClose));
네 맞습니다 :D  
추가적으로 
```
useEffect(() => {
    if (!isOpen || !ref.current) return;

    const handleClose = (e: MouseEvent) => {
      console.log('handleClose is called', performance.now());
      if (e.target === null) return;

      const path = e.composedPath();
      const isDropDownBoxClicked = path.some(el => el === ref.current);

      !isDropDownBoxClicked && onClose();
    };

    const $underRoot = document.querySelector('#root > div');
    $underRoot!.addEventListener('click', handleClose);
    return () => $underRoot!.removeEventListener('click', handleClose);
  }, [isOpen, onClose]);
```
body가 아니라 #root > div에 이벤트를 걸어놓으면 프레임을 늦춰도 문제가 발생하지 않습니다!

2022-09-21 00:27 UTC, airman5573 commented on frontend/src/components/drop-down-box/DropDownBox.tsx
> +  if (!isOpen) return <></>;
null은 가능했군요!  

```tsx
if (!isOpen) return <></>;

return (
  <S.DropDownBox {...positions} padding={padding} ref={ref}>
    {children}
  </S.DropDownBox>
);
```

```tsx
return (
  <>
    {isOpen && (
      <S.DropDownBox {...positions} padding={padding} ref={ref}>
        {children}
      </S.DropDownBox>
    )}
  </>
);
```

위 두 코드를 보니, `<></>`에 대해 알고있다면 아래쪽이 더 잘 읽히네요.

제안해주신 방법대로 수정하겠습니다 :D

2022-09-21 00:42 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +      <UnstyledButton css={tw`text-18`} onClick={handleAllClearButtonClick}>
좋은 생각입니다.

[646415e](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/646415e1e9f34198f2a0456793979c1da987afbb)

2022-09-21 00:44 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.style.tsx
>    right: 0;
Good!  

[2e2b35f](https://github.com/woowacourse-teams/2022-moamoa/pull/358/commits/2e2b35f96152f84c220bb74f7f8a06d2421220a8)

2022-09-21 02:47 UTC, nan-noo approved these changes

2022-09-21 02:47 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.style.tsx
>    box-shadow: 0px 0px 4px 0px;
0px이 있네요! 그리고  아마  기본적으로  DropDownBox가 theme.colors.white가 배경색이에요 

max-height만 빼면 상속받지 않아도 될 거 같은데 나중에 컴포넌트 리팩토링 다시 할 때 수정합시다!

2022-09-21 02:57 UTC, nan-noo commented on frontend/src/components/multi-tag-select/MultiTagSelect.style.tsx
> +export const SelectButton = styled(UnstyledButton)`
이런 경우는 애니메이션이나 미디어 쿼리도 필요하면서 도메인을 붙여서 이름을 바꿔줘야할 때 겠네요!

2022-09-21 04:18 UTC, merged