[FE] issue369: 디자인 시스템 적용
woowacourse-teams/2022-moamoa pull request #393
Opened 2022-10-05 14:50 UTC by airman5573

## 요약
[저희가 논의한 바](https://github.com/woowacourse-teams/2022-moamoa/wiki/MOAMOA-FE-Design-System)대로 디자인 시스템을 적용했습니다.  

최대한 main jsx에 스타일 관련 정보를 빼고, 컴포넌트의 구조만 보일 수 있도록 노력했습니다.  
예를들어서 
```tsx

export type EditTitleProps = {
  title: string;
};

const TITLE = 'title';

const EditTitle: React.FC<EditTitleProps> = ({ title }) => {
  const { register, formState } = useFormContext();
  const { errors } = formState;
  const [count, setCount] = useState(0);
  const isValid = !errors[TITLE]?.hasError;

  const handleTitleChange = ({ target: { value } }: React.ChangeEvent<FieldElement>) => setCount(value.length);

  return (
    // 구조만 나옵니다. 
    // LetterCounter가 있고, TitleField가 있구나!
    // css관련 정보를 최대한 뺀 이유는, 그것이 핵심이 아니기 때문입니다.
    // 다만, 지금은 리팩토링이라 괜찮지만 컴포넌트를 새로 만든다 치면 css작성이 조금 까다로울 수는 있을것 같습니다.
    <Self>
      <LetterCounter count={count} maxCount={TITLE_LENGTH.MAX.VALUE} />
      <TitleField isValid={isValid} title={title} onChange={handleTitleChange} register={register} />
    </Self>
  );
};

const Self = styled.div`
  position: relative;
`;

type LetterCouterProps = ImportedLetterCounterProps;
const LetterCounter: React.FC<LetterCouterProps> = ({ ...props }) => {
  const style = css`
    position: absolute;
    right: 4px;
    bottom: 2px;
  `;
  return (
    <div css={style}>
      <ImportedLetterCounter {...props} />
    </div>
  );
};

type TitleFieldProps = {
  isValid: boolean;
  title: string;
  register: UseFormRegister;
  onChange: React.ChangeEventHandler<HTMLInputElement>;
};
const TitleField: React.FC<TitleFieldProps> = ({ isValid, title, register, onChange: handleChange }) => (
  <>
    <Label htmlFor={TITLE} hidden>
      공지사항 제목
    </Label>
    <div
      css={css`
        margin-bottom: 20px;
      `}
    >
      <Input
        id={TITLE}
        type="text"
        placeholder="제목을 입력해 주세요"
        ...
        })}
      />
    </div>
  </>
);
```

파일 변화 양이 너무 많아서, 저랑 나눠서 봐도 될것 같아요!  

close #369

2022-10-06 12:01 UTC, nan-noo commented on frontend/src/pages/study-page/edit-study-page/EditStudyPage.tsx
> +import DescriptionTab from '@pages/study-page/components/description-tab/DescriptionTab';
여기도! @study-page/...

종류가 많은데 index파일을 만드는 건 어떨까요?

2022-10-06 12:03 UTC, nan-noo commented on frontend/src/pages/study-room-page/StudyRoomPage.tsx
> +        <Flex.Item flexGrow={1}>
section이 더 어울릴 것같긴한데 뭔가 방법이 없을까요?(제안)

2022-10-06 12:07 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/article-list/ArticleList.tsx
> +const NoArticle = () => <div>게시글이 없습니다</div>;
로딩, 에러, 빈 데이터... 컴포넌트로 만들어도 좋을 것 같네요!

- 스켈레톤 또는 로딩 스피너
- 에러 컴포넌트(에러 페이지가 있긴 하지만 페이지 관련 에러임!) - 토스트
- 빈 데이터 컴포넌트 - '텅' 이런 거??

2022-10-06 12:11 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/edit/Edit.tsx
>  const Edit: React.FC<EditProps> = ({ studyId, articleId }) => {
Edit-*이랑 Publish-*은 study-page 처럼 뭉쳐도 되지 않을까요??

2022-10-06 12:28 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/review-tab-panel/components/review-comment/ReviewComment.tsx
> +    handleDeleteReviewButtonClick,
👍

2022-10-06 12:28 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/review-tab-panel/components/review-comment/ReviewComment.tsx
> +      {!isEditing && (
삼항연산자로 가능해보입니다.

2022-10-07 01:11 UTC, airman5573 commented on frontend/.eslintrc.json
> +    "@typescript-eslint/no-explicit-any": "off",
좋은 생각입니다 :D

2022-10-07 01:19 UTC, airman5573 commented on frontend/package.json
> +    "csstype": "^3.1.1",
모든 CSS 프로퍼티와 값에 대한 타입을 제공하는 라이브러리 입니다!  
[npm link](https://www.npmjs.com/package/csstype)

2022-10-07 01:20 UTC, airman5573 commented on frontend/package.json
> +    "msw": "^0.47.4",
오류떠서 새로 설치하다가 --save-dev를 안해버렸네요!  
수정하겠습니다 :D

2022-10-07 04:05 UTC, airman5573 commented on frontend/public/mockServiceWorker.js
>  /**
msw 버전이 업데이트 되면서 같이 변경되었습니다 :D

2022-10-07 05:19 UTC, airman5573 commented on frontend/src/styles/responsive.ts
> +export type BreakPoint = typeof breakPoints[number];
제시하신 방법도 좋아보이네요!  
다만, Array<BreakPoint>는 약간 불안해서  

```ts
const arrayOfAll =
  <T>() =>
  <U extends T[]>(array: U & ([T] extends [U[number]] ? unknown : 'Invalid')) =>
    array;

type BreakPoint = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl' | 'xxxl';
const arrayOfAllBreakPoint = arrayOfAll<BreakPoint>();
const breakPoints = arrayOfAllBreakPoint(['xs', 'sm', 'md', 'lg', 'xl', 'xxl', 'xxxl']);
```

이렇게 하면 하나라도 빼먹으면 breakPoints에서 에러가 납니다!  
어떠신가요?

2022-10-07 05:23 UTC, airman5573 commented on frontend/src/styles/responsive.ts
> +  [key in BreakPoint]?: T;
저 For가 루프를 돈다는 의미는 아니고  
T에 대한 BreakPoints 혹은 T를 위한 BreakPoints 를 의미한다고 생각해서,  
Loop보다는 For가 더 어울려보입니다!  

태태는 어떤 이유에서 Loop로 생각하신건가요 ?

2022-10-07 05:57 UTC, airman5573 commented on frontend/src/styles/custom-css.ts
> +};
```typescript
type AllCSSKeys = keyof AllCSSKeyValue;

type PickAllowedCSSKeyValue<AllowedCSSKeys extends AllCSSKeys> = {
  [CSSKey in AllowedCSSKeys]?: AllCSSKeyValue[CSSKey];
};

type ResponsiveCSSKeyValue<AllowedCSSKeys extends AllCSSKeys> = BreakpointsFor<PickAllowedCSSKeyValue<AllowedCSSKeys>>;

export type CustomCSS<AllowedCSSKeys extends AllCSSKeys> = PickAllowedCSSKeyValue<AllowedCSSKeys> & {
  responsive?: ResponsiveCSSKeyValue<AllowedCSSKeys>;
};
```

이렇게 심플하게 바꿔봤습니다!

2022-10-07 06:13 UTC, airman5573 commented on frontend/src/styles/custom-css.ts
> +};
OriginalCSSProperties & {fontSize: ThemeFontSize; ... }를 기본 CSS 속성 타입으로 하는 건 어떨까요  
이렇게 하면 fontSize에 너무 강한 제약을 주는건 아닐까 하는 걱정이 들어요!  
ThemeFontSize와 더불어 px도 받을 수 있게 하는건 어떨까요?

2022-10-08 00:35 UTC, airman5573 commented on frontend/src/styles/responsive.ts
> +  [key in BreakPoint]?: T;
key -> Key 로 수정했습니다 :D  
[f8e77e7](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/f8e77e7bb163a0610f03241ce8a72fe885d4f89a)

2022-10-08 00:42 UTC, airman5573 commented on frontend/src/styles/custom-css.ts
> +      // 우선순위가 중요합니다!! xxxl -> xs 순으로 놓아야 합니다
👍   

[e270bde](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/e270bde6544ae17743eeb8e6f71137b400a69350)

2022-10-08 00:43 UTC, airman5573 commented on frontend/src/components/button/box-button/BoxButton.tsx
> +  custom?: CustomCSS<'padding' | 'fontSize'>;
위에서 수정했습니다!  
(ThemeFontSize + px 등의 기본 css value type)
[7fb0bdb](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/7fb0bdbaf372408708e1e665a1ce00e2e125f7c5)

2022-10-08 01:45 UTC, airman5573 commented on frontend/src/components/button-group/ButtonGroup.tsx
> +    <Self orientation={orientation} gap={gap} justifyContent={justifyContent} alignItems={alignItems}>
수정했습니다 :D  
[045b0ff](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/045b0ff5cd3cd6ad8c87bbc77e94178e4f0310fb)

2022-10-08 01:46 UTC, airman5573 commented on frontend/src/components/button-group/ButtonGroup.tsx
> +import { CustomCSS } from '@styles/custom-css';
전반적으로 `import { type A, type B, C } from '...';`  
이런식으로 수정했습니다!!

[c0e181d](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/c0e181d6a3af743db5eb33c0fdb363a73011cef0)

2022-10-08 01:48 UTC, airman5573 commented on frontend/src/components/icons/crown-icon/CrownIcon.tsx
> +const CrownIcon: React.FC<CrownIconProps> = ({ custom }) => (
필요할때 하나씩 추가합시다!

2022-10-08 02:16 UTC, airman5573 commented on frontend/src/components/flex/Flex.tsx
> +  alignItems = 'flex-start',
맞네요!  
다만, 엄밀하게는 normal이 기본값이라고 합니다. [mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items#formal_definition)  

normal로 했을경우 replaced-absolutely-positioned box에서는 stretch가 아니라 start로 작동한다고 합니다.  
그래서 [간단한 실험](https://codepen.io/airman5573/pen/WNJaoMq)을 해봤습니다.  
하지만! 보시는 바와 같이 stretch 처럼 작동했어요.  

그래서 replaced-absolutely-positioned box가 뭔지 모르겠어서, [stackoverflow에 질문](https://stackoverflow.com/questions/73993931/what-is-replaced-absolutely-positioned-boxes-in-css)을 남겨놨습니다.  

결론 : 기본값이 normal이라고는 나와있지만, 아직 그 이유를 잘 모르는상태기 때문에 'stretch'로 합시다!

2022-10-08 02:24 UTC, airman5573 commented on frontend/src/components/flex/Flex.tsx
> +  return <div css={style}>{children}</div>;
네 맞습니다!

2022-10-08 02:26 UTC, airman5573 commented on frontend/src/components/center/Center.tsx
> +`;
Good!  
[af47939](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/af47939f4207a7296ae00107bfaee34c1acd3c6d)

2022-10-08 02:28 UTC, airman5573 commented on frontend/src/components/button/unstyled-button/UnstyledButton.tsx
> +  className?: string;
oops 안지웠네요!  
[e5c81b2](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/e5c81b21feebb36481441ce1c8263f62085a88e3)

2022-10-08 02:32 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +export const AllClearButton = styled(UnstyledButton)``;
Good ~ 

[a470018](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/a470018e58bdb42bafcc5f617d13e797f2f28b62)

2022-10-08 02:34 UTC, airman5573 commented on frontend/src/components/multi-tag-select/MultiTagSelect.tsx
> +  theme: Theme;
1. 결합도를 낮추기 위해 위에서 주입하는 방식을 선택했습니다.
그런데 조금 오버엔지니어링이라는 생각도 드네요. 왜냐면 SelectButton은 MultiTagSelect 안에서만 쓰이기 때문입니다.  

2. 위 커밋에서 fontSize를 'sm' 으로 받는식으로 개선했기 때문에 현재는 theme을 받지 않고 있습니다 :D

2022-10-08 03:04 UTC, airman5573 commented on frontend/src/components/wrapper/Wrapper.tsx
>  const Wrapper: React.FC<WrapperProps> = ({ children, space = '20px' }) => {
수정했습니다 :D  

[3a1c044](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/3a1c044ab44659bc777bfc1352e493170a9a23b2)

2022-10-08 03:05 UTC, airman5573 commented on frontend/src/layout/header/Header.tsx
> +`;
좋습니다 ~

2022-10-08 03:05 UTC, airman5573 commented on frontend/src/layout/header/Header.tsx
> +            >
맞습니다 :D

2022-10-08 03:07 UTC, airman5573 commented on frontend/src/layout/header/Header.tsx
> +          <Flex columnGap="16px" flexWrap="nowrap">
꼼꼼하시군요!  

수정했습니다 :D  
[fcb676c](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/fcb676ceb98394f20565868502db4e619201b8ff)

2022-10-08 03:13 UTC, airman5573 commented on frontend/src/components/user-info-item/UserInfoItem.tsx
> +      <Flex flexDirection="column" columnGap="2px">
맞네요!  
수정했습니다 :D  
[d66caf3](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/d66caf3b4c0483c93cace40e12e610b281b9d5cc)

2022-10-08 03:15 UTC, airman5573 commented on frontend/src/layout/header/components/logo/Logo.tsx
> +    <Flex justifyContent="center" alignItems="center" flexDirection="row">
수정했습니다 :D  
[e9328d8](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/e9328d844cc1805ce667c28dc5ec4e2615675fb4)

2022-10-08 03:55 UTC, airman5573 commented on frontend/src/pages/detail-page/components/study-member-card/StudyMemberCard.tsx
>    startDate = '2022.07.02',
수정했습니다 :D

2022-10-08 04:03 UTC, airman5573 commented on frontend/src/components/button/icon-button/IconButton.tsx
> +import { CustomCSS, resolveCustomCSS } from '@styles/custom-css';
수정했습니다 :D

2022-10-08 04:28 UTC, airman5573 commented on frontend/src/pages/main-page/components/filter-section/FilterSection.tsx
> +import FilterButtonList, { FilterButtonListProps } from '@main-page/components/filter-button-list/FilterButtonList';
수정했습니다 :D  
[06ef547](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/06ef547344732a2b0533c23c384cdc86a3702deb)

2022-10-08 04:30 UTC, airman5573 commented on frontend/src/pages/main-page/components/filter-section/FilterSection.tsx
> +const Self = styled.div`
수정했습니다 :D  
[c897882](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/c8978825852251098aabf5111d3116b6b886c49c)

2022-10-08 04:32 UTC, airman5573 commented on frontend/src/pages/main-page/components/filter-section/FilterSection.tsx
> +        <GenerationTags
Good ~  
[aa7a896](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/aa7a8969dcc239d7647913984477f7e0bece18eb)

2022-10-08 04:36 UTC, airman5573 commented on frontend/src/pages/main-page/components/filter-section/FilterSection.tsx
> +      <Filter ref={sliderRef}>
좋습니다 :D  

[7f581cf](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/7f581cff9e41570307cfe46623eb1f696f31b991)

2022-10-08 04:37 UTC, airman5573 commented on frontend/src/pages/main-page/components/filter-slide-button/FilterSlideButton.tsx
> +        transition: 'background-color 0.2s ease 0s',
Good ~  
[ab3ef69](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/ab3ef69397a9a3ed087bc8da804bd1b321ea4508)

2022-10-08 04:57 UTC, airman5573 commented on frontend/src/pages/main-page/MainPage.tsx
> +        {hasResult && (
어떤 식으로 조건문을 처리할지에 대한 논의가 먼저 필요하다고 생각해요.  

기존의 방식은  

```javascript
renderContent() {
  if (a) return <A />;

  if (b) return <B />;
}
```

이런 식이었는데, 이 코드 자체는 읽기가 편하지만 

아래쪽에서 
```jsx
<Container>
{renderContent()}
</Container>
```

이런 코드가 있을때 위로 다시 올라가는게 불편하더라구요,  
Context Switching 비용 + 응집성 저하!
위로 올라갔다가 다시 내려오면 흐름을 놓치게 되는 느낌이 있었어요.  

그래서!
이번에 리팩토링하면서 render~함수(이전방식) 를 빼고 선언적으로 jsx단에서 해결 했어요.   
```jsx
<Container>
  {a && <A />}
  {!a && b && <B />}
</Container>
```

지금 화면에 뭐가 그려질지 계산하는 일이 함수의 if문 보다는 더 복잡해 졌지만  
위로 올라갔다 계산하고 -> 다시 내려오는 비용 보다는 적다고 생각했어요.  
그리고 생각보다 디버깅 비용도 크지 않더라구요, 
```jsx
<Container>
  {a && <A />}
  {!a && b && <B />}
  {!a && !b && c && <C />}
  {!a && !b && !c && d && <D />}
  {!a && !b && !c && !d && e  && <E />}
</Container>
```
5가지 케이스가 있다 하더라도 각 컬럼에는 true인 경우가 1개만 있어야 하므로  
로직을 잘못 짰는지도 빠르게 검사할 수 있다고 생각해요.  

아무튼!  
이제 본론을 이야기 하자면,  
지금 경우에는 3항연산자를 써도 잘 읽히나, 일관적으로 위의 방식을 적용하고 싶네요!   

그래서 이번 케이스는  
```jsx
<PageWrapper>
  {isError && <Error />}
  {!isError && !hasResult && <NoResult />}
  {!isError && hasResult && (
    <InfinitScrollCardList
      isContentLoading={isFetching}
      onContentLoad={fetchNextPage}
      studies={searchedStudies}
    />
  )}
</PageWrapper>
```
이렇게 수정할 수 있을것 같아요.  

태태의 생각은 어떠 신가요 ?

2022-10-08 05:35 UTC, airman5573 commented on frontend/src/pages/my-study-page/MyStudyPage.tsx
> +import { StudyType, useMyStudyPage } from '@my-study-page/hooks/useMyStudyPage';
설명이 조금 복잡한데요,  
결론 먼저 말씀드리자면 StudyType이 아니라 StudyStatus로 네이밍을 고치겠습니다 :D  

## 상세 설명
1. StudyType은 '스터디의 유형'을 의미한거였습니다!  
2. 하지만, 네이밍이 잘못된건 사실입니다. 그래서 StudyStatus가 적절해 보입니다.
3. 그런데, StudyStatus가 이미 있었습니다. `type StudyStatus = 'PREPARE' | 'IN_PROGRESS' | 'DONE';`
4. 하지만! 지금 필요한건 PREPARE가 아니라 prepare입니다. 서버에서 PREPARE로 받았기 때문에 지금 상태의 StudyStatus는 저희가 원하는 형식과 달라 사용할 수 없습니다.  
5. 그래서! 서버에서 받아올때(`getMyStudies`) PREPARE -> prepare 로 바꾸고, StudyStatus = 'prepare' | 'inProgress' | 'done' 으로 바꾸는 방법이 생각났습니다.

어떻게 생각하시나요 ?

2022-10-08 05:38 UTC, airman5573 commented on frontend/src/pages/my-study-page/hooks/useMyStudyPage.ts
> +  const filteredStudies: Record<StudyType, Array<MyStudy>> = useMemo(() => {
`type StudyStatus = 'PREPARE' | 'IN_PROGRESS' | 'DONE';`
라서 객체의 key로는 쓰기가 어렵다고 생각했습니다.  

위의 코멘트를 확인해 주세요 :D

2022-10-08 05:42 UTC, airman5573 commented on frontend/src/pages/study-page/components/description-tab/DescriptionTab.stories.tsx
> +import DescriptionTab from '@pages/study-page/components/description-tab/DescriptionTab';
Good !  

[d8de231](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/d8de2318e2a4752ed48d814cd01114b5165c1650)

2022-10-08 05:44 UTC, airman5573 commented on frontend/src/pages/study-page/components/description-tab/DescriptionTab.tsx
> +import Textarea from '@components/textarea/Textarea';
좋은 생각입니다!  
다만, type을 import할때 한줄이 더 생기는게 조금 걱정되긴 하네요.  

```javascript
import { ButtonGroup } from '@components';
import { type ButtonGroupProps } from '@components/button-group/ButtonGroup';  
```

아니면 index파일에 type들도 re-export하는 방법도 있겠네요 :D  

같이 논의해 봅시다 ~

2022-10-08 05:45 UTC, airman5573 commented on frontend/src/pages/study-page/components/excerpt/Excerpt.tsx
> +  originalExcerpt?: StudyDetail['description'];
wow,,매의눈 태태!  
[3ce77e5](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/3ce77e5a232477e2dbc9c5916f1652cda2a4d31d)

2022-10-08 05:52 UTC, airman5573 commented on frontend/src/pages/study-page/components/excerpt/Excerpt.tsx
> +  <ImportedTextarea
Imported에 중독되었나봐요..  
수정했습니다 :D  

[45ead14](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/45ead14b5aff985a592273af70ddff7468c9bd60)

2022-10-08 05:58 UTC, airman5573 commented on frontend/src/pages/study-page/components/subject/Subject.tsx
> +    : [];
```typescript
let selectedOptions: Array<Option> = [];
if (originalOptions) {
  selectedOptions = originalOptions;
} else if (etcTag) {
  selectedOptions = [{ value: etcTag.id, label: etcTag.description }];
}
```
이 방식은 어떤가요?

2022-10-08 06:10 UTC, airman5573 commented on frontend/src/pages/study-page/components/subject/Subject.tsx
>        alert('기타 태그의 name이 변경되었습니다');
좋은 생각입니다 :D  

[907c13e](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/907c13e16d84a554c89b2ebe22ed1a05a502e2a8)  
[a10784d](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/a10784d3b9b8d8297d645068ef473a6beaec2734)

2022-10-08 06:12 UTC, airman5573 commented on frontend/src/pages/study-page/edit-study-page/EditStudyPage.tsx
> +import DescriptionTab from '@pages/study-page/components/description-tab/DescriptionTab';
좋은 생각입니다 :D  
다만, 폴더 구조를 같의 논의해보고 리팩토링 합시다!

2022-10-08 06:14 UTC, airman5573 commented on frontend/src/pages/study-room-page/StudyRoomPage.tsx
> +        <Flex.Item flexGrow={1}>
matarial ui를 보니까 as props를 받더라구요!  

예를들어서 `<Flex.Item as="section">` 이런식으로요.  

그나저나, section이 더 어울린다고 생각하신 이유는 무엇인가요?

2022-10-08 06:15 UTC, airman5573 commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/article-list/ArticleList.tsx
> +const NoArticle = () => <div>게시글이 없습니다</div>;
좋습니다!  
이 부분은 다음에 같이 디자인 하면서 생각해 보도록 합시다 :D

2022-10-08 06:18 UTC, airman5573 commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/edit/Edit.tsx
>  const Edit: React.FC<EditProps> = ({ studyId, articleId }) => {
좋은 생각입니다!  
다만 이번 PR은 컴포넌트 구조에 대한 컨벤션을 정립하는 내용이었기 때문에,  
같이 공통컴포넌트를 정의하고 그 다음에 개선합시다 :D

2022-10-08 06:21 UTC, airman5573 commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/edit/Edit.tsx
> +  theme: Theme;
맞습니다!

[4f56ad2](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/4f56ad2bbe0dabd46f5b701991c9cbad51c80404)

2022-10-08 06:23 UTC, airman5573 commented on frontend/src/pages/study-room-page/tabs/review-tab-panel/components/review-comment/ReviewComment.tsx
> +      {!isEditing && (
일관성을 위해서 body(컴포넌트의 jsx)에서는 가능한 삼항연산자를 피하려고 합니다!!  

(위의 코멘트에서 이야기 합시다 :D)

2022-10-08 06:40 UTC, airman5573 commented on frontend/src/pages/my-study-page/components/my-study-card-list-section/MyStudyCardListSection.tsx
> +        <Link to={PATH.STUDY_ROOM(study.id)}>
엇!  맞네요! 나의 실수..

수정했습니다 :D  
[46fd485](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/46fd485f462bd5746312dd30b787944dcc9d8b5c)

2022-10-08 06:42 UTC, airman5573 commented on frontend/src/pages/detail-page/components/study-wide-float-box/StudyWideFloatBox.tsx
> +  }
이 방식은 어떤가요 ? 

```typescript
<Card.Heading custom={{ fontSize: 'xl' }}>
  {isRegistered && <AlreadyRegistered />}
  {!isRegistered && !isOpen && <Closed />}
  {!isRegistered && isOpen && !enrollmentEndDate && <Open />}
  {!isRegistered && isOpen && enrollmentEndDate && (
    <EnrollmentEndDate theme={theme} enrollmentEndDate={enrollmentEndDate} />
  )}
</Card.Heading>
```

2022-10-08 06:43 UTC, airman5573 commented on frontend/src/pages/detail-page/components/study-member-section/StudyMemberSection.tsx
> +        {hasStudyMembers && (
일관성을 위해 && 로 처리 했습니다!   

삼항연산자가 더 나으려나요

2022-10-08 06:47 UTC, airman5573 commented on frontend/src/components/button/icon-button/IconButton.tsx
> +  custom?: CustomCSS<'width' | 'height' | 'fontSize' | 'borderRadius' | 'transition' | 'backgroundColor'>;
FilterSlideButton에서 transition을 사용하고 있습니다

2022-10-08 06:56 UTC, airman5573 commented
## 궁금한 점
import해도 되는데, useTheme을 사용하는 이유!
=> theme을 동적으로 변경하는 경우에 useTheme이 더 적절합니다!  re-rendering 될때 변경된 theme을 사용해야 하기 때문입니다.  

코멘트에도 달았는데, ThemeFontSize 타입을 살려서 CustomCSS 타입을 수정하면 어떨까요?
=> 좋은 생각입니다. 저도 코멘트에 달았습니다.

render~~ 함수들을 모두 JSX 내부에 작성하는 방식으로 바꾼 이유는 무엇인가요?
=> 함수로 갔다가 돌아오는 비용 + 안에 들어있는 내용물을 머릿속에 담아놔야 하는 비용을 고려했을때 JSX 내부에 작성하는편이 덜 피곤하다고 느꼈습니다. 코멘트에 상세한 내용 담았습니다! 

Wrapper 컴포넌트는 나중에 추가할 계획인가요?
=> 네 조금 더 논의해보고 추가합시다!  

혹시 모르니 tsc와 eslint, prettier도 돌려주시고 import 할 때 타입인데 type을 빼먹은 게 없나 확인해주세요! 꽤 있습니다(Theme, CSSCustom 등등)!!
=> 알겠습니다!  (done)

## 소감
디자인 규칙 적용한 코드를 보고 든 생각!

확실히 파일 길이가 길다. 윗부분만 보면 깔끔한데, 아래로 내리는 순간 복잡하다는 느낌!
=> 맞아요, 아래가 좀 길죠.

위와 같은 이유로 Wrapper 컴포넌트를 얼른 만들어야 겠다. 
=> 엄밀히는 Wrapper의 유무 보다는 한번 감싸서 의미를 부여했기 때문에 아래가 길어졌다고 생각해요.  
메인 컴포넌트에서 이거를 촤라락 풀어서 보여주는편이 나을지, 아니면 기능/의미 단위로 한번더 아래쪽에서 묶는편이 나을지  
다시 고민해 봅시다 :D  

export default 아랫단에 스타일 컴포넌트, 그냥 이름만 바꾼 컴포넌트, 추가 스타일을 준 컴포넌트가 섞여 있어서 일관성이 부족해보인다.
=> 그러네요! 말씀하신대로 이 부분은 Wrapper로 해결할 수 있을듯 싶어요 :D

새로운 기능을 추가하면서 컴포넌트를 만들 때 어려울 것 같다! 
=> 스타일링 할때 이리갔다 저리갔다 해야되서 귀찮아 질듯 싶네요.  아니면 만들때는 한쪽에서 와다다다 만들고, 잘 돌아가면 그때 아래쪽으로 빼는것도 방법일듯 싶네요!  

구현 후 규칙에 맞춰 리팩토링하는 과정이 불가피해 보인다. 

최대한 기존 컴포넌트 활용하는 방향으로 가고, 공통 컴포넌트를 더 추가하자!
=> 좋은 생각입니다.  

컴포넌트로 분리하지 않았다면 추가할 필요가 없는 prop과 type을 추가로 선언하다보니 코드가 두배가 된 것 같다. 다른 방법은 없을까..?
=> 아 맞아요,,,prop, type 추가로 선언하는것도 코드가 길어지는데 한몫 하죠. 두뇌 풀가동 해서 해결해 봅시다.

2022-10-10 09:12 UTC, nan-noo requested changes

2022-10-10 09:12 UTC, nan-noo commented on frontend/src/pages/study-room-page/StudyRoomPage.tsx
> +        <Flex.Item flexGrow={1}>
Outlet 부분이 스터디 방 페이지의 메인 내용 'section'이기 때문입니다. Flex.Item은 단순 div로 되어 있어서 아무 의미도 없지만요ㅎㅎ 좀 더 semantic 태그를 활용하면 좋겠다고 생각했습니다 :D

2022-10-10 09:12 UTC, nan-noo commented on frontend/src/styles/custom-css.ts
> +type PickAllowedCSSKeyValue<AllowedCSSKeys extends AllCSSKeys> = {
KeyValue 대신에 Object를 사용해주세요 :D

2022-10-10 09:12 UTC, nan-noo commented on frontend/src/utils/isThemeFontSize.ts
> +};
```suggestion
const isThemeFontSize = (fontSize: unknown): fontSize is ThemeFontSize => isString(fontSize) && hasOwnProperty(theme.fontSize, fontSize)
```

2022-10-10 09:20 UTC, nan-noo commented on frontend/src/components/button-group/ButtonGroup.tsx
> +import { CustomCSS } from '@styles/custom-css';
코멘트에도 달았지만, custom-types에서 import하는 것은 모두 타입이기 때문에 굳이 바꾸지 않아도 될 것 같습니다! 일관성은 있지만 오히려 코드가 늘어나서 나중에 또 빼먹는 일이 많이 생길 것 같네요

2022-10-10 09:26 UTC, nan-noo commented on frontend/src/components/button/icon-button/IconButton.tsx
> +  custom?: CustomCSS<'width' | 'height' | 'fontSize' | 'borderRadius' | 'transition' | 'backgroundColor'>;
제가 기억하기론 IconButton에 기본 transition 스타일이 주어져 있어서 필요 없던 것 같은데 다시 확인해주세요!

2022-10-10 09:28 UTC, nan-noo commented on frontend/src/pages/detail-page/components/study-wide-float-box/StudyWideFloatBox.tsx
> +  }
코멘트에도 남겼지만 좀 복잡해보입니다!

2022-10-10 09:42 UTC, nan-noo commented on frontend/src/pages/main-page/MainPage.tsx
> +        {hasResult && (
> 위로 올라갔다 계산하고 -> 다시 내려오는 비용 보다는 적다고 생각했어요.

저는 이 비용이 발생하지 않는다고 생각합니다! 왜냐하면 저희가 지금 render~ 함수로 분리한 부분은 state, props에 따라 변하는 부분이고, 분리하지 않은 부분은 정적인 레이아웃(주로 -Container, -Wrapper)이기 때문입니다. 저희가 디버깅하거나 로직을 수정할 때는 주로 동적인 부분을 보고 정적인 부분은 보지 않습니다!
부모 요소에 영향받는 스타일을 수정할 때 말고는 '왔다 갔다 이동이 불편하다'라는 생각이 들지 않았는데, 병민은 어떤 상황에서 그런 불편함이 있었나요??

> 지금 화면에 뭐가 그려질지 계산하는 일이 함수의 if문 보다는 더 복잡해 졌지만

전 오히려 이 비용이 더 크다고 생각합니다. 
`{!a && !b && c && <C />}` -> 어떤 상황인지 한눈에 알기가 어려워요 ㅠㅠ

2022-10-10 09:54 UTC, nan-noo commented on frontend/src/pages/my-study-page/MyStudyPage.tsx
> +  <MyStudyCardListSection sectionTitle="종료했어요" done={true} studies={studies.done} />
조금 과도하게 분리된 감이 있습니다! 한 줄을 분리하기 위해 코드양이 훨씬 많아졌어요. 
MyStudyCardListSection이 이미 분리된 컴포넌트인데 추가적인 스타일이 없음에도 또 분리하니까 코드가 많이 길어졌네요!

2022-10-10 10:01 UTC, nan-noo commented on frontend/src/pages/my-study-page/MyStudyPage.tsx
> +import { StudyType, useMyStudyPage } from '@my-study-page/hooks/useMyStudyPage';
음 그건 괜찮습니다. ~~그런데 왜 대문자 말고 소문자가 필요한가요?~~
`studies={studies.inProgress} ` 이것들 때문이군요!
그러면 일단은 소문자 타입을 따로 만들고 응답값 수정은 따로 합시다!

2022-10-10 10:02 UTC, nan-noo commented on frontend/src/pages/study-page/components/subject/Subject.tsx
> +    : [];
코멘트 남겼습니다

2022-10-10 10:04 UTC, nan-noo commented
빌드 에러나는데 수정해주세요!

2022-10-10 12:23 UTC, nan-noo commented on frontend/src/pages/my-study-page/MyStudyPage.tsx
> +  <MyStudyCardListSection sectionTitle="종료했어요" done={true} studies={studies.done} />
```suggestion
const InProgressStudyList: React.FC<InProgressStudyListProps> = ({ studies }) => (
  <MyStudyCardListSection sectionTitle="활동 중!" studies={studies.inProgress} />
);

type PrepareStudyListProps = InProgressStudyListProps;
const PrepareStudyList: React.FC<PrepareStudyListProps> = ({ studies }) => (
  <MyStudyCardListSection sectionTitle="곧 시작해요!" studies={studies.prepare} />
);

type DoneStudyListProps = InProgressStudyListProps;
const DoneStudyList: React.FC<DoneStudyListProps> = ({ studies }) => (
  <MyStudyCardListSection sectionTitle="종료했어요" done studies={studies.done} />
```

2022-10-10 13:32 UTC, airman5573 commented on frontend/src/api/community/index.ts
> +import { type ArticleId, type CommunityArticle, type Page, type Size, type StudyId } from '@custom-types';
수정했습니다 :D  
[5d6fc93](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/5d6fc93511b8db201f7823ee7d5ba8a99a50ec04)

2022-10-10 13:42 UTC, airman5573 commented on frontend/src/pages/study-page/components/subject/Subject.tsx
> +  }
오 확실히 짧아졌네요!  
다만 이렇게 되면 위와 아래쪽에 의존성을 가지게 되서 코드가 조금 더 복잡하지 않나 싶습니다.  
위 코드가 정상 작동하는지 알려면, etcTag가 undefined가 된다는점 + MultiTagSelect의 defaultSelectedOptions에 undefined가 들어왔을때 기본으로 배열을 사용한다는점. 이 두가지를 알고 있어야 etcTag && 으로 해도 괜찮다는걸 알 수 있기 때문에 조금 더 복잡하다고 생각합니다.  
그래서 

`const selectedOptions = originalOptions ?? (etcTag ? [{ value: etcTag.id, label: etcTag.description }] : []);`

2022-10-10 13:50 UTC, airman5573 commented on frontend/src/pages/study-page/components/subject/Subject.tsx
> +          <MultiTagSelect defaultSelectedOptions={selectedOptions} options={options} {...register(SUBJECT)} />
음 저도 고민을 해봤는데요  

```typescript
const noTags = isSuccess && !hasTags;
const hasEtcTagError = isSuccess && hasTags && !etcTag;
const noError = isSuccess && hasTags && etcTag;
```

2022-10-10 13:57 UTC, airman5573 commented on frontend/src/styles/custom-css.ts
> +type PickAllowedCSSKeyValue<AllowedCSSKeys extends AllCSSKeys> = {
수정했습니다 :D  

[ac6fe5f](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/ac6fe5f9384a433f191bf3b4efd6b99a32da6b7f)

2022-10-10 13:57 UTC, airman5573 commented on frontend/src/utils/isThemeFontSize.ts
> +};
oh good

2022-10-10 14:02 UTC, airman5573 commented on frontend/src/pages/my-study-page/MyStudyPage.tsx
> +  <MyStudyCardListSection sectionTitle="종료했어요" done={true} studies={studies.done} />
수정했습니다 :D  
[2352ee3](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/2352ee3e8abc5378609e61cec08ba51184bfe729)

2022-10-16 09:11 UTC, nan-noo approved these changes
몇가지 코멘트 남겼습니다!

충돌 해결하고 dev server api와 연결해서 버그 없는지 테스트한 후에 머지하면 될 것 같습니다 :D

추가적으로 이야기 나온 컴포넌트 규칙은 나중에 다시 수정합시다!

2022-10-16 09:11 UTC, nan-noo commented on frontend/src/pages/detail-page/components/study-wide-float-box/StudyWideFloatBox.tsx
> +  const isOpen = recruitmentStatus === RECRUITMENT_STATUS.START;
위 코멘트와 마찬가지입니다!

2022-10-16 09:11 UTC, nan-noo commented on frontend/src/pages/study-page/components/category/Category.tsx
> +const GENERATION = 'generation';
이건 왜 상수를 사용안 했나요??

2022-10-16 09:11 UTC, nan-noo commented on frontend/src/utils/dates.ts
>  import { DateYMD } from '@custom-types';
```suggestion
import type { DateYMD } from '@custom-types';
```

2022-10-16 09:28 UTC, nan-noo commented on frontend/src/components/@shared/icons/login-icon/LoginIcon.stories.tsx
```suggestion
import { LoginIcon } from '@shared/icons';

```

2022-10-16 09:28 UTC, nan-noo commented on frontend/src/components/@shared/icons/logout-icon/LogoutIcon.stories.tsx
위 코멘트와 동일합니다

2022-10-16 09:28 UTC, nan-noo commented on frontend/src/layout/header/Header.tsx
> +import UserDropDown from '@layout/header/components/user-dropdown/UserDropdown';
이 컴포넌트들이 2군이라 판단한 이유가 뭔가요??

저는 만약 헤더를 나눈다면
로고 / 서치바 / navigation 섹션 으로 2군을 나눌 것 같아요!

2022-10-16 09:28 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/edit-title/EditTitle.tsx
>  export default EditTitle;
return 바로 아래로 옮깁시다 :D

2022-10-16 17:10 UTC, airman5573 commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/edit-title/EditTitle.tsx
>  export default EditTitle;
전반적으로 수정했습니다 :D  
[5546e26](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/5546e2666004a81e0196af0a5d0eb7a441a34148)

2022-10-16 17:10 UTC, airman5573 commented on frontend/src/layout/header/Header.tsx
> +import UserDropDown from '@layout/header/components/user-dropdown/UserDropdown';
좋은 생각입니다 :D  

[7662dc6](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/7662dc61d358bf244f2415f76a513262327ea1f0)

2022-10-16 17:11 UTC, airman5573 commented on frontend/src/components/@shared/icons/logout-icon/LogoutIcon.stories.tsx
전반적으로 수정했습니다 :D  

[277a770](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/277a770fdfbe00c4636e042d8a11a251b5cd7e6f)

2022-10-16 17:11 UTC, airman5573 commented on frontend/src/utils/dates.ts
>  import { DateYMD } from '@custom-types';
수정했습니다 :D  

[2607c2f](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/2607c2f01ba253ed61d89786c3058f636209f634)

2022-10-16 17:12 UTC, airman5573 commented on frontend/src/pages/study-page/components/category/Category.tsx
> +const GENERATION = 'generation';
상수로 변경했습니다 :D  

[4f9301f](https://github.com/woowacourse-teams/2022-moamoa/pull/393/commits/4f9301f05f16d6dc0946582fefd6ffb52ac762b9)

2022-10-16 17:13 UTC, airman5573 commented on frontend/src/pages/detail-page/components/study-float-box/StudyFloatBox.tsx
> +  const isRegistered = userRole === USER_ROLE.MEMBER || userRole === USER_ROLE.OWNER;
전반적으로 useUserRole을 사용했습니다 :D

2022-10-17 05:29 UTC, nan-noo requested changes

2022-10-17 05:29 UTC, nan-noo commented on frontend/src/components/@shared/multi-tag-select/MultiTagSelect.tsx
>  `;
```ts
const SelectControl = styled.div<{ invalid: boolean }>`
  ${({ theme, invalid }) => css`
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    align-items: center;

    position: relative;
    padding-right: 8px;
    min-height: 38px;

    border: 1px solid ${theme.colors.secondary.base};
    background-color: ${theme.colors.secondary.light};
    border-radius: ${theme.radius.sm};

    ${invalid &&
    css`
      border: 1px solid ${theme.colors.red};

      &:focus {
        border: 1px solid ${theme.colors.red};
      }
    `}
  `}
`;
```

2022-10-17 05:29 UTC, nan-noo commented on frontend/src/pages/detail-page/DetailPage.tsx
> +MarkdownRender;
오.. 이거 지워주세요!

2022-10-17 05:29 UTC, nan-noo commented on frontend/src/pages/detail-page/components/study-wide-float-box/StudyWideFloatBox.tsx
> +        {isRegistered ? (
isOwnerOrMember를 그대로 써도 될 것 같습니다!

2022-10-17 05:29 UTC, nan-noo commented on frontend/src/pages/study-page/components/subject/Subject.tsx
> +            if (data.tags.length === 0) return <NoTags />;
if(isError || !isSuccess) return <Error />;로 하면 되지 않을까요??

2022-10-17 05:29 UTC, nan-noo commented on frontend/src/pages/study-page/create-study-page/hooks/useCreateStudyPage.ts
>      const tagIds = [
그냥 서버에서 에러 응답을 주는 게 낫지 않을까요??

2022-10-17 05:29 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/CommunityTabPanel.tsx
> +  // @TODO: studyId가 없는 경우는 어떻게 처리할것인가?
스터디 아이디가 없는 경우 홈으로 리다이렉트 시켜야 겠네요!
로그인 리다이렉트 페이지처럼

2022-10-17 05:29 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/article-list/ArticleList.tsx
> +import { ApiCommunityArticles, useGetCommunityArticles } from '@api/community';
```suggestion
import { type ApiCommunityArticles, useGetCommunityArticles } from '@api/community';
```

2022-10-17 05:29 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/edit-content/EditContent.tsx
> +
지워주세요!

2022-10-17 05:29 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/link-room-tab-panel/LinkRoomTabPanel.tsx
> +      {/* owner 혹은 member만 링크를 추가할 수 있을것 같은데, 확실하지는 않음 */}
오 왜인가요??

2022-10-17 05:29 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/link-room-tab-panel/hooks/useLinkRoomTabPanel.ts
> +  const studyId = Number(_studyId);
얘도 스터디 아이디가 있는지 확인해야겠군요

2022-10-17 05:29 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/notice-tab-panel/NoticeTabPanel.tsx
> +  const { isOwner } = useUserRole({ studyId }); // @TODO: 객체로 받을 필요가 있나?
isOwner를 props로 받고 있어서 내부에서 useUserRole을 할 필요가 없을 것 같아요!

2022-10-17 05:33 UTC, nan-noo commented
위에것만 수정되면 바로 머지하겠습니다!

2022-10-17 08:07 UTC, airman5573 commented on frontend/src/pages/study-room-page/tabs/link-room-tab-panel/LinkRoomTabPanel.tsx
> +      {/* owner 혹은 member만 링크를 추가할 수 있을것 같은데, 확실하지는 않음 */}
머지하다가 지워진것 같아요.  수정했습니다 :D

2022-10-17 08:26 UTC, airman5573 commented on frontend/src/pages/study-page/components/subject/Subject.tsx
> +            if (data.tags.length === 0) return <NoTags />;
다음에 tans-query로 바꿉시다!

2022-10-17 08:26 UTC, airman5573 commented on frontend/src/pages/study-page/create-study-page/hooks/useCreateStudyPage.ts
>      const tagIds = [
좋습니다 :D

2022-10-17 08:28 UTC, airman5573 commented on frontend/src/components/@shared/multi-tag-select/MultiTagSelect.tsx
>  `;
감사합니당 :D

2022-10-18 01:15 UTC, nan-noo commented
https://stackoverflow.com/questions/64644625/cypress-typeerror-cannot-read-property-keyboardevent-of-undefined-cypress

cypress 재설치하고 올려주세요!

2022-10-18 01:29 UTC, nan-noo commented
develop 브랜치 frontend.yml도 업데이트했으니 pull해주세요!

2022-10-18 01:31 UTC, nan-noo approved these changes

2022-10-18 02:03 UTC, merged