[FE] issue387: 서버 응답 런타임에 타입 확인
woowacourse-teams/2022-moamoa pull request #401
Opened 2022-10-07 04:58 UTC by nan-noo

## 요약
서버 응답이 타입대로 오지 않을 때 런타임 에러가 발생해서 화면이 하얗게 변하는 문제 
-> axios api 응답값 반환 전에 타입을 체크해서 응답값이 제대로 오지 않을 시 처리를 통해 하얗게 변하는 것을 방지했습니다.

## 세부사항
api 폴더의 각 도메인마다 typeChecker.ts 파일을 추가했습니다.

### 예시
```ts
// api 파일 - index.ts
export const postLogin = async ({ code }: ApiLogin['post']['variables']) => {
  const response = await axiosInstance.post<
    ApiLogin['post']['responseData'],
    AxiosResponse<ApiLogin['post']['responseData']>,
    ApiLogin['post']['variables']
  >(`/api/auth/login?code=${code}`);

// type check 추가
  return checkLogin(response.data);
};
```
```ts
// type checker 파일 - typeChecker.ts
type LoginKeys = keyof ApiLogin['post']['responseData'];

export const checkLogin = (data: unknown): ApiRefreshToken['get']['responseData'] => {
  if (!isObject(data)) throw new AxiosError(`Token does not have correct type: object`);

  const keys: Array<LoginKeys> = ['accessToken', 'expiredTime'];
  if (!hasOwnProperties(data, keys)) throw new AxiosError('StudyReviews does not have some properties');

  return {
    accessToken: checkType(data.accessToken, isString),
    expiredTime: checkType(data.expiredTime, isNumber),
  };
};
```

```ts
// utils/typeChecker.ts
export const isNull = (value: unknown): value is null => value === null;

export const isNullOrUndefined = (value: unknown): value is null | undefined => value === undefined || value === null;

export const isBoolean = (value: unknown): value is boolean => typeof value === 'boolean';

...

// isNull, isNumber등의 조건 함수 참/거짓 반환값에 따라 value를 return하는 함수
const checkType = <T>(value: unknown, isTypeFn: (value: unknown) => value is T): T => {
  if (!isTypeFn(value)) {
    console.error(`${isTypeFn} ${value} does not have correct type`);
    throw new AxiosError(`${value} does not have correct type`);
  }

  return value;
};

export default checkType;
```

close #387

2022-10-08 12:40 UTC, airman5573 requested changes
태태 코드 짜느라 수고하셨어요.  
리뷰 확인해주세요 :D

2022-10-08 12:40 UTC, airman5573 commented on frontend/src/mocks/handlers/detailStudyHandlers.ts
> +        recruitmentStatus: 'RECRUITMENT_START',
이 친구도 상수로 부탁해요!

2022-10-10 05:53 UTC, nan-noo commented on frontend/src/api/my-study/typeChecker.ts
> +type TagKeys = keyof Pick<Tag, 'id' | 'name'>;
api my study 에 같이 오는 tag는 api tag와 다르게 'id'와 'name' 속성만 가지고 있습니다. 
두 api 도메인이 서로 의존성이 없고, 이 checkTag 함수는 my study에 종속되어 있다고 판단해 따로 만들었습니다.
(따라서 이 파일에 있는 checkTag는 export하지 않습니다.)

네이밍이 혼동될 여지가 있다고 봐서 checkTag -> checkMyStudyTag로 변경했습니다.

2022-10-10 05:59 UTC, nan-noo commented on frontend/src/api/my-study/typeChecker.ts
> +const checkTag = (data: unknown): Pick<Tag, 'id' | 'name'> => {
```ts
type MyStudyTag = Pick<Tag, 'id' | 'name'>;
type MyStudyTagKeys = keyof MyStudyTag;

const checkMyStudyTag = (data: unknown): MyStudyTag => {
...
```

위와 같이 수정했습니다 :D

2022-10-10 06:24 UTC, nan-noo commented on frontend/src/api/study/typeChecker.ts
> +    maxMemberCount: checkOptionalType(data.maxMemberCount, isNumber),
checkOptionalType 함수는 api 응답으로 null이 올 수 있는 속성에 대해 옵셔널(\<valuetype\> | \<undefined\>)로 return합니다.
```ts
<T>(value: unknown, isTypeFn: (value: unknown) => value is T): T | undefined
```

그런데 제안하신 함수는 null인지 확인하고 null을 return하는 함수라 목적이 다른 것 같습니다.

~~전에도 말했다시피 checkType에 isOptional 플래그 파라미터를 추가해서 checkOptionalType 기능을 구현할 수 있지만, isOptional이 true인지 false인지 조건에 따라 return 타입을 주기 어려워서 checkType과 checkOptionalType을 분리한 것입니다!~~
-> 함수 오버로딩을 이용해서 optional도 하나의 함수로 합쳤습니다 :D 

```ts
function checkType<T>(value: unknown, isTypeFn: (value: unknown) => value is T, isOptional: true): T | undefined;
function checkType<T>(value: unknown, isTypeFn: (value: unknown) => value is T, isOptional?: false): T;
function checkType<T>(value: unknown, isTypeFn: (value: unknown) => value is T, isOptional?: boolean): T | undefined {
  if (isOptional) {
    if (!isTypeFn(value) && !isNullOrUndefined(value)) {
      console.error(`${isTypeFn} ${value} does not have correct type`);
      throw new Error(`${value} does not have correct type`);
    }

    return value ?? undefined;
  }

  if (!isTypeFn(value)) {
    console.error(`${isTypeFn} ${value} does not have correct type`);
    throw new Error(`${value} does not have correct type`);
  }

  return value;
}

export default checkType;
```

제안한 방법에 따라 여러 함수를 받을 수 있게 확장하는 게 좋아보입니다!

2022-10-10 07:14 UTC, nan-noo commented on frontend/src/api/study/typeChecker.ts
> +    maxMemberCount: checkOptionalType(data.maxMemberCount, isNumber),
그런데 아직까지는 여러 타입을 받을 필요가 없어서 필요해지면 추후에 수정하는 게 좋을 것 같습니다!

함수 오버로딩을 활용하면 가능할 것 같습니다 :D

2022-10-10 07:31 UTC, airman5573 commented on frontend/src/api/my-study/typeChecker.ts
> +type TagKeys = keyof Pick<Tag, 'id' | 'name'>;
그래서 export 하지 않았군요. 이해했습니다 👍

2022-10-10 10:23 UTC, nan-noo commented on frontend/src/api/link-preview/typeChecker.ts
> +    title: checkType(data.title, isStringOrNull),
https://github.com/woowacourse-teams/2022-moamoa/pull/401#discussion_r990968601

2022-10-10 13:15 UTC, merged