[BE] issue 343: 게시판 댓글 기능
woowacourse-teams/2022-moamoa pull request #406
Opened 2022-10-10 12:23 UTC by tco0427

## 요약

게시판에 댓글 기능을 추가한다.
공지사항에 댓글 기능을 추가한다.

## 세부사항

- 게시판 및 공지사항에 스터디원은 댓글을 달 수 있다.
  - 스터디를 탈퇴한 회원은 공지사항 및 게시판에 자신이 달았던 댓글을 수정 및 삭제할 수 없다.
- 댓글을 페이징 처리하여 조회할 수 있다.
- 자신이 작성한 댓글은 수정이 가능하다. (스터디 가입 동안)
- 자신이 작성한 댓글은 삭제가 가능하다. (스터디 가입 동안)

close #343

2022-10-17 08:00 UTC, jaejae-yoo requested changes
디우 구현 양이 많아서 고생하셨겠네요..! 고생하셨습니다. 👍
몇 가지 리뷰 확인 부탁드려요 ~ 🙌

2022-10-17 08:00 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/comment/controller/CommentController.java
> +    @GetMapping
`("/{comment-id}")` 요거 없어도 되나용??

URI.create("/api/studies/" + studyId + "/" + type + "/" + articleId + "/comments/" + commentId); 

위에 리다이렉트 URI가 어디로 가는지 궁금해요!

2022-10-17 08:00 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/comment/domain/AssociatedCommunity.java
> +public class AssociatedCommunity {
요 친구는 어디서 쓰이고 있나요 ??

2022-10-17 08:00 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/comment/domain/Comment.java
> +    @ManyToOne(fetch = EAGER)
EAGER로 설정한 이유가 궁금해요! :D

2022-10-17 08:00 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/comment/domain/Comment.java
> +        if (!isAuthor(author) || !isSigningUp(studyId, author)) {
`isSigningUp()`도 함께 확인해줘야 하는 이유가 궁금해요!

2022-10-17 08:00 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/comment/domain/Comment.java
> +        if (!isAuthor(author) || !isSigningUp(studyId, author)) {
`checkDeletePermission` 메서드를 이름을 변경하고 같이 쓰는 것은 어떨까요 ?

2022-10-17 08:00 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/comment/service/CommentService.java
> +        comment.checkDeletePermission(studyId, new Author(memberId));
이 부분을 Comment 내부에서 생성될 때 체크하는 것은 어떨까요?

2022-10-17 08:00 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/comment/service/response/CommentsResponse.java
> +@NoArgsConstructor
`(access = AccessLevel.PRIVATE)` 👀

2022-10-17 08:00 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/comment/service/response/CommentsResponse.java
> +    List<CommentResponse> comments;
`private` 👀

2022-10-17 08:00 UTC, jaejae-yoo commented on backend/src/main/resources/schema.sql
> +    last_modified_date DATETIME     NOT NULL,
편-안 👍

2022-10-17 09:02 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/comment/controller/CommentController.java
> +    @GetMapping
생성된 자원의 id 를 front에 넘겨주기 위한 용도로 추가해주었었어요!!
이 부분은 프론트 팀원과 상의해보고 만약 필요없다고 하면 제거해도 충분할 것 같아요!!
조회시에는 단건 조회가 없어서 "/{comment-id}" 가 필요 없을 것 같습니다!!

2022-10-17 09:07 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/comment/domain/AssociatedCommunity.java
> +public class AssociatedCommunity {
와우와우 안쓰이고 있었네요..!! 제거하도록 하겠습니다!

2022-10-18 04:13 UTC, sc0116 requested changes
디우 잘 구현해주셨는데요. 몇가지 궁금한점 적어봤어요!

2022-10-18 04:13 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/moamoa/comment/domain/CommentTest.java
> +class CommentTest {
단위 테스트에서 예외 부분도 테스트하면 좋을 것 같네요!

2022-10-18 07:42 UTC, sc0116 requested changes

2022-10-18 07:42 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/comment/controller/CommentController.java
> +                .header("Access-Control-Allow-Headers", LOCATION)
제거예정

2022-10-18 07:42 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/comment/domain/Comment.java
> +    }
베루스: 불필요한 메서드 추출

2022-10-18 07:42 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/comment/domain/repository/JpaCommentRepository.java
> +public interface JpaCommentRepository  extends JpaRepository<Comment, Long>, CommentRepository {
default로 변경하여 외부에서 접근할 수 없도록 수정

2022-10-18 07:42 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/comment/service/CommentService.java
> +        final Comment comment = article.writeComment(new Accessor(memberId, studyId), request.getContent());
정적 팩토리 메서드 사용

2022-10-18 07:42 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/studyroom/domain/article/Article.java
> +        if (studyRoom.isPermittedAccessor(accessor)) {
isSigningUp 쓰기 && 메서드명 수정

2022-10-18 07:42 UTC, sc0116 commented on backend/src/test/java/com/woowacourse/acceptance/test/comment/CommunityCommentAcceptanceTest.java
> +        final Long 댓글_내용3_ID = 디우가().로그인하고().스터디에(자바_스터디).댓글을_작성한다(COMMUNITY, 자바_게시글, "댓글 내용3");
다른 게시물의 댓글 작성 후 해당 게시물의 댓글만 조회하는지 확인해봅시당

2022-10-19 12:02 UTC, merged