[FE] issue431: 게시글에 댓글 기능 추가
woowacourse-teams/2022-moamoa pull request #449
Opened 2022-10-21 02:19 UTC by airman5573

## 요약
게시글에 댓글 기능을 추가합니다

close #431

2022-10-24 06:48 UTC, nan-noo requested changes
코멘트 남겼습니다!

2022-10-24 06:48 UTC, nan-noo commented on frontend/src/pages/study-room-page/components/comment-edit-form/CommentEditForm.tsx
> +export default Object.assign(CommentEditForm, { CommentEditField });
이렇게 하면 CommentEditField가 옵셔널처럼 느껴져요!

2022-10-24 06:48 UTC, nan-noo commented on frontend/src/pages/study-room-page/components/comment-edit-form/CommentEditForm.tsx
> +export default Object.assign(CommentEditForm, { CommentEditField });
그리고 export default 위로 올려주세요!

2022-10-24 06:48 UTC, nan-noo commented on frontend/src/pages/study-room-page/components/comment-edit-form/CommentEditForm.tsx
> +        {renderField(setCount)}
이 부분에 아래 textarea가 들어가는 거군요

onSubmit을 실행하기 전에 setCount를 초기화하는 방법은 안 될까요??

뭔가 계속 생각하다보니까 비제어 컴포넌트가 좋은지 잘 모르겠네요..! 예외처리 하는 것도 복잡하고, 맘대로 초기화하거나 값을 바꿀수도 없고 항상 접근해서 값을 가져와야하고..
제어 컴포넌트로 했으면 submit할 때 모든 value state를 초기화하면 되니까 letterCounter도 자동으로 초기화됐을 것 같은데(count로 value.length를 넘겨주면 되니까) 어떻게 생각하시나요??

폼을 사용할수록 제어 컴포넌트가 관리하기 쉬운 것 같다는 생각이 드네요!

2022-10-24 06:48 UTC, nan-noo commented on frontend/src/pages/study-room-page/components/comment-form/CommentForm.tsx
> +export default Object.assign(CommentForm, { CommentField });
위로 올려주세요!

2022-10-24 06:48 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/comment-edit-form/CommentEditForm.tsx
> +const CommentEditForm: React.FC<CommentEditFormProps> = ({
이름을 바꾸는 건 어떨까요?

CommunityCommentEditForm

2022-10-24 06:48 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/comment-list/CommentList.tsx
> +// 그냥 useGetCommunityComments를 두번 호출하는건 별로인가?
저는 ~~리스트 컴포넌트는 리스트를 받아서 렌더링만 해주는 게 좋다고 생각합니다 :D

2022-10-24 06:48 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/comment-list/CommentList.tsx
> +const Self = styled.div``;
아무 스타일도 없을 때는 그냥 div를 직접 넣어줘도 좋을 것 같아요!

2022-10-24 06:48 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/edit-content/EditContent.tsx
> +export default EditContent;
올려주세요!

2022-10-24 06:48 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/edit/Edit.tsx
> +  ) => {
```suggestion
const handleSubmit: HandleEditFormSubmit = async (_, submitResult) => {
```

2022-10-24 06:48 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/editable-comment/EditableComment.tsx
> +import Comment, { CommentProps } from '@study-room-page/components/comment/Comment';
```suggestion
import type { ArticleId, ReviewId, StudyId } from '@custom-types';

import { QK_COMMUNITY_COMMENTS_INFINITE_SCROLL, useDeleteCommunityComment } from '@api/community/comment';

import Comment, { type CommentProps } from '@study-room-page/components/comment/Comment';
```

2022-10-24 06:48 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/review-tab-panel/components/reivew-form/ReviewForm.tsx
> +        }}
children으로 받으면 안 될까요??

renderField를 써야 하는 이유가 무엇인가요?

2022-10-27 15:36 UTC, airman5573 commented on frontend/src/pages/study-room-page/components/comment-edit-form/CommentEditForm.tsx
> +  onSubmit,
수정했습니다!  
[5f296a9](https://github.com/woowacourse-teams/2022-moamoa/pull/449/commits/5f296a93da57fb5f7607106ee2e8b85db55ea2e2)

2022-10-27 15:59 UTC, airman5573 commented on frontend/src/api/community/comment/index.ts
> +  };
좋은생각입니다! 👍

2022-10-27 16:34 UTC, airman5573 commented on frontend/src/api/reviews/index.ts
> +    return { ...response.data, page: pageParam.page };
수정했습니다!  
[939c4cd](https://github.com/woowacourse-teams/2022-moamoa/pull/449/commits/939c4cdcec11147e6d030a56aee9cdaaf970b300)

2022-10-27 16:37 UTC, airman5573 commented on frontend/src/api/community/comment/typeChecker.ts
> +export const checkCommunityComment = (data: unknown): CommunityComment => {
오,, 꼼꼼하시군요!  
[445b92f](https://github.com/woowacourse-teams/2022-moamoa/pull/449/commits/445b92f8e9be751d6d21f90e885ff6c61bc756dc)

2022-10-27 16:49 UTC, airman5573 commented on frontend/src/api/community/comment/typeChecker.ts
> +export const checkCommunityComment = (data: unknown): CommunityComment => {
꼼꼼하시군요!  
밑에 내용대로 파일을 분리하면서 export는 남겨 두었습니다 :D

2022-10-27 16:49 UTC, airman5573 commented on frontend/src/api/community/comment/typeChecker.ts
> +// comments
좋은 생각입니다 👍

2022-10-27 16:51 UTC, airman5573 commented on frontend/src/api/notice/comment/index.ts
> +};
임시로 사용했던건데 남아있었군요.  
삭제했습니다 :D 
[01fe858](https://github.com/woowacourse-teams/2022-moamoa/pull/449/commits/01fe858f07ec4a56d66e13a2d567f24c780179dc)

2022-10-27 16:52 UTC, airman5573 commented on frontend/src/mocks/handlers/communityHandler.ts
> +import { ApiCommunityDraftArticle, ApiCommunityDraftArticleToArticle } from '@api/community/draft-article';
수정했습니다 :D  
[ffb7ccc](https://github.com/woowacourse-teams/2022-moamoa/pull/449/commits/ffb7cccccf4fcebd93c393292273a0c8fe70f008)

2022-10-27 16:54 UTC, airman5573 commented on frontend/src/pages/study-room-page/components/comment-edit-form/CommentEditForm.tsx
> +import LetterCounter from '@components/@shared/letter-counter/LetterCounter';
다른것들도 함께 수정했습니다 :D  
[3c8578d](https://github.com/woowacourse-teams/2022-moamoa/pull/449/commits/3c8578d71104ff79e6ae66ddf838d4e382292133)

2022-10-27 17:01 UTC, airman5573 commented on frontend/src/pages/study-room-page/components/comment-edit-form/CommentEditForm.tsx
> +  onCancelEditButtonClick: Noop;
수정했습니다!  
[ce89fe2](https://github.com/woowacourse-teams/2022-moamoa/pull/449/commits/ce89fe24c6ef83f9bb46f511e1bcfb2fd088fa12)

2022-10-27 17:09 UTC, airman5573 commented on frontend/src/pages/study-room-page/components/comment-edit-form/CommentEditForm.tsx
> +import { FieldElement, makeValidationResult, useFormContext } from '@hooks/useForm';
전반적으로 type을 붙였습니다.  

[134954d](https://github.com/woowacourse-teams/2022-moamoa/pull/449/commits/134954d162ae2352d7c4f92fbfdea25d2ccd642f)

2022-10-27 17:17 UTC, airman5573 commented on frontend/src/pages/study-room-page/components/comment-edit-form/CommentEditForm.tsx
> +export default Object.assign(CommentEditForm, { CommentEditField });
올렸습니다!  
[c9b1dda](https://github.com/woowacourse-teams/2022-moamoa/pull/449/commits/c9b1dda1d57d2533a3b42f50c2340e21cbff37ab)

2022-10-27 18:08 UTC, airman5573 commented on frontend/src/pages/study-room-page/components/comment-edit-form/CommentEditForm.tsx
> +        {renderField(setCount)}
"onSubmit을 실행하기 전에 setCount를 초기화하는 방법은 안 될까요??"
=> 가능하고, 해결했습니다! (onSubmit 후에)
[8fe547b](https://github.com/woowacourse-teams/2022-moamoa/pull/449/commits/8fe547b64a629937868f8063818ec3060e77525e)

지금 이런 구조(CommentEditForm)가 나오게된 배경은 두가지 입니다.
1. CommentEditForm에 LetterCounter를 같이 두자(응집성, 반복줄이기)
2. CommentEditForm에 있는 Field에 props를 내려줘야하는데, CommentEditForm을 통해 내려주면 너무 props가 많아지고 어떤게 Field에 들어가는 props인지 Form에 들어가는 props인지 구분이 안되서 이렇게 합성 컴포넌트로 만든겁니다.
3. setCount를 함수의 인자로 내려주고 있는데, 이거는 useForm의 기능의 부재로 나온겁니다. react-hook-form 라이브러리 같은 경우에는 useWatch라는 기능을 제공해서 그 값을 감시할 수 있습니다. 이렇게 onChnage에 핸들러를 걸어주지 않아도 말이죠.

우선 배경은 이러하고, 이와는 별개로 저는 지금의 방식(useForm)이 두가지 장점이 있다고 봅니다.  
1. 비교적 적은 리렌더링
2. FormProvider안에 있는 input이라면 어디든 접근 가능하다는 점
사실 1번의 장점보다는 2번의 장점이 크다고 생각합니다.  
nested input의 값을 위로 올릴려면 onChange를 아래로 내려 줘야합니다. 그러면 prop drilling 이 발생해서 props가 지저분해집니다!  

그래서 저는 이 방식이 좋은데,  
태태의 제어 컴포넌트에 대한 생각이 어떤 느낌인지는 알겠으나 코드로 말씀해 주시면 비교분석이 수월해질것 같아요 !

2022-10-27 18:19 UTC, airman5573 commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/editable-comment/EditableComment.tsx
> +import Comment, { CommentProps } from '@study-room-page/components/comment/Comment';
[66031eb](https://github.com/woowacourse-teams/2022-moamoa/pull/449/commits/66031ebf88e190df967f8d236b45e0f971917209)

2022-10-27 18:21 UTC, airman5573 commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/edit/Edit.tsx
> +  ) => {
섬세하시군요!
[4d40a7a](https://github.com/woowacourse-teams/2022-moamoa/pull/449/commits/4d40a7a7d52e23d72fcbb75a7f47206b51bbc29e)

2022-10-27 18:22 UTC, airman5573 commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/edit-content/EditContent.tsx
> +export default EditContent;
👍 
[518a873](https://github.com/woowacourse-teams/2022-moamoa/pull/449/commits/518a8734614fd0cb5d3d681cd597df8ba5a2ba08)

2022-10-27 18:24 UTC, airman5573 commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/comment-list/CommentList.tsx
> +const Self = styled.div``;
👍 
[575b301](https://github.com/woowacourse-teams/2022-moamoa/pull/449/commits/575b30142fd3ac74b815c29491f6d8a098f01816)

2022-10-27 18:46 UTC, airman5573 commented on frontend/src/pages/study-room-page/tabs/review-tab-panel/components/reivew-form/ReviewForm.tsx
> +        }}
[위 댓글](https://github.com/woowacourse-teams/2022-moamoa/pull/449#discussion_r1007208067) 확인 바랍니다.

2022-10-28 03:06 UTC, nan-noo commented on frontend/src/pages/study-room-page/components/comment-edit-form/CommentEditForm.tsx
> +        {renderField(setCount)}
2번은 제어 컴포넌트도 useReducer와 Context API를 결합해서 만들면 되지 않을까요?? 저는 예전에 카드 미션할 때 그렇게 구현했었습니다.

## 오프라인 대화
- useForm 기능을 추가해서 보완할 수 있다. - reset, watch 기능이 아직 없다
- 제어 컴포넌트가 React로 구현할 때는 더 이해하기 쉬운 것 같다(동일 출처 원칙 등)

LetterCounter 훅(useLetterCount)이 필요할까?

### renderField와 관련한 컴포넌트 분리
- 스타일이 동일해서 컴포넌트로 분리하다 보니까 필요한 props가 많아졌다. 인풋에 필요한 props와 폼에 필요한 props를 분리하기 위해 renderField로 만든 것
- 스타일만을 분리할 수는 없을까??

등등

기억나는대로 작성해봤습니다

2022-10-28 03:08 UTC, airman5573 commented on frontend/src/pages/my-study-page/components/my-study-card/MyStudyCard.tsx
> +import React from 'react';
1. 에러는 뜨지 않았습니다!
2. 불필요한 import React를 삭제했습니다 [d03d684](https://github.com/woowacourse-teams/2022-moamoa/pull/449/commits/d03d684d6c2cd3ad0c6493b688d0b7abfca45121)
3. 그런데 에러가 떠야한다고 생각한 이유가 무엇일까요?

2022-10-28 03:26 UTC, airman5573 commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/comment-edit-form/CommentEditForm.tsx
> +const CommentEditForm: React.FC<CommentEditFormProps> = ({
좋은 생각입니다!  

📦community-tab-panel
 ┣ 📂components
 ┃ ┣ 📂article
 ┃ ┃ ┗ 📜CommunityArticle.tsx
 ┃ ┣ 📂article-edit
 ┃ ┃ ┗ 📜CommunityArticleEdit.tsx
 ┃ ┣ 📂article-edit-content
 ┃ ┃ ┗ 📜CommunityArticleEditContent.tsx
 ┃ ┣ 📂article-editable-comment
 ┃ ┃ ┗ 📜CommunityEditableComment.tsx
 ┃ ┣ 📂article-list
 ┃ ┃ ┗ 📜CommunityArticleList.tsx
 ┃ ┣ 📂article-list-item
 ┃ ┃ ┗ 📜CommunityArticleListItem.tsx
 ┃ ┣ 📂article-list-page
 ┃ ┃ ┗ 📜CommunityArticleListPage.tsx
 ┃ ┣ 📂article-publish
 ┃ ┃ ┗ 📜CommunityArticlePublish.tsx
 ┃ ┣ 📂comment-edit-form
 ┃ ┃ ┗ 📜CommunityCommentEditForm.tsx
 ┃ ┣ 📂comment-form
 ┃ ┃ ┗ 📜CommunityCommentForm.tsx
 ┃ ┣ 📂comment-list
 ┃ ┃ ┗ 📜CommunityCommentList.tsx
 ┃ ┣ 📂comment-section
 ┃ ┃ ┗ 📜CommunityCommentSection.tsx
 ┃ ┗ 📂draft-save-button
 ┃ ┃ ┗ 📜CommunityDraftArticleSaveButton.tsx
 ┣ 📂inner-pages
 ┃ ┗ 📂draft-article-publish
 ┃ ┃ ┗ 📜CommunityDraftArticlePublish.tsx
 ┗ 📜CommunityTabPanel.tsx

이런 구조로 가는건 어떨까요?  
폴더는 general하게, 파일은 specific하게!

2022-10-28 04:52 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/comment-list/CommentList.tsx
> +// 그냥 useGetCommunityComments를 두번 호출하는건 별로인가?
음 아니면 여러번 사용하지 않는 ~~리스트를 굳이 분리해야 할까요??
// page component
const {refetch, ... } = ...

const handleEdit...
...

return (
<ReviewForm섹션 ... />
<Divider />
<ReviewList>
{array.map(el => <ReviewItem />)}
</ReviewList>
...

요런식으로 보여줘도 충분히 리스트라는 것을 나타낼 것 같은데(children으로 받는 느낌) 어떻게 생각하나요?? (근데 저도 이렇게 적용 안 한 부분이 좀 있는 것 같습니다 ㅎㅎ)

2022-10-28 05:32 UTC, nan-noo requested changes
코멘트 몇가지만 남겼습니다!

2022-10-28 05:32 UTC, nan-noo commented on frontend/src/api/community/comments/index.ts
> +  page,
default 값을 상수로 만들어서 주는 건 어떨까요?

  page = PAGE,
  size = SIZE,

2022-10-28 05:32 UTC, nan-noo commented on frontend/src/api/community/comments/index.ts
> +  }
size와 url이 모두 있을 때의 결과값이

`/api/studies/${studyId}/community/${articleId}/comments?size=${size}?page=${page}`가 될 것 같은데,
`/api/studies/${studyId}/community/${articleId}/comments?size=${size}&page=${page}` 가 되어야 하지 않을까요?

2022-10-28 05:32 UTC, nan-noo commented on frontend/src/pages/my-study-page/components/my-study-card/MyStudyCard.tsx
> +import React from 'react';
제가 구현할 때 자동 import가 된 적이 있었는데, eslint 에러가 뜨더라구요!

2022-10-28 05:32 UTC, nan-noo commented on frontend/src/api/community/comments/index.ts
> +};
이 훅은 사용하고 있나요??

2022-10-28 05:32 UTC, nan-noo commented on frontend/src/api/notice/comments/index.ts
> +  const response = await axiosInstance.get<ApiNoticeComments['get']['responseData']>(url);
이부분도 위쪽에 남긴 코멘트와 마찬가지입니다 :D

2022-10-28 05:32 UTC, nan-noo commented on frontend/src/pages/study-room-page/components/comment-edit-form/CommentEditForm.tsx
> +    setCount(0);
👍

2022-10-28 05:37 UTC, nan-noo commented on frontend/src/api/community/comments/index.ts
> +  page,
default 값을 주면 아래 코드와 같이 if문을 사용하는 일은 없을 것 같습니다!

아니면 아래 같은 방법도 있을 것 같아요

```ts
const pageParams = page && `page=${page}`;
const sizeParams = size && `page=${size}`;
const url = `/api/studies/${studyId}/community/${articleId}/comments?${pageParams}&${sizeParams}`;
```

2022-10-28 08:44 UTC, airman5573 commented on frontend/src/pages/study-room-page/tabs/community-tab-panel/components/comment-list/CommentList.tsx
> +// 그냥 useGetCommunityComments를 두번 호출하는건 별로인가?
제안해주신 코드로 한정해서 보자면,  
저는 ReviewList는 따로 분리를 하고 그 안에서 api요청을 하는 편이 가독성에 더 좋지 않나 싶습니다.  
예를들어서  
```jsx
<ReviewSection>
  <ReviewForm />
  <Divider />
  <ReviewList />
</ReviewSection>
```
이런식이면 구조가 한눈에 들어옵니다.

2022-10-28 08:54 UTC, airman5573 commented on frontend/src/pages/study-room-page/components/comment-edit-form/CommentEditForm.tsx
> +        {renderField(setCount)}
정리 감사합니다 !  

"2번은 제어 컴포넌트도 useReducer와 Context API를 결합해서 만들면 되지 않을까요??" => 맞습니다, 가능은 한데 useForm을 사용했을 때 더 코드가 간결할듯 싶습니다. (dispatch나 switch가 필요 없어서)

나머지는 같이 고민해봅시다 :D

2022-10-28 10:20 UTC, airman5573 commented on frontend/src/api/community/comments/index.ts
> +  page,
결론 : 상수로 만들어 주는것이 합당하다!  

현재 api 규칙은 다음과 같습니다.
1. size(x) & page(x) => 모든 comments
2. size(o) & page(x) => Error
3. size(x) & page(o) => Error
4. size(o) & page(o) => 정상 comments
그리고 getCommunityComments는 pagination에만 사용되고 있습니다.  
그래서 comments 전체를 불러올 일은 없기에 pagination만 고려해 default값을 상수로 넣어주자는 의견에 동의합니다.  

그나저나, 마지막에 보내주신 예제는 undefined가 string으로 들어갑니다.
[예제코드](https://playcode.io/997406)에서 확인 가능 합니다.

2022-10-28 10:54 UTC, airman5573 commented on frontend/src/api/community/comments/index.ts
> +  }
맞습니다, 제가 실수했네요 👍

2022-10-28 11:04 UTC, airman5573 commented on frontend/src/api/community/comments/index.ts
> +};
다른 댓글에 대한 답도 여기에 일괄적으로 남기겠습니다.  

1. 사용하지 않는 api 함수 및 훅을 삭제했습니다
2. getCommunityCommentsWithPage -> getCommunityComments 로 변경했습니다. 어차피 pagination이 적용되기 때문에 굳이 분리할 필요가 없다고 생각하기 때문입니다.
3. 밖으로 내보일 필요 없는 api 함수들은 export를 제거했습니다.

2022-10-28 17:42 UTC, airman5573 commented on README.md
>  ## ⚙️ 인프라 구조
수정했습니다 :D  
[178b96c](https://github.com/woowacourse-teams/2022-moamoa/pull/449/commits/178b96c438d8a22d5e7cefbef850eba70c187400)

2022-10-31 05:17 UTC, nan-noo requested changes

2022-10-31 05:17 UTC, nan-noo commented on frontend/src/api/community/comments/index.ts
> +import buildURLQuery from '@utils/buildURLQuery';
utils 폴더의 Index 파일에 추가하는 건 어떨까요?

2022-10-31 05:17 UTC, nan-noo commented on frontend/src/api/reviews/index.ts
> +// getStudyReviews와 getStudyReviewsWithPage를 구분해 줘야 합니다.
getStudyReviewWithPage가 존재하지 않는 것 같아요!

2022-10-31 05:17 UTC, nan-noo commented on frontend/src/pages/study-room-page/tabs/review-tab-panel/ReviewTabPanel.tsx
> +  const { data, isFetching, refetch, isError, isSuccess } = useGetStudyReviews({
백엔드가 페이지네이션이 안 되어 있군요!

2022-10-31 05:17 UTC, nan-noo commented on frontend/src/utils/buildURLQuery.ts
> +  const validEntries = Object.entries(obj).filter<[string, string | number]>(isValidEntry);
오 필터링을 하는군요! 그러면 필터링된 length랑 그 전에 length랑 다르면 console.error를 출력하는 건 어떨까요?

2022-10-31 05:17 UTC, nan-noo commented on frontend/src/api/notice/article/index.ts
> +// @TODO: 함수 위치 변경
아 잘못 봤습니다!

2022-10-31 05:17 UTC, nan-noo commented on frontend/src/api/reviews/index.ts
> +// getStudyReviews와 getStudyReviewsWithPage를 구분해 줘야 합니다.
아직 백엔드가 구현되지 않았군요!

2022-10-31 08:23 UTC, airman5573 commented on frontend/src/api/community/comments/index.ts
> +import buildURLQuery from '@utils/buildURLQuery';
좋습니다 👍

2022-10-31 08:25 UTC, airman5573 commented on frontend/src/utils/buildURLQuery.ts
> +  const validEntries = Object.entries(obj).filter<[string, string | number]>(isValidEntry);
-- 회의내용 --
사용처에서 { title: 'abc', tags: undefined } 이렇게 넣을 수도 있기 때문에 에러라고 단정 짓기 어렵다.  
결론: 현행유지

2022-11-01 01:27 UTC, nan-noo approved these changes

2022-11-01 01:27 UTC, merged