[BE] issue60: Filter로 필터링하여 스터디 목록 조회
woowacourse-teams/2022-moamoa pull request #69
Opened 2022-07-17 06:00 UTC by tco0427

## 요약

필터를 통해서 필터링하여 스터디 목록을 조회할 수 있다.

## 세부사항

- 필터로 필터링한 내용과 제목 검색을 함께 조합해 스터디 목록을 조회할 수 있다.
- 같은 카테고리의 필터로 필터링하여 스터디 목록을 조회할 수 있다. (검색 조건 : OR)
- 서로 다른 카테고리의 필터로 필터링하여 스터디 목록을 조회할 수 있다. (검색 조건 : AND)

close #60

2022-07-17 13:55 UTC, wilgur513 requested changes

2022-07-17 13:55 UTC, wilgur513 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/studyfilter/repository/CustomStudyFilterRepositoryTest.java
> +    }
실패 케이스 찾았습니다...
`4기`, `BE`, `FE`로 필터링할 경우 `Java 스터디`, `React 스터디`, `알고리즘 스터디`가 나와야 하는데
`Java 스터디`, `React 스터디`만 나오네요 ㅠㅠ

2022-07-17 13:55 UTC, wilgur513 commented on backend/src/main/resources/data.sql
> +INSERT INTO study_filter(study_id, filter_id) VALUES (5, 4);
알고리즘 스터디에 `4기`, `BE`, `FE`를 추가했습니다

2022-07-17 13:55 UTC, wilgur513 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/study/Study.java
> +    }
테스트 로그 확인용으로 toString 추가했어요

2022-07-17 14:04 UTC, jaejae-yoo reviewed
디우 구현양이 많아서 고생하셨을 것 같네요 수고하셨습니다 👍 
궁금한 부분과 피드백 남겼습니다! 
확인 부탁드려요 ~

2022-07-17 14:04 UTC, jaejae-yoo commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/studyfilter/repository/CustomStudyFilterRepositoryImpl.java
> +        removeLastOne(studies, hasNext);
마지막 스터디를 왜 삭제하는지 궁금해요!

2022-07-18 03:21 UTC, sc0116 reviewed
디우 코멘트 달았어요! 근데 코드 조금 더 이해하고 추가적으로 달게요!

2022-07-18 03:21 UTC, sc0116 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/StudyFilterService.java
> +        if (filterRequest == null || filterRequest.isEmpty()) {
앗 근데 공백은 검사 안해도 되는건가용?

2022-07-18 06:52 UTC, tco0427 commented on backend/src/test/java/com/woowacourse/moamoa/study/domain/studyfilter/repository/CustomStudyFilterRepositoryTest.java
> +    }
오늘 오전 회의에서 말씀해주신 것 처럼..위 테스트의 경우에는 Java 스터디와 JavaScript 스터디만 조회되어야할 것 같아요..!! (title이 "java" 여서..!)

관련해서 테스트 케이스 추가해놓았습니다~_~👍

2022-07-18 06:55 UTC, tco0427 commented on backend/src/main/resources/data.sql
> +INSERT INTO study_filter(study_id, filter_id) VALUES (5, 4);
테스트 코드 추가한 후에 `force push` 해서..ㅠㅠ 혹시 테스트 코드를 위한 것이라면 추가 안해도 괜찮을 것 같습니다!!
(Conflict 해결하면서 다시 봐보죠!!😁)

2022-07-18 06:56 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/study/Study.java
> +    }
위와 같은 이유로...ㅠ.ㅠ

2022-07-18 06:57 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/MoamoaApplication.java
> +    public JPAQueryFactory jpaQueryFactory(EntityManager entityManager) {
오홍..좋은 것 같습니다..!! 혹은 그냥 `CustomStudyFilterRepositoryImpl` 에서 생성자 주입으로 생성해줄 수 있어서 수정해볼게요!

2022-07-18 06:57 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/service/StudyFilterService.java
> +        if (filterRequest == null || filterRequest.isEmpty()) {
filterRequest로 오는 3가지 List 들의 사이즈가 0이어도 문제가 생기더라구요...ㅠㅠ 다시 한 번 확인해보겠습님다!😃

2022-07-18 06:59 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/studyfilter/repository/CustomStudyFilterRepositoryImpl.java
> +        removeLastOne(studies, hasNext);
1개를 추가로 가져오기 때문에(다음 페이지를 위한 데이터가 존재하는지 여부를 확인하기 위해서, 실제 Slice 내부 동작(쿼리)도 동일) 만약 다음 페이지가 존재하면 마지막 요소 하나를 빼고 반환해주어야 합니다!!🙂

2022-07-18 07:00 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/studyfilter/repository/CustomStudyFilterRepositoryImpl.java
> +            result.removeIf(finalStudy -> !studies.contains(finalStudy));
저도 현재 코드가 가독성이 완전 좋은 것 같지는 않아서..고민이 많네요..ㅠ.ㅠ 린론 의견을 포함해서 고민 후 개선해보도록 하겠습니다..!!

2022-07-18 07:00 UTC, tco0427 commented on backend/src/main/java/com/woowacourse/moamoa/study/domain/studyfilter/repository/CustomStudyFilterRepositoryImpl.java
> +            final List<Study> studies = findStudyWithFilter(categorizedFilters);
https://github.com/woowacourse-teams/2022-moamoa/pull/69#discussion_r923021404

2022-07-19 02:01 UTC, closed without merging